/*
 * Copyright (c) 2025. RecruitCRM
 * All rights reserved.
 */

package io.recruitcrm.microservice.timesheet.access_control.recruitcrm.core;

public enum GlobalPermission {

	REPORTS, RECRUITER_PERFORMANCE_REPORT, CANDIDATE_LIFECYCLE_REPORT, CLIENT_PERFORMANCE_REPORT, JOB_STATISTIC_REPORT,
	DEAL_REPORT, EXPORT_TO_CSV, BULK_UPDATE_FIELD, BULK_DELETE, ADMIN_SETTINGS, PLANS_AND_BILLING, USER_MANAGEMENT,
	ROLES_PERMISSIONS, TEAMS, ACCOUNT_MANAGEMENT, EMAIL_TRIGGERS, SALES_PIPELINE, HIRING_PIPELINE, DEALS_PIPELINE,
	JOB_STATUS, CUSTOMIZE_INVOICE, FIELDS_SHARED_WITH_CLIENT, CANDIDATE_FIELDS, COMPANY_FIELDS, CONTACT_FIELDS,
	DEAL_FIELDS, JOB_FIELDS, PUBLIC_JOB_PAGE_SETTINGS, JOB_APPLICATION_FORM_SETTINGS, PROFILE_UPDATE_FORM_SETTINGS,
	TALENT_POOL_PAGE_SETTINGS, API_INTEGRATIONS, JOB_BOARD_INTEGRATIONS, CALLING_INTEGRATIONS, CALL_TYPE_CUSTOMIZATION,
	NOTE_TYPE_CUSTOMIZATION, PITCH_CANDIDATE_PIPELINE, STANDARD_EMAIL_TEMPLATES, RESUME_FORMATTING, HIDE_EMAIL,
	BLACKLIST_EMAIL_ID, SMS_TEMPLATES, IP_RESTRICTION, TIME_TO_HIRE_REPORT, ACCOUNT_OVERVIEW_REPORT, DEALS_BY_TEAM,
	EXECUTIVE_SEARCH_REPORT, EXTERNAL_JOB_BOARD_INTEGRATION, MEETING_TYPE_CUSTOMIZATION, CUSTOM_XML_SETTINGS,
	ACTIVITY_TEMPLATES, WORKFLOW_AUTOMATION, SENT_EMAIL_KPI_REPORT, ADVANCED_ANALYTICS, ALLOW_TO_CHOOSE_OWN_FIELDS,
	RECORD_CALLS_BY_DEFAULT, ALLOW_TO_CHOOSE_CALL_RECORD, ALLOW_TO_DOWNLOAD_RECORDS, TASK_TYPE_CUSTOMIZATION,
	TARGET_REPORT, PRIVATE_EMAILS, ALL_CONNECTED_EMAIL, DATA_ENRICHMENT, TARGET_REPORT_CREATE_ACCESS

}