package io.recruitcrm.microservice.timesheet.dto.kafka;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.Objects;

/**
 * Payload for {@code {env}-reminder-notification} when publishing timesheet lifecycle
 * events. More fields may be added later; keep this type backward-compatible for
 * consumers.
 *
 * @param eventId Unique identifier for idempotency (UUID); generated by producer.
 * @param timesheetIds Identifiers of the timesheet rows that were created or updated
 * (JSON key {@code timesheetIds}).
 * @param eventName Human-readable event label, e.g.
 * {@link #EVENT_NAME_TIMESHEET_CREATED}.
 * @param accountId Account that performed the action; {@code null} for aggregated CRON
 * digests.
 * @param createdByUserTypeId User type id of the actor; {@code null} for aggregated CRON
 * digests.
 * @param reminderForUserTypeId Audience for the reminder; {@code null} for aggregated
 * CRON digests.
 * @param eventType Realtime vs CRON.
 * @param sendInappNotification Whether to send in-app notification.
 * @param sendEmailNotification Whether to send email notification.
 * @param sendPortalNotification Whether to send portal notification.
 * @param performerName Display name of the actor (agency user username / name, or contact
 * first+last name); {@code null} when not provided.
 * @param cronWindow CRON window bounds ({@link TimesheetReminderCronWindowDto});
 * {@code null} for realtime events.
 * @param reimbursementIds Identifiers of reimbursement rows affected by the event (JSON
 * key {@code reimbursementIds}); {@code null} when not applicable (e.g. pure timesheet
 * events).
 */
public record TimesheetReminderNotificationPayloadDto(String eventId,
		@JsonProperty("timesheetIds") ArrayList<Integer> timesheetIds, String eventName, Integer accountId,
		Integer createdByUserTypeId, Integer reminderForUserTypeId, ReminderNotificationEventType eventType,
		@JsonProperty("sendInappNotification") boolean sendInappNotification,
		@JsonProperty("sendEmailNotification") boolean sendEmailNotification,
		@JsonProperty("sendPortalNotification") boolean sendPortalNotification,
		@JsonProperty("performerName") String performerName,
		@JsonProperty("cronWindow") TimesheetReminderCronWindowDto cronWindow,
		@JsonProperty("reimbursementIds") @JsonInclude(JsonInclude.Include.NON_NULL) ArrayList<Integer> reimbursementIds) {

	/**
	 * Backward-compatible constructor without {@code reimbursementIds} (defaults to
	 * {@code null}).
	 */
	public TimesheetReminderNotificationPayloadDto(final String eventId, final ArrayList<Integer> timesheetIds,
			final String eventName, final Integer accountId, final Integer createdByUserTypeId,
			final Integer reminderForUserTypeId, final ReminderNotificationEventType eventType,
			final boolean sendInappNotification, final boolean sendEmailNotification,
			final boolean sendPortalNotification, final String performerName,
			final TimesheetReminderCronWindowDto cronWindow) {
		this(eventId, timesheetIds, eventName, accountId, createdByUserTypeId, reminderForUserTypeId, eventType,
				sendInappNotification, sendEmailNotification, sendPortalNotification, performerName, cronWindow, null);
	}

	public static final String EVENT_NAME_TIMESHEET_CREATED = "timesheet.created";

	public static final String EVENT_NAME_TIMESHEET_APPROVED = "timesheet.approved";

	public static final String EVENT_NAME_TIMESHEET_REJECTED = "timesheet.rejected";

	public static final String EVENT_NAME_TIMESHEET_SUBMITTED = "timesheet.submitted";

	public static final String EVENT_NAME_TIMESHEET_REMINDER_SUBMITTED = "timesheet.reminder.submitted";

	public static final String EVENT_NAME_REIMBURSEMENT_SUBMITTED = "timesheet.reimbursement.submitted";

	public static final String EVENT_NAME_REIMBURSEMENT_APPROVED = "timesheet.reimbursement.approved";

	public static final String EVENT_NAME_REIMBURSEMENT_REJECTED = "timesheet.reimbursement.rejected";

	public static final String EVENT_NAME_REIMBURSEMENT_REMINDER_SUBMITTED = "timesheet.reimbursement.reminder.submitted";

	public static final String EVENT_NAME_REIMBURSEMENT_SHARED_WITH_CLIENT_UPDATED = "timesheet.reimbursement.shared_with_client.updated";

	public TimesheetReminderNotificationPayloadDto {
		Objects.requireNonNull(eventId, "eventId");
		if (eventId.isBlank()) {
			throw new IllegalArgumentException("eventId must not be blank");
		}
		Objects.requireNonNull(timesheetIds, "timesheetIds");
		if (timesheetIds.isEmpty()) {
			throw new IllegalArgumentException("timesheetIds must not be empty");
		}
		Objects.requireNonNull(eventName, "eventName");
		if (eventName.isBlank()) {
			throw new IllegalArgumentException("eventName must not be blank");
		}
		Objects.requireNonNull(eventType, "eventType");
		if (eventType == ReminderNotificationEventType.CRON) {
			Objects.requireNonNull(cronWindow, "cronWindow");
		}
		else {
			Objects.requireNonNull(accountId, "accountId");
			Objects.requireNonNull(createdByUserTypeId, "createdByUserTypeId");
			Objects.requireNonNull(reminderForUserTypeId, "reminderForUserTypeId");
		}
		if (reimbursementIds != null && reimbursementIds.isEmpty()) {
			throw new IllegalArgumentException("reimbursementIds must not be empty when provided");
		}
	}

}
