/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcandidate.TblcandidatePath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CandidateLastActivitiesTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CandidateLastActivitiesT extends TableImpl<CandidateLastActivitiesTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>candidate_last_activities_t</code>
	 */
	public static final CandidateLastActivitiesT CANDIDATE_LAST_ACTIVITIES_T = new CandidateLastActivitiesT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CandidateLastActivitiesTRecord> getRecordType() {
		return CandidateLastActivitiesTRecord.class;
	}

	/**
	 * The column <code>candidate_last_activities_t.id</code>.
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>candidate_last_activities_t.candidate_id</code>. Candidate id from
	 * tblcandidate
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> CANDIDATE_ID = createField(
			DSL.name("candidate_id"), SQLDataType.INTEGER.nullable(false), this, "Candidate id from tblcandidate");

	/**
	 * The column <code>candidate_last_activities_t.calllog_id</code>. Last Calllog id
	 * from tblcalllog
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> CALLLOG_ID = createField(DSL.name("calllog_id"),
			SQLDataType.INTEGER, this, "Last Calllog id from tblcalllog");

	/**
	 * The column <code>candidate_last_activities_t.calllog_created_on</code>. Last
	 * Calllog Created Timestamp
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> CALLLOG_CREATED_ON = createField(
			DSL.name("calllog_created_on"), SQLDataType.INTEGER, this, "Last Calllog Created Timestamp");

	/**
	 * The column <code>candidate_last_activities_t.calllog_created_by</code>. Last
	 * Calllog Created By
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> CALLLOG_CREATED_BY = createField(
			DSL.name("calllog_created_by"), SQLDataType.INTEGER, this, "Last Calllog Created By");

	/**
	 * The column <code>candidate_last_activities_t.sms_id</code>. Last SMS id of
	 * conversation_message_t
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> SMS_ID = createField(DSL.name("sms_id"),
			SQLDataType.INTEGER, this, "Last SMS id of conversation_message_t");

	/**
	 * The column <code>candidate_last_activities_t.sms_sent_on</code>. Last SMS Sent
	 * Timestamp
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> SMS_SENT_ON = createField(DSL.name("sms_sent_on"),
			SQLDataType.INTEGER, this, "Last SMS Sent Timestamp");

	/**
	 * The column <code>candidate_last_activities_t.sms_sent_by</code>. Last SMS Sent By
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> SMS_SENT_BY = createField(DSL.name("sms_sent_by"),
			SQLDataType.INTEGER, this, "Last SMS Sent By");

	/**
	 * The column <code>candidate_last_activities_t.email_sent_on</code>. Last Email Sent
	 * Timestamp
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> EMAIL_SENT_ON = createField(
			DSL.name("email_sent_on"), SQLDataType.INTEGER, this, "Last Email Sent Timestamp");

	/**
	 * The column <code>candidate_last_activities_t.email_sent_by</code>. Last Email Sent
	 * By
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> EMAIL_SENT_BY = createField(
			DSL.name("email_sent_by"), SQLDataType.INTEGER, this, "Last Email Sent By");

	/**
	 * The column <code>candidate_last_activities_t.last_communication_method</code>.
	 * Values can be email, sms, calllog, meeting,linkedin message
	 */
	public final TableField<CandidateLastActivitiesTRecord, String> LAST_COMMUNICATION_METHOD = createField(
			DSL.name("last_communication_method"), SQLDataType.VARCHAR(10), this,
			"Values can be email, sms, calllog, meeting,linkedin message");

	/**
	 * The column <code>candidate_last_activities_t.last_communication_timestamp</code>.
	 * Last Communication Timestamp
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> LAST_COMMUNICATION_TIMESTAMP = createField(
			DSL.name("last_communication_timestamp"), SQLDataType.INTEGER, this, "Last Communication Timestamp");

	/**
	 * The column <code>candidate_last_activities_t.meeting_id</code>. Stores ID of the
	 * last meeting associated with tblnotetaskappointment
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> MEETING_ID = createField(DSL.name("meeting_id"),
			SQLDataType.INTEGER, this, "Stores ID of the last meeting associated with tblnotetaskappointment");

	/**
	 * The column <code>candidate_last_activities_t.meeting_created_on</code>. Unix
	 * timestamp of when the meeting was created
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> MEETING_CREATED_ON = createField(
			DSL.name("meeting_created_on"), SQLDataType.INTEGER, this,
			"Unix timestamp of when the meeting was created");

	/**
	 * The column <code>candidate_last_activities_t.meeting_created_by</code>. User ID of
	 * the person who created the meeting
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> MEETING_CREATED_BY = createField(
			DSL.name("meeting_created_by"), SQLDataType.INTEGER, this, "User ID of the person who created the meeting");

	/**
	 * The column <code>candidate_last_activities_t.message_id</code>. Id of linkedin
	 * message sent from RCRM
	 */
	public final TableField<CandidateLastActivitiesTRecord, String> MESSAGE_ID = createField(DSL.name("message_id"),
			SQLDataType.VARCHAR(255), this, "Id of linkedin message sent from RCRM");

	/**
	 * The column <code>candidate_last_activities_t.message_sent_on</code>. Unix timestamp
	 * of linkedin message sent
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> MESSAGE_SENT_ON = createField(
			DSL.name("message_sent_on"), SQLDataType.INTEGER, this, "Unix timestamp of linkedin message sent");

	/**
	 * The column <code>candidate_last_activities_t.message_sent_by</code>. User ID of the
	 * person sended linkedin message
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> MESSAGE_SENT_BY = createField(
			DSL.name("message_sent_by"), SQLDataType.INTEGER, this, "User ID of the person sended linkedin message");

	/**
	 * The column <code>candidate_last_activities_t.note_id</code>. Stores ID of the last
	 * note associated with tblnotetaskappointment
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> NOTE_ID = createField(DSL.name("note_id"),
			SQLDataType.INTEGER, this, "Stores ID of the last note associated with tblnotetaskappointment");

	/**
	 * The column <code>candidate_last_activities_t.note_created_on</code>. Unix timestamp
	 * of when the note was created
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> NOTE_CREATED_ON = createField(
			DSL.name("note_created_on"), SQLDataType.INTEGER, this, "Unix timestamp of when the note was created");

	/**
	 * The column <code>candidate_last_activities_t.note_created_by</code>. User ID of the
	 * person who created the note
	 */
	public final TableField<CandidateLastActivitiesTRecord, Integer> NOTE_CREATED_BY = createField(
			DSL.name("note_created_by"), SQLDataType.INTEGER, this, "User ID of the person who created the note");

	private CandidateLastActivitiesT(Name alias, Table<CandidateLastActivitiesTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private CandidateLastActivitiesT(Name alias, Table<CandidateLastActivitiesTRecord> aliased, Field<?>[] parameters,
			Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>candidate_last_activities_t</code> table reference
	 */
	public CandidateLastActivitiesT(String alias) {
		this(DSL.name(alias), CANDIDATE_LAST_ACTIVITIES_T);
	}

	/**
	 * Create an aliased <code>candidate_last_activities_t</code> table reference
	 */
	public CandidateLastActivitiesT(Name alias) {
		this(alias, CANDIDATE_LAST_ACTIVITIES_T);
	}

	/**
	 * Create a <code>candidate_last_activities_t</code> table reference
	 */
	public CandidateLastActivitiesT() {
		this(DSL.name("candidate_last_activities_t"), null);
	}

	public <O extends Record> CandidateLastActivitiesT(Table<O> path,
			ForeignKey<O, CandidateLastActivitiesTRecord> childPath,
			InverseForeignKey<O, CandidateLastActivitiesTRecord> parentPath) {
		super(path, childPath, parentPath, CANDIDATE_LAST_ACTIVITIES_T);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class CandidateLastActivitiesTPath extends CandidateLastActivitiesT
			implements Path<CandidateLastActivitiesTRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> CandidateLastActivitiesTPath(Table<O> path,
				ForeignKey<O, CandidateLastActivitiesTRecord> childPath,
				InverseForeignKey<O, CandidateLastActivitiesTRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private CandidateLastActivitiesTPath(Name alias, Table<CandidateLastActivitiesTRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public CandidateLastActivitiesTPath as(String alias) {
			return new CandidateLastActivitiesTPath(DSL.name(alias), this);
		}

		@Override
		public CandidateLastActivitiesTPath as(Name alias) {
			return new CandidateLastActivitiesTPath(alias, this);
		}

		@Override
		public CandidateLastActivitiesTPath as(Table<?> alias) {
			return new CandidateLastActivitiesTPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<CandidateLastActivitiesTRecord, Integer> getIdentity() {
		return (Identity<CandidateLastActivitiesTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<CandidateLastActivitiesTRecord> getPrimaryKey() {
		return Keys.KEY_CANDIDATE_LAST_ACTIVITIES_T_PRIMARY;
	}

	@Override
	public List<UniqueKey<CandidateLastActivitiesTRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_CANDIDATE_LAST_ACTIVITIES_T_CANDIDATE_ID);
	}

	@Override
	public List<ForeignKey<CandidateLastActivitiesTRecord, ?>> getReferences() {
		return Arrays.asList(Keys.CANDIDATE_LAST_ACTIVITIES_T_IBFK_1);
	}

	private transient TblcandidatePath _tblcandidate;

	/**
	 * Get the implicit join path to the <code>tblcandidate</code> table.
	 */
	public TblcandidatePath tblcandidate() {
		if (_tblcandidate == null)
			_tblcandidate = new TblcandidatePath(this, Keys.CANDIDATE_LAST_ACTIVITIES_T_IBFK_1, null);

		return _tblcandidate;
	}

	@Override
	public CandidateLastActivitiesT as(String alias) {
		return new CandidateLastActivitiesT(DSL.name(alias), this);
	}

	@Override
	public CandidateLastActivitiesT as(Name alias) {
		return new CandidateLastActivitiesT(alias, this);
	}

	@Override
	public CandidateLastActivitiesT as(Table<?> alias) {
		return new CandidateLastActivitiesT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CandidateLastActivitiesT rename(String name) {
		return new CandidateLastActivitiesT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CandidateLastActivitiesT rename(Name name) {
		return new CandidateLastActivitiesT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CandidateLastActivitiesT rename(Table<?> name) {
		return new CandidateLastActivitiesT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateLastActivitiesT where(Condition condition) {
		return new CandidateLastActivitiesT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateLastActivitiesT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateLastActivitiesT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateLastActivitiesT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CandidateLastActivitiesT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CandidateLastActivitiesT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CandidateLastActivitiesT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CandidateLastActivitiesT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateLastActivitiesT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateLastActivitiesT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
