/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcandidate.TblcandidatePath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CandidateCustomFieldsTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CandidateCustomFieldsT extends TableImpl<CandidateCustomFieldsTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>candidate_custom_fields_t</code>
	 */
	public static final CandidateCustomFieldsT CANDIDATE_CUSTOM_FIELDS_T = new CandidateCustomFieldsT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CandidateCustomFieldsTRecord> getRecordType() {
		return CandidateCustomFieldsTRecord.class;
	}

	/**
	 * The column <code>candidate_custom_fields_t.custom_field_id</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, Integer> CUSTOM_FIELD_ID = createField(
			DSL.name("custom_field_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>candidate_custom_fields_t.candidate_id</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, Integer> CANDIDATE_ID = createField(DSL.name("candidate_id"),
			SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn1</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN1 = createField(DSL.name("custcolumn1"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn2</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN2 = createField(DSL.name("custcolumn2"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn3</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN3 = createField(DSL.name("custcolumn3"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn4</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN4 = createField(DSL.name("custcolumn4"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn5</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN5 = createField(DSL.name("custcolumn5"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn6</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN6 = createField(DSL.name("custcolumn6"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn7</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN7 = createField(DSL.name("custcolumn7"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn8</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN8 = createField(DSL.name("custcolumn8"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn9</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN9 = createField(DSL.name("custcolumn9"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn10</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN10 = createField(DSL.name("custcolumn10"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn11</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN11 = createField(DSL.name("custcolumn11"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn12</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN12 = createField(DSL.name("custcolumn12"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn13</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN13 = createField(DSL.name("custcolumn13"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn14</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN14 = createField(DSL.name("custcolumn14"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn15</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN15 = createField(DSL.name("custcolumn15"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn16</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN16 = createField(DSL.name("custcolumn16"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn17</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN17 = createField(DSL.name("custcolumn17"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn18</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN18 = createField(DSL.name("custcolumn18"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn19</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN19 = createField(DSL.name("custcolumn19"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn20</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN20 = createField(DSL.name("custcolumn20"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn21</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN21 = createField(DSL.name("custcolumn21"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn22</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN22 = createField(DSL.name("custcolumn22"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn23</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN23 = createField(DSL.name("custcolumn23"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn24</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN24 = createField(DSL.name("custcolumn24"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn25</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN25 = createField(DSL.name("custcolumn25"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn26</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN26 = createField(DSL.name("custcolumn26"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn27</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN27 = createField(DSL.name("custcolumn27"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn28</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN28 = createField(DSL.name("custcolumn28"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn29</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN29 = createField(DSL.name("custcolumn29"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn30</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN30 = createField(DSL.name("custcolumn30"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn31</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN31 = createField(DSL.name("custcolumn31"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn32</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN32 = createField(DSL.name("custcolumn32"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn33</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN33 = createField(DSL.name("custcolumn33"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn34</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN34 = createField(DSL.name("custcolumn34"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn35</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN35 = createField(DSL.name("custcolumn35"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn36</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN36 = createField(DSL.name("custcolumn36"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn37</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN37 = createField(DSL.name("custcolumn37"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn38</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN38 = createField(DSL.name("custcolumn38"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn39</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN39 = createField(DSL.name("custcolumn39"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn40</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN40 = createField(DSL.name("custcolumn40"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn41</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN41 = createField(DSL.name("custcolumn41"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn42</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN42 = createField(DSL.name("custcolumn42"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn43</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN43 = createField(DSL.name("custcolumn43"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn44</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN44 = createField(DSL.name("custcolumn44"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn45</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN45 = createField(DSL.name("custcolumn45"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn46</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN46 = createField(DSL.name("custcolumn46"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn47</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN47 = createField(DSL.name("custcolumn47"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn48</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN48 = createField(DSL.name("custcolumn48"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn49</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN49 = createField(DSL.name("custcolumn49"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn50</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN50 = createField(DSL.name("custcolumn50"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.migration_reserved1</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> MIGRATION_RESERVED1 = createField(
			DSL.name("migration_reserved1"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>candidate_custom_fields_t.import_slug</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> IMPORT_SLUG = createField(DSL.name("import_slug"),
			SQLDataType.VARCHAR(90).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn51</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN51 = createField(DSL.name("custcolumn51"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn52</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN52 = createField(DSL.name("custcolumn52"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn53</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN53 = createField(DSL.name("custcolumn53"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn54</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN54 = createField(DSL.name("custcolumn54"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn55</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN55 = createField(DSL.name("custcolumn55"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn56</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN56 = createField(DSL.name("custcolumn56"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn57</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN57 = createField(DSL.name("custcolumn57"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn58</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN58 = createField(DSL.name("custcolumn58"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn59</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN59 = createField(DSL.name("custcolumn59"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn60</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN60 = createField(DSL.name("custcolumn60"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn61</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN61 = createField(DSL.name("custcolumn61"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn62</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN62 = createField(DSL.name("custcolumn62"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn63</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN63 = createField(DSL.name("custcolumn63"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn64</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN64 = createField(DSL.name("custcolumn64"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn65</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN65 = createField(DSL.name("custcolumn65"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn66</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN66 = createField(DSL.name("custcolumn66"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn67</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN67 = createField(DSL.name("custcolumn67"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn68</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN68 = createField(DSL.name("custcolumn68"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn69</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN69 = createField(DSL.name("custcolumn69"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn70</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN70 = createField(DSL.name("custcolumn70"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn71</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN71 = createField(DSL.name("custcolumn71"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn72</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN72 = createField(DSL.name("custcolumn72"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn73</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN73 = createField(DSL.name("custcolumn73"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn74</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN74 = createField(DSL.name("custcolumn74"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn75</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN75 = createField(DSL.name("custcolumn75"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn76</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN76 = createField(DSL.name("custcolumn76"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn77</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN77 = createField(DSL.name("custcolumn77"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn78</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN78 = createField(DSL.name("custcolumn78"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn79</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN79 = createField(DSL.name("custcolumn79"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn80</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN80 = createField(DSL.name("custcolumn80"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn81</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN81 = createField(DSL.name("custcolumn81"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn82</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN82 = createField(DSL.name("custcolumn82"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn83</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN83 = createField(DSL.name("custcolumn83"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn84</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN84 = createField(DSL.name("custcolumn84"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn85</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN85 = createField(DSL.name("custcolumn85"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn86</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN86 = createField(DSL.name("custcolumn86"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn87</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN87 = createField(DSL.name("custcolumn87"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn88</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN88 = createField(DSL.name("custcolumn88"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn89</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN89 = createField(DSL.name("custcolumn89"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn90</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN90 = createField(DSL.name("custcolumn90"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn91</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN91 = createField(DSL.name("custcolumn91"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn92</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN92 = createField(DSL.name("custcolumn92"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn93</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN93 = createField(DSL.name("custcolumn93"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn94</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN94 = createField(DSL.name("custcolumn94"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn95</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN95 = createField(DSL.name("custcolumn95"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn96</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN96 = createField(DSL.name("custcolumn96"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn97</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN97 = createField(DSL.name("custcolumn97"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn98</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN98 = createField(DSL.name("custcolumn98"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn99</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN99 = createField(DSL.name("custcolumn99"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn100</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN100 = createField(DSL.name("custcolumn100"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn101</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN101 = createField(DSL.name("custcolumn101"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn102</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN102 = createField(DSL.name("custcolumn102"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn103</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN103 = createField(DSL.name("custcolumn103"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn104</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN104 = createField(DSL.name("custcolumn104"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn105</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN105 = createField(DSL.name("custcolumn105"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn106</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN106 = createField(DSL.name("custcolumn106"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn107</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN107 = createField(DSL.name("custcolumn107"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn108</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN108 = createField(DSL.name("custcolumn108"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn109</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN109 = createField(DSL.name("custcolumn109"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn110</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN110 = createField(DSL.name("custcolumn110"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn111</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN111 = createField(DSL.name("custcolumn111"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn112</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN112 = createField(DSL.name("custcolumn112"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn113</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN113 = createField(DSL.name("custcolumn113"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn114</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN114 = createField(DSL.name("custcolumn114"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn115</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN115 = createField(DSL.name("custcolumn115"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn116</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN116 = createField(DSL.name("custcolumn116"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn117</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN117 = createField(DSL.name("custcolumn117"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn118</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN118 = createField(DSL.name("custcolumn118"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn119</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN119 = createField(DSL.name("custcolumn119"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn120</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN120 = createField(DSL.name("custcolumn120"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn121</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN121 = createField(DSL.name("custcolumn121"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn122</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN122 = createField(DSL.name("custcolumn122"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn123</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN123 = createField(DSL.name("custcolumn123"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn124</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN124 = createField(DSL.name("custcolumn124"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn125</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN125 = createField(DSL.name("custcolumn125"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn126</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN126 = createField(DSL.name("custcolumn126"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn127</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN127 = createField(DSL.name("custcolumn127"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn128</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN128 = createField(DSL.name("custcolumn128"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn129</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN129 = createField(DSL.name("custcolumn129"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn130</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN130 = createField(DSL.name("custcolumn130"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn131</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN131 = createField(DSL.name("custcolumn131"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn132</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN132 = createField(DSL.name("custcolumn132"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn133</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN133 = createField(DSL.name("custcolumn133"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn134</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN134 = createField(DSL.name("custcolumn134"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn135</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN135 = createField(DSL.name("custcolumn135"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn136</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN136 = createField(DSL.name("custcolumn136"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn137</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN137 = createField(DSL.name("custcolumn137"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn138</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN138 = createField(DSL.name("custcolumn138"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn139</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN139 = createField(DSL.name("custcolumn139"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn140</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN140 = createField(DSL.name("custcolumn140"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn141</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN141 = createField(DSL.name("custcolumn141"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn142</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN142 = createField(DSL.name("custcolumn142"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn143</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN143 = createField(DSL.name("custcolumn143"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn144</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN144 = createField(DSL.name("custcolumn144"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn145</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN145 = createField(DSL.name("custcolumn145"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn146</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN146 = createField(DSL.name("custcolumn146"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn147</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN147 = createField(DSL.name("custcolumn147"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn148</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN148 = createField(DSL.name("custcolumn148"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn149</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN149 = createField(DSL.name("custcolumn149"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.custcolumn150</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, String> CUSTCOLUMN150 = createField(DSL.name("custcolumn150"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>candidate_custom_fields_t.accountid</code>.
	 */
	public final TableField<CandidateCustomFieldsTRecord, Integer> ACCOUNTID = createField(DSL.name("accountid"),
			SQLDataType.INTEGER, this, "");

	private CandidateCustomFieldsT(Name alias, Table<CandidateCustomFieldsTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private CandidateCustomFieldsT(Name alias, Table<CandidateCustomFieldsTRecord> aliased, Field<?>[] parameters,
			Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>candidate_custom_fields_t</code> table reference
	 */
	public CandidateCustomFieldsT(String alias) {
		this(DSL.name(alias), CANDIDATE_CUSTOM_FIELDS_T);
	}

	/**
	 * Create an aliased <code>candidate_custom_fields_t</code> table reference
	 */
	public CandidateCustomFieldsT(Name alias) {
		this(alias, CANDIDATE_CUSTOM_FIELDS_T);
	}

	/**
	 * Create a <code>candidate_custom_fields_t</code> table reference
	 */
	public CandidateCustomFieldsT() {
		this(DSL.name("candidate_custom_fields_t"), null);
	}

	public <O extends Record> CandidateCustomFieldsT(Table<O> path,
			ForeignKey<O, CandidateCustomFieldsTRecord> childPath,
			InverseForeignKey<O, CandidateCustomFieldsTRecord> parentPath) {
		super(path, childPath, parentPath, CANDIDATE_CUSTOM_FIELDS_T);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class CandidateCustomFieldsTPath extends CandidateCustomFieldsT
			implements Path<CandidateCustomFieldsTRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> CandidateCustomFieldsTPath(Table<O> path,
				ForeignKey<O, CandidateCustomFieldsTRecord> childPath,
				InverseForeignKey<O, CandidateCustomFieldsTRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private CandidateCustomFieldsTPath(Name alias, Table<CandidateCustomFieldsTRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public CandidateCustomFieldsTPath as(String alias) {
			return new CandidateCustomFieldsTPath(DSL.name(alias), this);
		}

		@Override
		public CandidateCustomFieldsTPath as(Name alias) {
			return new CandidateCustomFieldsTPath(alias, this);
		}

		@Override
		public CandidateCustomFieldsTPath as(Table<?> alias) {
			return new CandidateCustomFieldsTPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.CANDIDATE_CUSTOM_FIELDS_T_ACCOUNTID,
				Indexes.CANDIDATE_CUSTOM_FIELDS_T_FK_CUSTOM_FIELD_T_TBLCANDIDATE_IDX);
	}

	@Override
	public Identity<CandidateCustomFieldsTRecord, Integer> getIdentity() {
		return (Identity<CandidateCustomFieldsTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<CandidateCustomFieldsTRecord> getPrimaryKey() {
		return Keys.KEY_CANDIDATE_CUSTOM_FIELDS_T_PRIMARY;
	}

	@Override
	public List<UniqueKey<CandidateCustomFieldsTRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_CANDIDATE_CUSTOM_FIELDS_T_UNIQUE_CANDIDATEID_SLUG);
	}

	@Override
	public List<ForeignKey<CandidateCustomFieldsTRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_CUSTOM_FIELD_T_TBLCANDIDATE);
	}

	private transient TblcandidatePath _tblcandidate;

	/**
	 * Get the implicit join path to the <code>tblcandidate</code> table.
	 */
	public TblcandidatePath tblcandidate() {
		if (_tblcandidate == null)
			_tblcandidate = new TblcandidatePath(this, Keys.FK_CUSTOM_FIELD_T_TBLCANDIDATE, null);

		return _tblcandidate;
	}

	@Override
	public CandidateCustomFieldsT as(String alias) {
		return new CandidateCustomFieldsT(DSL.name(alias), this);
	}

	@Override
	public CandidateCustomFieldsT as(Name alias) {
		return new CandidateCustomFieldsT(alias, this);
	}

	@Override
	public CandidateCustomFieldsT as(Table<?> alias) {
		return new CandidateCustomFieldsT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CandidateCustomFieldsT rename(String name) {
		return new CandidateCustomFieldsT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CandidateCustomFieldsT rename(Name name) {
		return new CandidateCustomFieldsT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CandidateCustomFieldsT rename(Table<?> name) {
		return new CandidateCustomFieldsT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateCustomFieldsT where(Condition condition) {
		return new CandidateCustomFieldsT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateCustomFieldsT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateCustomFieldsT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateCustomFieldsT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CandidateCustomFieldsT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CandidateCustomFieldsT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CandidateCustomFieldsT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CandidateCustomFieldsT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateCustomFieldsT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CandidateCustomFieldsT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
