/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.records.ClientPortalStatusTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

/**
 * Client portal lifecycle per HMP user within an RCRM account.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientPortalStatusT extends TableImpl<ClientPortalStatusTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>client_portal_status_t</code>
	 */
	public static final ClientPortalStatusT CLIENT_PORTAL_STATUS_T = new ClientPortalStatusT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ClientPortalStatusTRecord> getRecordType() {
		return ClientPortalStatusTRecord.class;
	}

	/**
	 * The column <code>client_portal_status_t.id</code>. Unique record ID
	 */
	public final TableField<ClientPortalStatusTRecord, UInteger> ID = createField(DSL.name("id"),
			SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "Unique record ID");

	/**
	 * The column <code>client_portal_status_t.portal_status_id</code>. Portal status:
	 * 0=not_sent 1=invitation_sent 2=portal_enabled 3=portal_disabled
	 */
	public final TableField<ClientPortalStatusTRecord, Byte> PORTAL_STATUS_ID = createField(
			DSL.name("portal_status_id"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Portal status: 0=not_sent 1=invitation_sent 2=portal_enabled 3=portal_disabled");

	/**
	 * The column <code>client_portal_status_t.account_id</code>. RCRM tenant account ID
	 */
	public final TableField<ClientPortalStatusTRecord, UInteger> ACCOUNT_ID = createField(DSL.name("account_id"),
			SQLDataType.INTEGERUNSIGNED.nullable(false), this, "RCRM tenant account ID");

	/**
	 * The column <code>client_portal_status_t.company_id</code>. RCRM company ID from
	 * which the contact was invited; references tblcompany.id
	 */
	public final TableField<ClientPortalStatusTRecord, UInteger> COMPANY_ID = createField(DSL.name("company_id"),
			SQLDataType.INTEGERUNSIGNED, this,
			"RCRM company ID from which the contact was invited; references tblcompany.id");

	/**
	 * The column <code>client_portal_status_t.invite_count</code>. Number of invite
	 * emails sent; enforces 3/day rate limit
	 */
	public final TableField<ClientPortalStatusTRecord, UInteger> INVITE_COUNT = createField(DSL.name("invite_count"),
			SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)),
			this, "Number of invite emails sent; enforces 3/day rate limit");

	/**
	 * The column <code>client_portal_status_t.vms_user_id</code>. vms-auth user ID;
	 * populated at invite dispatch when vms-auth creates the invite token
	 */
	public final TableField<ClientPortalStatusTRecord, UInteger> VMS_USER_ID = createField(DSL.name("vms_user_id"),
			SQLDataType.INTEGERUNSIGNED, this,
			"vms-auth user ID; populated at invite dispatch when vms-auth creates the invite token");

	/**
	 * The column <code>client_portal_status_t.vms_user_email</code>. contact email
	 * address; populated at invite dispatch
	 */
	public final TableField<ClientPortalStatusTRecord, String> VMS_USER_EMAIL = createField(DSL.name("vms_user_email"),
			SQLDataType.VARCHAR(254), this, "contact email address; populated at invite dispatch");

	/**
	 * The column <code>client_portal_status_t.invite_sent_by_user_id</code>. RCRM user ID
	 * who sent the invite; 0 when invite was sent via HMP portal peer-invite flow
	 */
	public final TableField<ClientPortalStatusTRecord, UInteger> INVITE_SENT_BY_USER_ID = createField(
			DSL.name("invite_sent_by_user_id"),
			SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)),
			this, "RCRM user ID who sent the invite; 0 when invite was sent via HMP portal peer-invite flow");

	/**
	 * The column <code>client_portal_status_t.invite_sent_on</code>. Unix epoch of most
	 * recent invite email dispatch
	 */
	public final TableField<ClientPortalStatusTRecord, UInteger> INVITE_SENT_ON = createField(
			DSL.name("invite_sent_on"),
			SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)),
			this, "Unix epoch of most recent invite email dispatch");

	/**
	 * The column <code>client_portal_status_t.updated_on</code>. Unix epoch of last
	 * record modification
	 */
	public final TableField<ClientPortalStatusTRecord, UInteger> UPDATED_ON = createField(DSL.name("updated_on"),
			SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)),
			this, "Unix epoch of last record modification");

	private ClientPortalStatusT(Name alias, Table<ClientPortalStatusTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private ClientPortalStatusT(Name alias, Table<ClientPortalStatusTRecord> aliased, Field<?>[] parameters,
			Condition where) {
		super(alias, null, aliased, parameters,
				DSL.comment("Client portal lifecycle per HMP user within an RCRM account."), TableOptions.table(),
				where);
	}

	/**
	 * Create an aliased <code>client_portal_status_t</code> table reference
	 */
	public ClientPortalStatusT(String alias) {
		this(DSL.name(alias), CLIENT_PORTAL_STATUS_T);
	}

	/**
	 * Create an aliased <code>client_portal_status_t</code> table reference
	 */
	public ClientPortalStatusT(Name alias) {
		this(alias, CLIENT_PORTAL_STATUS_T);
	}

	/**
	 * Create a <code>client_portal_status_t</code> table reference
	 */
	public ClientPortalStatusT() {
		this(DSL.name("client_portal_status_t"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<ClientPortalStatusTRecord, UInteger> getIdentity() {
		return (Identity<ClientPortalStatusTRecord, UInteger>) super.getIdentity();
	}

	@Override
	public UniqueKey<ClientPortalStatusTRecord> getPrimaryKey() {
		return Keys.KEY_CLIENT_PORTAL_STATUS_T_PRIMARY;
	}

	@Override
	public List<UniqueKey<ClientPortalStatusTRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_CLIENT_PORTAL_STATUS_T_UQ_VMS_USER_ACCOUNT);
	}

	@Override
	public ClientPortalStatusT as(String alias) {
		return new ClientPortalStatusT(DSL.name(alias), this);
	}

	@Override
	public ClientPortalStatusT as(Name alias) {
		return new ClientPortalStatusT(alias, this);
	}

	@Override
	public ClientPortalStatusT as(Table<?> alias) {
		return new ClientPortalStatusT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ClientPortalStatusT rename(String name) {
		return new ClientPortalStatusT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ClientPortalStatusT rename(Name name) {
		return new ClientPortalStatusT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ClientPortalStatusT rename(Table<?> name) {
		return new ClientPortalStatusT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ClientPortalStatusT where(Condition condition) {
		return new ClientPortalStatusT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ClientPortalStatusT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ClientPortalStatusT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ClientPortalStatusT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ClientPortalStatusT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ClientPortalStatusT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ClientPortalStatusT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ClientPortalStatusT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ClientPortalStatusT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ClientPortalStatusT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
