/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.records.ContractorPortalStatusTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

/**
 * Stores contractor portal status and email send tracking details
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContractorPortalStatusT extends TableImpl<ContractorPortalStatusTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>contractor_portal_status_t</code>
	 */
	public static final ContractorPortalStatusT CONTRACTOR_PORTAL_STATUS_T = new ContractorPortalStatusT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ContractorPortalStatusTRecord> getRecordType() {
		return ContractorPortalStatusTRecord.class;
	}

	/**
	 * The column <code>contractor_portal_status_t.id</code>. Primary key
	 */
	public final TableField<ContractorPortalStatusTRecord, UInteger> ID = createField(DSL.name("id"),
			SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "Primary key");

	/**
	 * The column <code>contractor_portal_status_t.contractor_id</code>. Same as Candidate
	 * ID
	 */
	public final TableField<ContractorPortalStatusTRecord, UInteger> CONTRACTOR_ID = createField(
			DSL.name("contractor_id"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "Same as Candidate ID");

	/**
	 * The column <code>contractor_portal_status_t.status_id</code>. Portal status:
	 * 0=Invitation not sent, 1=Invitation sent, 2=Portal enabled, 3=Portal disabled
	 */
	public final TableField<ContractorPortalStatusTRecord, Byte> STATUS_ID = createField(DSL.name("status_id"),
			SQLDataType.TINYINT.nullable(false), this,
			"Portal status: 0=Invitation not sent, 1=Invitation sent, 2=Portal enabled, 3=Portal disabled");

	/**
	 * The column <code>contractor_portal_status_t.invite_count</code>. Number of invites
	 * sent to the contractor
	 */
	public final TableField<ContractorPortalStatusTRecord, UInteger> INVITE_COUNT = createField(
			DSL.name("invite_count"),
			SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)),
			this, "Number of invites sent to the contractor");

	/**
	 * The column <code>contractor_portal_status_t.last_invite_sent_on</code>. Epoch
	 * timestamp when the last invite email was sent
	 */
	public final TableField<ContractorPortalStatusTRecord, UInteger> LAST_INVITE_SENT_ON = createField(
			DSL.name("last_invite_sent_on"), SQLDataType.INTEGERUNSIGNED, this,
			"Epoch timestamp when the last invite email was sent");

	/**
	 * The column <code>contractor_portal_status_t.updated_by</code>. User ID who last
	 * updated the record
	 */
	public final TableField<ContractorPortalStatusTRecord, UInteger> UPDATED_BY = createField(DSL.name("updated_by"),
			SQLDataType.INTEGERUNSIGNED.nullable(false), this, "User ID who last updated the record");

	/**
	 * The column <code>contractor_portal_status_t.updated_on</code>. Epoch timestamp when
	 * the record was last updated
	 */
	public final TableField<ContractorPortalStatusTRecord, UInteger> UPDATED_ON = createField(DSL.name("updated_on"),
			SQLDataType.INTEGERUNSIGNED.nullable(false), this, "Epoch timestamp when the record was last updated");

	/**
	 * The column <code>contractor_portal_status_t.account_id</code>. Account ID related
	 * to contractor
	 */
	public final TableField<ContractorPortalStatusTRecord, UInteger> ACCOUNT_ID = createField(DSL.name("account_id"),
			SQLDataType.INTEGERUNSIGNED.nullable(false), this, "Account ID related to contractor");

	private ContractorPortalStatusT(Name alias, Table<ContractorPortalStatusTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private ContractorPortalStatusT(Name alias, Table<ContractorPortalStatusTRecord> aliased, Field<?>[] parameters,
			Condition where) {
		super(alias, null, aliased, parameters,
				DSL.comment("Stores contractor portal status and email send tracking details"), TableOptions.table(),
				where);
	}

	/**
	 * Create an aliased <code>contractor_portal_status_t</code> table reference
	 */
	public ContractorPortalStatusT(String alias) {
		this(DSL.name(alias), CONTRACTOR_PORTAL_STATUS_T);
	}

	/**
	 * Create an aliased <code>contractor_portal_status_t</code> table reference
	 */
	public ContractorPortalStatusT(Name alias) {
		this(alias, CONTRACTOR_PORTAL_STATUS_T);
	}

	/**
	 * Create a <code>contractor_portal_status_t</code> table reference
	 */
	public ContractorPortalStatusT() {
		this(DSL.name("contractor_portal_status_t"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<ContractorPortalStatusTRecord, UInteger> getIdentity() {
		return (Identity<ContractorPortalStatusTRecord, UInteger>) super.getIdentity();
	}

	@Override
	public UniqueKey<ContractorPortalStatusTRecord> getPrimaryKey() {
		return Keys.KEY_CONTRACTOR_PORTAL_STATUS_T_PRIMARY;
	}

	@Override
	public List<UniqueKey<ContractorPortalStatusTRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_CONTRACTOR_PORTAL_STATUS_T_CONTRACTOR_ID);
	}

	@Override
	public ContractorPortalStatusT as(String alias) {
		return new ContractorPortalStatusT(DSL.name(alias), this);
	}

	@Override
	public ContractorPortalStatusT as(Name alias) {
		return new ContractorPortalStatusT(alias, this);
	}

	@Override
	public ContractorPortalStatusT as(Table<?> alias) {
		return new ContractorPortalStatusT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ContractorPortalStatusT rename(String name) {
		return new ContractorPortalStatusT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ContractorPortalStatusT rename(Name name) {
		return new ContractorPortalStatusT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ContractorPortalStatusT rename(Table<?> name) {
		return new ContractorPortalStatusT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContractorPortalStatusT where(Condition condition) {
		return new ContractorPortalStatusT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContractorPortalStatusT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContractorPortalStatusT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContractorPortalStatusT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ContractorPortalStatusT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ContractorPortalStatusT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ContractorPortalStatusT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ContractorPortalStatusT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContractorPortalStatusT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContractorPortalStatusT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
