/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcompany.TblcompanyPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcontact.TblcontactPath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.ContactCompanyTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContactCompanyT extends TableImpl<ContactCompanyTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>contact_company_t</code>
	 */
	public static final ContactCompanyT CONTACT_COMPANY_T = new ContactCompanyT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ContactCompanyTRecord> getRecordType() {
		return ContactCompanyTRecord.class;
	}

	/**
	 * The column <code>contact_company_t.id</code>.
	 */
	public final TableField<ContactCompanyTRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>contact_company_t.contact_id</code>. This contact id reference of
	 * tblcontact table
	 */
	public final TableField<ContactCompanyTRecord, Integer> CONTACT_ID = createField(DSL.name("contact_id"),
			SQLDataType.INTEGER, this, "This contact id reference of tblcontact table");

	/**
	 * The column <code>contact_company_t.company_id</code>. This company id reference of
	 * tblcompany table
	 */
	public final TableField<ContactCompanyTRecord, Integer> COMPANY_ID = createField(DSL.name("company_id"),
			SQLDataType.INTEGER, this, "This company id reference of tblcompany table");

	private ContactCompanyT(Name alias, Table<ContactCompanyTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private ContactCompanyT(Name alias, Table<ContactCompanyTRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>contact_company_t</code> table reference
	 */
	public ContactCompanyT(String alias) {
		this(DSL.name(alias), CONTACT_COMPANY_T);
	}

	/**
	 * Create an aliased <code>contact_company_t</code> table reference
	 */
	public ContactCompanyT(Name alias) {
		this(alias, CONTACT_COMPANY_T);
	}

	/**
	 * Create a <code>contact_company_t</code> table reference
	 */
	public ContactCompanyT() {
		this(DSL.name("contact_company_t"), null);
	}

	public <O extends Record> ContactCompanyT(Table<O> path, ForeignKey<O, ContactCompanyTRecord> childPath,
			InverseForeignKey<O, ContactCompanyTRecord> parentPath) {
		super(path, childPath, parentPath, CONTACT_COMPANY_T);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class ContactCompanyTPath extends ContactCompanyT implements Path<ContactCompanyTRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> ContactCompanyTPath(Table<O> path, ForeignKey<O, ContactCompanyTRecord> childPath,
				InverseForeignKey<O, ContactCompanyTRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private ContactCompanyTPath(Name alias, Table<ContactCompanyTRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public ContactCompanyTPath as(String alias) {
			return new ContactCompanyTPath(DSL.name(alias), this);
		}

		@Override
		public ContactCompanyTPath as(Name alias) {
			return new ContactCompanyTPath(alias, this);
		}

		@Override
		public ContactCompanyTPath as(Table<?> alias) {
			return new ContactCompanyTPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.CONTACT_COMPANY_T_COMPANY_ID_IDX, Indexes.CONTACT_COMPANY_T_CONTACT_ID_IDX);
	}

	@Override
	public Identity<ContactCompanyTRecord, Integer> getIdentity() {
		return (Identity<ContactCompanyTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<ContactCompanyTRecord> getPrimaryKey() {
		return Keys.KEY_CONTACT_COMPANY_T_PRIMARY;
	}

	@Override
	public List<UniqueKey<ContactCompanyTRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_CONTACT_COMPANY_T_CONTACT_COMPANY_UNIQUE_IDX);
	}

	@Override
	public List<ForeignKey<ContactCompanyTRecord, ?>> getReferences() {
		return Arrays.asList(Keys.CONTACT_COMPANY_T_IBFK_1, Keys.CONTACT_COMPANY_T_IBFK_2);
	}

	private transient TblcontactPath _tblcontact;

	/**
	 * Get the implicit join path to the <code>tblcontact</code> table.
	 */
	public TblcontactPath tblcontact() {
		if (_tblcontact == null)
			_tblcontact = new TblcontactPath(this, Keys.CONTACT_COMPANY_T_IBFK_1, null);

		return _tblcontact;
	}

	private transient TblcompanyPath _tblcompany;

	/**
	 * Get the implicit join path to the <code>tblcompany</code> table.
	 */
	public TblcompanyPath tblcompany() {
		if (_tblcompany == null)
			_tblcompany = new TblcompanyPath(this, Keys.CONTACT_COMPANY_T_IBFK_2, null);

		return _tblcompany;
	}

	@Override
	public ContactCompanyT as(String alias) {
		return new ContactCompanyT(DSL.name(alias), this);
	}

	@Override
	public ContactCompanyT as(Name alias) {
		return new ContactCompanyT(alias, this);
	}

	@Override
	public ContactCompanyT as(Table<?> alias) {
		return new ContactCompanyT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ContactCompanyT rename(String name) {
		return new ContactCompanyT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ContactCompanyT rename(Name name) {
		return new ContactCompanyT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ContactCompanyT rename(Table<?> name) {
		return new ContactCompanyT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContactCompanyT where(Condition condition) {
		return new ContactCompanyT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContactCompanyT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContactCompanyT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContactCompanyT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ContactCompanyT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ContactCompanyT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ContactCompanyT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ContactCompanyT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContactCompanyT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ContactCompanyT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
