/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstRuleTemplateTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * Denormalized table to store rule templates and their associated configurations in JSON
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstRuleTemplateT extends TableImpl<CstRuleTemplateTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>cst_rule_template_t</code>
	 */
	public static final CstRuleTemplateT CST_RULE_TEMPLATE_T = new CstRuleTemplateT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CstRuleTemplateTRecord> getRecordType() {
		return CstRuleTemplateTRecord.class;
	}

	/**
	 * The column <code>cst_rule_template_t.id</code>. Primary key for the rule template
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary key for the rule template");

	/**
	 * The column <code>cst_rule_template_t.template_name</code>. Name of the rule
	 * template
	 */
	public final TableField<CstRuleTemplateTRecord, String> TEMPLATE_NAME = createField(DSL.name("template_name"),
			SQLDataType.VARCHAR(250).nullable(false), this, "Name of the rule template");

	/**
	 * The column <code>cst_rule_template_t.work_log_type</code>. Type of work log
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> WORK_LOG_TYPE = createField(DSL.name("work_log_type"),
			SQLDataType.INTEGER.nullable(false), this, "Type of work log");

	/**
	 * The column <code>cst_rule_template_t.calculate_break_time</code>. Flag to indicate
	 * if break time is calculated
	 */
	public final TableField<CstRuleTemplateTRecord, Byte> CALCULATE_BREAK_TIME = createField(
			DSL.name("calculate_break_time"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Flag to indicate if break time is calculated");

	/**
	 * The column <code>cst_rule_template_t.account_id</code>. Foreign key referencing
	 * account
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"),
			SQLDataType.INTEGER.nullable(false), this, "Foreign key referencing account");

	/**
	 * The column <code>cst_rule_template_t.added_on</code>. Timestamp when record was
	 * added
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> ADDED_ON = createField(DSL.name("added_on"),
			SQLDataType.INTEGER.nullable(false), this, "Timestamp when record was added");

	/**
	 * The column <code>cst_rule_template_t.added_by</code>. User ID who added the record
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> ADDED_BY = createField(DSL.name("added_by"),
			SQLDataType.INTEGER.nullable(false), this, "User ID who added the record");

	/**
	 * The column <code>cst_rule_template_t.added_by_user_type_id</code>. User type ID who
	 * added the record
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> ADDED_BY_USER_TYPE_ID = createField(
			DSL.name("added_by_user_type_id"), SQLDataType.INTEGER.nullable(false), this,
			"User type ID who added the record");

	/**
	 * The column <code>cst_rule_template_t.updated_on</code>. Timestamp when record was
	 * last updated
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> UPDATED_ON = createField(DSL.name("updated_on"),
			SQLDataType.INTEGER, this, "Timestamp when record was last updated");

	/**
	 * The column <code>cst_rule_template_t.updated_by</code>. User ID who last updated
	 * the record
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> UPDATED_BY = createField(DSL.name("updated_by"),
			SQLDataType.INTEGER, this, "User ID who last updated the record");

	/**
	 * The column <code>cst_rule_template_t.updated_by_user_type_id</code>. User type ID
	 * who last updated the record
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> UPDATED_BY_USER_TYPE_ID = createField(
			DSL.name("updated_by_user_type_id"), SQLDataType.INTEGER, this, "User type ID who last updated the record");

	/**
	 * The column <code>cst_rule_template_t.template_work_day</code>. List of work day
	 * settings for this template
	 */
	public final TableField<CstRuleTemplateTRecord, JSON> TEMPLATE_WORK_DAY = createField(DSL.name("template_work_day"),
			SQLDataType.JSON, this, "List of work day settings for this template");

	/**
	 * The column <code>cst_rule_template_t.custom_rule</code>. List of custom rules
	 * associated with the template including their work days
	 */
	public final TableField<CstRuleTemplateTRecord, JSON> CUSTOM_RULE = createField(DSL.name("custom_rule"),
			SQLDataType.JSON, this, "List of custom rules associated with the template including their work days");

	/**
	 * The column <code>cst_rule_template_t.break_time_threshold</code>. Break time
	 * threshold in second
	 */
	public final TableField<CstRuleTemplateTRecord, Integer> BREAK_TIME_THRESHOLD = createField(
			DSL.name("break_time_threshold"), SQLDataType.INTEGER, this, "Break time threshold in second");

	/**
	 * The column <code>cst_rule_template_t.is_default</code>. Flag to set template as
	 * default
	 */
	public final TableField<CstRuleTemplateTRecord, Byte> IS_DEFAULT = createField(DSL.name("is_default"),
			SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Flag to set template as default");

	/**
	 * The column <code>cst_rule_template_t.is_unplanned_hour_pay_enabled</code>. 0 =
	 * disabled (default): unplanned hours follow existing behaviour. 1 = enabled: hours
	 * outside schedule and not covered by any overtime rule are paid/billed at minimum 1x
	 * rate.
	 */
	public final TableField<CstRuleTemplateTRecord, Byte> IS_UNPLANNED_HOUR_PAY_ENABLED = createField(
			DSL.name("is_unplanned_hour_pay_enabled"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"0 = disabled (default): unplanned hours follow existing behaviour. 1 = enabled: hours outside schedule and not covered by any overtime rule are paid/billed at minimum 1x rate.");

	private CstRuleTemplateT(Name alias, Table<CstRuleTemplateTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private CstRuleTemplateT(Name alias, Table<CstRuleTemplateTRecord> aliased, Field<?>[] parameters,
			Condition where) {
		super(alias, null, aliased, parameters,
				DSL.comment("Denormalized table to store rule templates and their associated configurations in JSON"),
				TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>cst_rule_template_t</code> table reference
	 */
	public CstRuleTemplateT(String alias) {
		this(DSL.name(alias), CST_RULE_TEMPLATE_T);
	}

	/**
	 * Create an aliased <code>cst_rule_template_t</code> table reference
	 */
	public CstRuleTemplateT(Name alias) {
		this(alias, CST_RULE_TEMPLATE_T);
	}

	/**
	 * Create a <code>cst_rule_template_t</code> table reference
	 */
	public CstRuleTemplateT() {
		this(DSL.name("cst_rule_template_t"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<CstRuleTemplateTRecord, Integer> getIdentity() {
		return (Identity<CstRuleTemplateTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<CstRuleTemplateTRecord> getPrimaryKey() {
		return Keys.KEY_CST_RULE_TEMPLATE_T_PRIMARY;
	}

	@Override
	public List<UniqueKey<CstRuleTemplateTRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_CST_RULE_TEMPLATE_T_UK_RULE_TEMPLATE_NAME);
	}

	@Override
	public CstRuleTemplateT as(String alias) {
		return new CstRuleTemplateT(DSL.name(alias), this);
	}

	@Override
	public CstRuleTemplateT as(Name alias) {
		return new CstRuleTemplateT(alias, this);
	}

	@Override
	public CstRuleTemplateT as(Table<?> alias) {
		return new CstRuleTemplateT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstRuleTemplateT rename(String name) {
		return new CstRuleTemplateT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstRuleTemplateT rename(Name name) {
		return new CstRuleTemplateT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstRuleTemplateT rename(Table<?> name) {
		return new CstRuleTemplateT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstRuleTemplateT where(Condition condition) {
		return new CstRuleTemplateT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstRuleTemplateT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstRuleTemplateT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstRuleTemplateT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstRuleTemplateT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstRuleTemplateT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstRuleTemplateT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstRuleTemplateT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstRuleTemplateT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstRuleTemplateT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
