/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimeLogT.CstTimeLogTPath;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetApprovalT.CstTimesheetApprovalTPath;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetSettingT.CstTimesheetSettingTPath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetTRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * Table to store timesheet records including payment and billing data
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstTimesheetT extends TableImpl<CstTimesheetTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>cst_timesheet_t</code>
	 */
	public static final CstTimesheetT CST_TIMESHEET_T = new CstTimesheetT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CstTimesheetTRecord> getRecordType() {
		return CstTimesheetTRecord.class;
	}

	/**
	 * The column <code>cst_timesheet_t.id</code>. Primary key for the timesheet record
	 */
	public final TableField<CstTimesheetTRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary key for the timesheet record");

	/**
	 * The column <code>cst_timesheet_t.period_start</code>. Start date and time of the
	 * timesheet period
	 */
	public final TableField<CstTimesheetTRecord, Integer> PERIOD_START = createField(DSL.name("period_start"),
			SQLDataType.INTEGER.nullable(false), this, "Start date and time of the timesheet period");

	/**
	 * The column <code>cst_timesheet_t.period_end</code>. End date and time of the
	 * timesheet period
	 */
	public final TableField<CstTimesheetTRecord, Integer> PERIOD_END = createField(DSL.name("period_end"),
			SQLDataType.INTEGER.nullable(false), this, "End date and time of the timesheet period");

	/**
	 * The column <code>cst_timesheet_t.pay_data</code>. Payment data with up to 2 decimal
	 * places
	 */
	public final TableField<CstTimesheetTRecord, BigDecimal> PAY_DATA = createField(DSL.name("pay_data"),
			SQLDataType.DECIMAL(10, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this,
			"Payment data with up to 2 decimal places");

	/**
	 * The column <code>cst_timesheet_t.bill_data</code>. Billing data with up to 2
	 * decimal places
	 */
	public final TableField<CstTimesheetTRecord, BigDecimal> BILL_DATA = createField(DSL.name("bill_data"),
			SQLDataType.DECIMAL(10, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this,
			"Billing data with up to 2 decimal places");

	/**
	 * The column <code>cst_timesheet_t.added_on</code>. Timestamp when the record was
	 * added
	 */
	public final TableField<CstTimesheetTRecord, Integer> ADDED_ON = createField(DSL.name("added_on"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Timestamp when the record was added");

	/**
	 * The column <code>cst_timesheet_t.added_by</code>. User ID who added the record
	 */
	public final TableField<CstTimesheetTRecord, Integer> ADDED_BY = createField(DSL.name("added_by"),
			SQLDataType.INTEGER.nullable(false), this, "User ID who added the record");

	/**
	 * The column <code>cst_timesheet_t.added_by_user_type_id</code>. User type ID who
	 * added the record, references cst_user_type_t PK
	 */
	public final TableField<CstTimesheetTRecord, Integer> ADDED_BY_USER_TYPE_ID = createField(
			DSL.name("added_by_user_type_id"), SQLDataType.INTEGER.nullable(false), this,
			"User type ID who added the record, references cst_user_type_t PK");

	/**
	 * The column <code>cst_timesheet_t.updated_on</code>. Timestamp when the record was
	 * last updated
	 */
	public final TableField<CstTimesheetTRecord, Integer> UPDATED_ON = createField(DSL.name("updated_on"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Timestamp when the record was last updated");

	/**
	 * The column <code>cst_timesheet_t.updated_by</code>. User ID who last updated the
	 * record
	 */
	public final TableField<CstTimesheetTRecord, Integer> UPDATED_BY = createField(DSL.name("updated_by"),
			SQLDataType.INTEGER.nullable(false), this, "User ID  who last updated the record");

	/**
	 * The column <code>cst_timesheet_t.updated_by_user_type_id</code>. User type ID who
	 * last updated the record, references cst_user_type_t PK
	 */
	public final TableField<CstTimesheetTRecord, Integer> UPDATED_BY_USER_TYPE_ID = createField(
			DSL.name("updated_by_user_type_id"), SQLDataType.INTEGER.nullable(false), this,
			"User type ID who last updated the record, references cst_user_type_t PK");

	/**
	 * The column <code>cst_timesheet_t.timesheet_setting_id</code>. Timesheet setting ID,
	 * references cst_timesheet_setting_t PK
	 */
	public final TableField<CstTimesheetTRecord, Integer> TIMESHEET_SETTING_ID = createField(
			DSL.name("timesheet_setting_id"), SQLDataType.INTEGER.nullable(false), this,
			"Timesheet setting ID, references cst_timesheet_setting_t PK");

	/**
	 * The column <code>cst_timesheet_t.timesheet_bill_status_id</code>. Timesheet billing
	 * status ID, references cst_timesheet_bill_status_type_t PK
	 */
	public final TableField<CstTimesheetTRecord, Integer> TIMESHEET_BILL_STATUS_ID = createField(
			DSL.name("timesheet_bill_status_id"), SQLDataType.INTEGER, this,
			"Timesheet billing status ID, references cst_timesheet_bill_status_type_t PK");

	/**
	 * The column <code>cst_timesheet_t.timesheet_pay_status_id</code>. Timesheet payment
	 * status ID, references timesheet_pay_status_t PK
	 */
	public final TableField<CstTimesheetTRecord, Integer> TIMESHEET_PAY_STATUS_ID = createField(
			DSL.name("timesheet_pay_status_id"), SQLDataType.INTEGER, this,
			"Timesheet payment status ID, references timesheet_pay_status_t PK");

	/**
	 * The column <code>cst_timesheet_t.account_id</code>. Account Id for the Timesheet
	 */
	public final TableField<CstTimesheetTRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"),
			SQLDataType.INTEGER.nullable(false), this, "Account Id for the Timesheet");

	/**
	 * The column <code>cst_timesheet_t.migration_reserved1</code>. column for migration
	 * data
	 */
	public final TableField<CstTimesheetTRecord, String> MIGRATION_RESERVED1 = createField(
			DSL.name("migration_reserved1"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this,
			"column for migration data");

	/**
	 * The column <code>cst_timesheet_t.migration_reserved2</code>. column for migration
	 * data
	 */
	public final TableField<CstTimesheetTRecord, String> MIGRATION_RESERVED2 = createField(
			DSL.name("migration_reserved2"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this,
			"column for migration data");

	/**
	 * The column <code>cst_timesheet_t.total_time</code>. Total time in seconds
	 */
	public final TableField<CstTimesheetTRecord, Integer> TOTAL_TIME = createField(DSL.name("total_time"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Total time in seconds");

	/**
	 * The column <code>cst_timesheet_t.total_work_time</code>. Total work time in seconds
	 */
	public final TableField<CstTimesheetTRecord, Integer> TOTAL_WORK_TIME = createField(DSL.name("total_work_time"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Total work time in seconds");

	/**
	 * The column <code>cst_timesheet_t.total_overtime</code>. Total overtime in seconds
	 */
	public final TableField<CstTimesheetTRecord, Integer> TOTAL_OVERTIME = createField(DSL.name("total_overtime"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Total overtime in seconds");

	/**
	 * The column <code>cst_timesheet_t.total_weekly_overtime</code>. Net weekly overtime
	 * duration in seconds (rule engine aggregate for the timesheet period)
	 */
	public final TableField<CstTimesheetTRecord, Integer> TOTAL_WEEKLY_OVERTIME = createField(
			DSL.name("total_weekly_overtime"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Net weekly overtime duration in seconds (rule engine aggregate for the timesheet period)");

	/**
	 * The column <code>cst_timesheet_t.total_regular_hour</code>. total regular time of
	 * timesheet
	 */
	public final TableField<CstTimesheetTRecord, Integer> TOTAL_REGULAR_HOUR = createField(
			DSL.name("total_regular_hour"), SQLDataType.INTEGER, this, "total regular time of timesheet");

	private CstTimesheetT(Name alias, Table<CstTimesheetTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private CstTimesheetT(Name alias, Table<CstTimesheetTRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters,
				DSL.comment("Table to store timesheet records including payment and billing data"),
				TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>cst_timesheet_t</code> table reference
	 */
	public CstTimesheetT(String alias) {
		this(DSL.name(alias), CST_TIMESHEET_T);
	}

	/**
	 * Create an aliased <code>cst_timesheet_t</code> table reference
	 */
	public CstTimesheetT(Name alias) {
		this(alias, CST_TIMESHEET_T);
	}

	/**
	 * Create a <code>cst_timesheet_t</code> table reference
	 */
	public CstTimesheetT() {
		this(DSL.name("cst_timesheet_t"), null);
	}

	public <O extends Record> CstTimesheetT(Table<O> path, ForeignKey<O, CstTimesheetTRecord> childPath,
			InverseForeignKey<O, CstTimesheetTRecord> parentPath) {
		super(path, childPath, parentPath, CST_TIMESHEET_T);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class CstTimesheetTPath extends CstTimesheetT implements Path<CstTimesheetTRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> CstTimesheetTPath(Table<O> path, ForeignKey<O, CstTimesheetTRecord> childPath,
				InverseForeignKey<O, CstTimesheetTRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private CstTimesheetTPath(Name alias, Table<CstTimesheetTRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public CstTimesheetTPath as(String alias) {
			return new CstTimesheetTPath(DSL.name(alias), this);
		}

		@Override
		public CstTimesheetTPath as(Name alias) {
			return new CstTimesheetTPath(alias, this);
		}

		@Override
		public CstTimesheetTPath as(Table<?> alias) {
			return new CstTimesheetTPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<CstTimesheetTRecord, Integer> getIdentity() {
		return (Identity<CstTimesheetTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<CstTimesheetTRecord> getPrimaryKey() {
		return Keys.KEY_CST_TIMESHEET_T_PRIMARY;
	}

	@Override
	public List<ForeignKey<CstTimesheetTRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_TIMESHEET_SETTING_TIMESHEET_T);
	}

	private transient CstTimesheetSettingTPath _cstTimesheetSettingT;

	/**
	 * Get the implicit join path to the <code>cst_timesheet_setting_t</code> table.
	 */
	public CstTimesheetSettingTPath cstTimesheetSettingT() {
		if (_cstTimesheetSettingT == null)
			_cstTimesheetSettingT = new CstTimesheetSettingTPath(this, Keys.FK_TIMESHEET_SETTING_TIMESHEET_T, null);

		return _cstTimesheetSettingT;
	}

	private transient CstTimeLogTPath _cstTimeLogT;

	/**
	 * Get the implicit to-many join path to the <code>cst_time_log_t</code> table
	 */
	public CstTimeLogTPath cstTimeLogT() {
		if (_cstTimeLogT == null)
			_cstTimeLogT = new CstTimeLogTPath(this, null, Keys.FK_TIME_LOG_TIMESHEET.getInverseKey());

		return _cstTimeLogT;
	}

	private transient CstTimesheetApprovalTPath _cstTimesheetApprovalT;

	/**
	 * Get the implicit to-many join path to the <code>cst_timesheet_approval_t</code>
	 * table
	 */
	public CstTimesheetApprovalTPath cstTimesheetApprovalT() {
		if (_cstTimesheetApprovalT == null)
			_cstTimesheetApprovalT = new CstTimesheetApprovalTPath(this, null,
					Keys.FK_TIMESHEET_APPROVAL_T_TIMESHEET.getInverseKey());

		return _cstTimesheetApprovalT;
	}

	@Override
	public CstTimesheetT as(String alias) {
		return new CstTimesheetT(DSL.name(alias), this);
	}

	@Override
	public CstTimesheetT as(Name alias) {
		return new CstTimesheetT(alias, this);
	}

	@Override
	public CstTimesheetT as(Table<?> alias) {
		return new CstTimesheetT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimesheetT rename(String name) {
		return new CstTimesheetT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimesheetT rename(Name name) {
		return new CstTimesheetT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimesheetT rename(Table<?> name) {
		return new CstTimesheetT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetT where(Condition condition) {
		return new CstTimesheetT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
