/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetT.CstTimesheetTPath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetApprovalTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * Table to store timesheet approval records
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstTimesheetApprovalT extends TableImpl<CstTimesheetApprovalTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>cst_timesheet_approval_t</code>
	 */
	public static final CstTimesheetApprovalT CST_TIMESHEET_APPROVAL_T = new CstTimesheetApprovalT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CstTimesheetApprovalTRecord> getRecordType() {
		return CstTimesheetApprovalTRecord.class;
	}

	/**
	 * The column <code>cst_timesheet_approval_t.id</code>. Primary key for the timesheet
	 * approval record
	 */
	public final TableField<CstTimesheetApprovalTRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary key for the timesheet approval record");

	/**
	 * The column <code>cst_timesheet_approval_t.timesheet_id</code>. Foreign key
	 * referencing cst_timesheet_t PK
	 */
	public final TableField<CstTimesheetApprovalTRecord, Integer> TIMESHEET_ID = createField(DSL.name("timesheet_id"),
			SQLDataType.INTEGER.nullable(false), this, "Foreign key referencing cst_timesheet_t PK");

	/**
	 * The column <code>cst_timesheet_approval_t.user_type_id</code>. Foreign key
	 * referencing cst_user_type_t PK
	 */
	public final TableField<CstTimesheetApprovalTRecord, Integer> USER_TYPE_ID = createField(DSL.name("user_type_id"),
			SQLDataType.INTEGER.nullable(false), this, "Foreign key referencing cst_user_type_t PK");

	/**
	 * The column <code>cst_timesheet_approval_t.entity_id</code>. Foreign key referencing
	 * the PK of either contractor_t or agency_contact_t (polymorphic field)
	 */
	public final TableField<CstTimesheetApprovalTRecord, Integer> ENTITY_ID = createField(DSL.name("entity_id"),
			SQLDataType.INTEGER.nullable(false), this,
			"Foreign key referencing the PK of either contractor_t or agency_contact_t (polymorphic field)");

	/**
	 * The column <code>cst_timesheet_approval_t.timesheet_approval_status_type_id</code>.
	 * Foreign key referencing cst_timesheet_approval_status_type_t PK
	 */
	public final TableField<CstTimesheetApprovalTRecord, Integer> TIMESHEET_APPROVAL_STATUS_TYPE_ID = createField(
			DSL.name("timesheet_approval_status_type_id"), SQLDataType.INTEGER.nullable(false), this,
			"Foreign key referencing cst_timesheet_approval_status_type_t PK");

	/**
	 * The column <code>cst_timesheet_approval_t.remark</code>. Additional remarks or
	 * notes for the approval
	 */
	public final TableField<CstTimesheetApprovalTRecord, String> REMARK = createField(DSL.name("remark"),
			SQLDataType.VARCHAR(1000), this, "Additional remarks or notes for the approval");

	/**
	 * The column <code>cst_timesheet_approval_t.created_on</code>. Timestamp when the
	 * record was last updated
	 */
	public final TableField<CstTimesheetApprovalTRecord, Integer> CREATED_ON = createField(DSL.name("created_on"),
			SQLDataType.INTEGER.nullable(false), this, "Timestamp when the record was last updated");

	/**
	 * The column <code>cst_timesheet_approval_t.migration_reserved1</code>. column for
	 * migration data
	 */
	public final TableField<CstTimesheetApprovalTRecord, String> MIGRATION_RESERVED1 = createField(
			DSL.name("migration_reserved1"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this,
			"column for migration data");

	private CstTimesheetApprovalT(Name alias, Table<CstTimesheetApprovalTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private CstTimesheetApprovalT(Name alias, Table<CstTimesheetApprovalTRecord> aliased, Field<?>[] parameters,
			Condition where) {
		super(alias, null, aliased, parameters, DSL.comment("Table to store timesheet approval records"),
				TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>cst_timesheet_approval_t</code> table reference
	 */
	public CstTimesheetApprovalT(String alias) {
		this(DSL.name(alias), CST_TIMESHEET_APPROVAL_T);
	}

	/**
	 * Create an aliased <code>cst_timesheet_approval_t</code> table reference
	 */
	public CstTimesheetApprovalT(Name alias) {
		this(alias, CST_TIMESHEET_APPROVAL_T);
	}

	/**
	 * Create a <code>cst_timesheet_approval_t</code> table reference
	 */
	public CstTimesheetApprovalT() {
		this(DSL.name("cst_timesheet_approval_t"), null);
	}

	public <O extends Record> CstTimesheetApprovalT(Table<O> path, ForeignKey<O, CstTimesheetApprovalTRecord> childPath,
			InverseForeignKey<O, CstTimesheetApprovalTRecord> parentPath) {
		super(path, childPath, parentPath, CST_TIMESHEET_APPROVAL_T);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class CstTimesheetApprovalTPath extends CstTimesheetApprovalT
			implements Path<CstTimesheetApprovalTRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> CstTimesheetApprovalTPath(Table<O> path,
				ForeignKey<O, CstTimesheetApprovalTRecord> childPath,
				InverseForeignKey<O, CstTimesheetApprovalTRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private CstTimesheetApprovalTPath(Name alias, Table<CstTimesheetApprovalTRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public CstTimesheetApprovalTPath as(String alias) {
			return new CstTimesheetApprovalTPath(DSL.name(alias), this);
		}

		@Override
		public CstTimesheetApprovalTPath as(Name alias) {
			return new CstTimesheetApprovalTPath(alias, this);
		}

		@Override
		public CstTimesheetApprovalTPath as(Table<?> alias) {
			return new CstTimesheetApprovalTPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<CstTimesheetApprovalTRecord, Integer> getIdentity() {
		return (Identity<CstTimesheetApprovalTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<CstTimesheetApprovalTRecord> getPrimaryKey() {
		return Keys.KEY_CST_TIMESHEET_APPROVAL_T_PRIMARY;
	}

	@Override
	public List<ForeignKey<CstTimesheetApprovalTRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_TIMESHEET_APPROVAL_T_TIMESHEET);
	}

	private transient CstTimesheetTPath _cstTimesheetT;

	/**
	 * Get the implicit join path to the <code>cst_timesheet_t</code> table.
	 */
	public CstTimesheetTPath cstTimesheetT() {
		if (_cstTimesheetT == null)
			_cstTimesheetT = new CstTimesheetTPath(this, Keys.FK_TIMESHEET_APPROVAL_T_TIMESHEET, null);

		return _cstTimesheetT;
	}

	@Override
	public CstTimesheetApprovalT as(String alias) {
		return new CstTimesheetApprovalT(DSL.name(alias), this);
	}

	@Override
	public CstTimesheetApprovalT as(Name alias) {
		return new CstTimesheetApprovalT(alias, this);
	}

	@Override
	public CstTimesheetApprovalT as(Table<?> alias) {
		return new CstTimesheetApprovalT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimesheetApprovalT rename(String name) {
		return new CstTimesheetApprovalT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimesheetApprovalT rename(Name name) {
		return new CstTimesheetApprovalT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimesheetApprovalT rename(Table<?> name) {
		return new CstTimesheetApprovalT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetApprovalT where(Condition condition) {
		return new CstTimesheetApprovalT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetApprovalT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetApprovalT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetApprovalT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetApprovalT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetApprovalT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetApprovalT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetApprovalT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetApprovalT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetApprovalT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
