/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimeLogIntervalTRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * Store time log interval
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstTimeLogIntervalT extends TableImpl<CstTimeLogIntervalTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>cst_time_log_interval_t</code>
	 */
	public static final CstTimeLogIntervalT CST_TIME_LOG_INTERVAL_T = new CstTimeLogIntervalT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CstTimeLogIntervalTRecord> getRecordType() {
		return CstTimeLogIntervalTRecord.class;
	}

	/**
	 * The column <code>cst_time_log_interval_t.id</code>. Record ID
	 */
	public final TableField<CstTimeLogIntervalTRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "Record ID");

	/**
	 * The column <code>cst_time_log_interval_t.time_log_id</code>. Referencing
	 * cst_time_log_t
	 */
	public final TableField<CstTimeLogIntervalTRecord, Integer> TIME_LOG_ID = createField(DSL.name("time_log_id"),
			SQLDataType.INTEGER.nullable(false), this, "Referencing cst_time_log_t");

	/**
	 * The column <code>cst_time_log_interval_t.work_start_time</code>. Start time of the
	 * work period
	 */
	public final TableField<CstTimeLogIntervalTRecord, Integer> WORK_START_TIME = createField(
			DSL.name("work_start_time"), SQLDataType.INTEGER, this, "Start time of the work period");

	/**
	 * The column <code>cst_time_log_interval_t.work_end_time</code>. End time of the work
	 * period
	 */
	public final TableField<CstTimeLogIntervalTRecord, Integer> WORK_END_TIME = createField(DSL.name("work_end_time"),
			SQLDataType.INTEGER, this, "End time of the work period");

	/**
	 * The column <code>cst_time_log_interval_t.range_based_remark</code>. Remarks for the
	 * time log entry
	 */
	public final TableField<CstTimeLogIntervalTRecord, String> RANGE_BASED_REMARK = createField(
			DSL.name("range_based_remark"), SQLDataType.CLOB, this, "Remarks for the time log entry");

	/**
	 * The column <code>cst_time_log_interval_t.break_interval</code>. Break interval data
	 * in JSON format
	 */
	public final TableField<CstTimeLogIntervalTRecord, JSON> BREAK_INTERVAL = createField(DSL.name("break_interval"),
			SQLDataType.JSON, this, "Break interval data in JSON format");

	private CstTimeLogIntervalT(Name alias, Table<CstTimeLogIntervalTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private CstTimeLogIntervalT(Name alias, Table<CstTimeLogIntervalTRecord> aliased, Field<?>[] parameters,
			Condition where) {
		super(alias, null, aliased, parameters, DSL.comment("Store time log interval"), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>cst_time_log_interval_t</code> table reference
	 */
	public CstTimeLogIntervalT(String alias) {
		this(DSL.name(alias), CST_TIME_LOG_INTERVAL_T);
	}

	/**
	 * Create an aliased <code>cst_time_log_interval_t</code> table reference
	 */
	public CstTimeLogIntervalT(Name alias) {
		this(alias, CST_TIME_LOG_INTERVAL_T);
	}

	/**
	 * Create a <code>cst_time_log_interval_t</code> table reference
	 */
	public CstTimeLogIntervalT() {
		this(DSL.name("cst_time_log_interval_t"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<CstTimeLogIntervalTRecord, Integer> getIdentity() {
		return (Identity<CstTimeLogIntervalTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<CstTimeLogIntervalTRecord> getPrimaryKey() {
		return Keys.KEY_CST_TIME_LOG_INTERVAL_T_PRIMARY;
	}

	@Override
	public CstTimeLogIntervalT as(String alias) {
		return new CstTimeLogIntervalT(DSL.name(alias), this);
	}

	@Override
	public CstTimeLogIntervalT as(Name alias) {
		return new CstTimeLogIntervalT(alias, this);
	}

	@Override
	public CstTimeLogIntervalT as(Table<?> alias) {
		return new CstTimeLogIntervalT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimeLogIntervalT rename(String name) {
		return new CstTimeLogIntervalT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimeLogIntervalT rename(Name name) {
		return new CstTimeLogIntervalT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimeLogIntervalT rename(Table<?> name) {
		return new CstTimeLogIntervalT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimeLogIntervalT where(Condition condition) {
		return new CstTimeLogIntervalT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimeLogIntervalT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimeLogIntervalT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimeLogIntervalT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimeLogIntervalT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimeLogIntervalT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimeLogIntervalT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimeLogIntervalT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimeLogIntervalT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimeLogIntervalT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
