/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetReimbursementClientShareHistoryTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * Append-only audit log tracking every status transition for reimbursements
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstTimesheetReimbursementClientShareHistoryT
		extends TableImpl<CstTimesheetReimbursementClientShareHistoryTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of
	 * <code>cst_timesheet_reimbursement_client_share_history_t</code>
	 */
	public static final CstTimesheetReimbursementClientShareHistoryT CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T = new CstTimesheetReimbursementClientShareHistoryT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CstTimesheetReimbursementClientShareHistoryTRecord> getRecordType() {
		return CstTimesheetReimbursementClientShareHistoryTRecord.class;
	}

	/**
	 * The column <code>cst_timesheet_reimbursement_client_share_history_t.id</code>.
	 * Unique status history record ID
	 */
	public final TableField<CstTimesheetReimbursementClientShareHistoryTRecord, Integer> ID = createField(
			DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this,
			"Unique status history record ID");

	/**
	 * The column
	 * <code>cst_timesheet_reimbursement_client_share_history_t.cst_timesheet_reimbursement_id</code>.
	 * Reference to reimbursement (cst_timesheet_reimbursement_t.id)
	 */
	public final TableField<CstTimesheetReimbursementClientShareHistoryTRecord, Integer> CST_TIMESHEET_REIMBURSEMENT_ID = createField(
			DSL.name("cst_timesheet_reimbursement_id"), SQLDataType.INTEGER.nullable(false), this,
			"Reference to reimbursement (cst_timesheet_reimbursement_t.id)");

	/**
	 * The column
	 * <code>cst_timesheet_reimbursement_client_share_history_t.is_shared_with_client</code>.
	 * Indicates whether this status history record is shared with the client (1 = Yes, 0
	 * = No)
	 */
	public final TableField<CstTimesheetReimbursementClientShareHistoryTRecord, Byte> IS_SHARED_WITH_CLIENT = createField(
			DSL.name("is_shared_with_client"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this,
			"Indicates whether this status history record is shared with the client (1 = Yes, 0 = No)");

	/**
	 * The column
	 * <code>cst_timesheet_reimbursement_client_share_history_t.created_by</code>. User ID
	 * who performed the status change
	 */
	public final TableField<CstTimesheetReimbursementClientShareHistoryTRecord, Integer> CREATED_BY = createField(
			DSL.name("created_by"), SQLDataType.INTEGER.nullable(false), this,
			"User ID who performed the status change");

	/**
	 * The column
	 * <code>cst_timesheet_reimbursement_client_share_history_t.created_by_user_type_id</code>.
	 * User type of the actor who performed the action; references cst_user_type_t.id.
	 */
	public final TableField<CstTimesheetReimbursementClientShareHistoryTRecord, Integer> CREATED_BY_USER_TYPE_ID = createField(
			DSL.name("created_by_user_type_id"), SQLDataType.INTEGER.nullable(false), this,
			"User type of the actor who performed the action; references cst_user_type_t.id.");

	/**
	 * The column
	 * <code>cst_timesheet_reimbursement_client_share_history_t.created_on</code>. Status
	 * change timestamp (Unix epoch)
	 */
	public final TableField<CstTimesheetReimbursementClientShareHistoryTRecord, Integer> CREATED_ON = createField(
			DSL.name("created_on"), SQLDataType.INTEGER.nullable(false), this, "Status change timestamp (Unix epoch)");

	/**
	 * The column
	 * <code>cst_timesheet_reimbursement_client_share_history_t.account_id</code>.
	 * Reference to the parent timesheet (tblaccount.id)
	 */
	public final TableField<CstTimesheetReimbursementClientShareHistoryTRecord, Integer> ACCOUNT_ID = createField(
			DSL.name("account_id"), SQLDataType.INTEGER.nullable(false), this,
			"Reference to the parent timesheet (tblaccount.id)");

	private CstTimesheetReimbursementClientShareHistoryT(Name alias,
			Table<CstTimesheetReimbursementClientShareHistoryTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private CstTimesheetReimbursementClientShareHistoryT(Name alias,
			Table<CstTimesheetReimbursementClientShareHistoryTRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters,
				DSL.comment("Append-only audit log tracking every status transition for reimbursements"),
				TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>cst_timesheet_reimbursement_client_share_history_t</code>
	 * table reference
	 */
	public CstTimesheetReimbursementClientShareHistoryT(String alias) {
		this(DSL.name(alias), CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T);
	}

	/**
	 * Create an aliased <code>cst_timesheet_reimbursement_client_share_history_t</code>
	 * table reference
	 */
	public CstTimesheetReimbursementClientShareHistoryT(Name alias) {
		this(alias, CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T);
	}

	/**
	 * Create a <code>cst_timesheet_reimbursement_client_share_history_t</code> table
	 * reference
	 */
	public CstTimesheetReimbursementClientShareHistoryT() {
		this(DSL.name("cst_timesheet_reimbursement_client_share_history_t"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(
				Indexes.CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T_IDX_RSH_REIMBURSEMENT_CREATED_ON,
				Indexes.CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T_IDX_RSH_REIMBURSEMENT_ID_ID,
				Indexes.CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T_IDX_RSH_SHARED_WITH_CLIENT_CREATED_ON,
				Indexes.CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T_IDX_STATUS_HISTORY_ACCOUNT_REIMBURSEMENT);
	}

	@Override
	public Identity<CstTimesheetReimbursementClientShareHistoryTRecord, Integer> getIdentity() {
		return (Identity<CstTimesheetReimbursementClientShareHistoryTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<CstTimesheetReimbursementClientShareHistoryTRecord> getPrimaryKey() {
		return Keys.KEY_CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T_PRIMARY;
	}

	@Override
	public CstTimesheetReimbursementClientShareHistoryT as(String alias) {
		return new CstTimesheetReimbursementClientShareHistoryT(DSL.name(alias), this);
	}

	@Override
	public CstTimesheetReimbursementClientShareHistoryT as(Name alias) {
		return new CstTimesheetReimbursementClientShareHistoryT(alias, this);
	}

	@Override
	public CstTimesheetReimbursementClientShareHistoryT as(Table<?> alias) {
		return new CstTimesheetReimbursementClientShareHistoryT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimesheetReimbursementClientShareHistoryT rename(String name) {
		return new CstTimesheetReimbursementClientShareHistoryT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimesheetReimbursementClientShareHistoryT rename(Name name) {
		return new CstTimesheetReimbursementClientShareHistoryT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public CstTimesheetReimbursementClientShareHistoryT rename(Table<?> name) {
		return new CstTimesheetReimbursementClientShareHistoryT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetReimbursementClientShareHistoryT where(Condition condition) {
		return new CstTimesheetReimbursementClientShareHistoryT(getQualifiedName(), aliased() ? this : null, null,
				condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetReimbursementClientShareHistoryT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetReimbursementClientShareHistoryT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetReimbursementClientShareHistoryT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetReimbursementClientShareHistoryT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetReimbursementClientShareHistoryT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetReimbursementClientShareHistoryT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public CstTimesheetReimbursementClientShareHistoryT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetReimbursementClientShareHistoryT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public CstTimesheetReimbursementClientShareHistoryT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
