/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.records.EntityOffLimitTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EntityOffLimitT extends TableImpl<EntityOffLimitTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>entity_off_limit_t</code>
	 */
	public static final EntityOffLimitT ENTITY_OFF_LIMIT_T = new EntityOffLimitT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EntityOffLimitTRecord> getRecordType() {
		return EntityOffLimitTRecord.class;
	}

	/**
	 * The column <code>entity_off_limit_t.id</code>.
	 */
	public final TableField<EntityOffLimitTRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>entity_off_limit_t.entity_id</code>. ID of the entity marked as
	 * off-limit
	 */
	public final TableField<EntityOffLimitTRecord, Integer> ENTITY_ID = createField(DSL.name("entity_id"),
			SQLDataType.INTEGER.nullable(false), this, "ID of the entity marked as off-limit");

	/**
	 * The column <code>entity_off_limit_t.entity_type</code>. Type of the entity marked
	 * as off-limit
	 */
	public final TableField<EntityOffLimitTRecord, Integer> ENTITY_TYPE = createField(DSL.name("entity_type"),
			SQLDataType.INTEGER.nullable(false), this, "Type of the entity marked as off-limit");

	/**
	 * The column <code>entity_off_limit_t.account_id</code>. Account ID of the entity
	 */
	public final TableField<EntityOffLimitTRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"),
			SQLDataType.INTEGER.nullable(false), this, "Account ID of the entity");

	/**
	 * The column <code>entity_off_limit_t.off_limit_status_id</code>. Key referencing the
	 * id in off_limit_status_t
	 */
	public final TableField<EntityOffLimitTRecord, Integer> OFF_LIMIT_STATUS_ID = createField(
			DSL.name("off_limit_status_id"), SQLDataType.INTEGER.nullable(false), this,
			"Key referencing the id in off_limit_status_t");

	/**
	 * The column <code>entity_off_limit_t.off_limit_reason</code>. Reason for marking
	 * off-limit
	 */
	public final TableField<EntityOffLimitTRecord, String> OFF_LIMIT_REASON = createField(DSL.name("off_limit_reason"),
			SQLDataType.VARCHAR(1000), this, "Reason for marking off-limit");

	/**
	 * The column <code>entity_off_limit_t.off_limit_end_date</code>. Date when off-limit
	 * ends
	 */
	public final TableField<EntityOffLimitTRecord, Integer> OFF_LIMIT_END_DATE = createField(
			DSL.name("off_limit_end_date"), SQLDataType.INTEGER, this, "Date when off-limit ends");

	/**
	 * The column <code>entity_off_limit_t.created_on</code>. Date when entity was marked
	 * off-limit
	 */
	public final TableField<EntityOffLimitTRecord, Integer> CREATED_ON = createField(DSL.name("created_on"),
			SQLDataType.INTEGER.nullable(false), this, "Date when entity was marked off-limit");

	/**
	 * The column <code>entity_off_limit_t.created_by</code>. ID of user marking entity as
	 * off-limit
	 */
	public final TableField<EntityOffLimitTRecord, Integer> CREATED_BY = createField(DSL.name("created_by"),
			SQLDataType.INTEGER.nullable(false), this, "ID of user marking entity as off-limit");

	/**
	 * The column <code>entity_off_limit_t.off_limit_contact</code>. Flag For Compnay
	 * related contact marked off-limit
	 */
	public final TableField<EntityOffLimitTRecord, Integer> OFF_LIMIT_CONTACT = createField(
			DSL.name("off_limit_contact"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Flag For Compnay related contact marked off-limit");

	/**
	 * The column <code>entity_off_limit_t.off_limit_candidate</code>. Flag For Compnay
	 * related candidate marked off-limit
	 */
	public final TableField<EntityOffLimitTRecord, Integer> OFF_LIMIT_CANDIDATE = createField(
			DSL.name("off_limit_candidate"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)),
			this, "Flag For Compnay related candidate marked off-limit");

	/**
	 * The column <code>entity_off_limit_t.migration_reserved</code>. Used for migration
	 */
	public final TableField<EntityOffLimitTRecord, String> MIGRATION_RESERVED = createField(
			DSL.name("migration_reserved"), SQLDataType.VARCHAR(90).defaultValue(DSL.inline("", SQLDataType.VARCHAR)),
			this, "Used for migration");

	private EntityOffLimitT(Name alias, Table<EntityOffLimitTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private EntityOffLimitT(Name alias, Table<EntityOffLimitTRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>entity_off_limit_t</code> table reference
	 */
	public EntityOffLimitT(String alias) {
		this(DSL.name(alias), ENTITY_OFF_LIMIT_T);
	}

	/**
	 * Create an aliased <code>entity_off_limit_t</code> table reference
	 */
	public EntityOffLimitT(Name alias) {
		this(alias, ENTITY_OFF_LIMIT_T);
	}

	/**
	 * Create a <code>entity_off_limit_t</code> table reference
	 */
	public EntityOffLimitT() {
		this(DSL.name("entity_off_limit_t"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.ENTITY_OFF_LIMIT_T_ENTITY_OFF_LIMIT_INDEX_ACCOUNT_ID,
				Indexes.ENTITY_OFF_LIMIT_T_ENTITY_OFF_LIMIT_INDEX_STATUS_ID);
	}

	@Override
	public Identity<EntityOffLimitTRecord, Integer> getIdentity() {
		return (Identity<EntityOffLimitTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<EntityOffLimitTRecord> getPrimaryKey() {
		return Keys.KEY_ENTITY_OFF_LIMIT_T_PRIMARY;
	}

	@Override
	public List<UniqueKey<EntityOffLimitTRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_ENTITY_OFF_LIMIT_T_ENTITY_OFF_LIMIT_INDEX_ENTITY_TYPE_ENTITY_ID);
	}

	@Override
	public EntityOffLimitT as(String alias) {
		return new EntityOffLimitT(DSL.name(alias), this);
	}

	@Override
	public EntityOffLimitT as(Name alias) {
		return new EntityOffLimitT(alias, this);
	}

	@Override
	public EntityOffLimitT as(Table<?> alias) {
		return new EntityOffLimitT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public EntityOffLimitT rename(String name) {
		return new EntityOffLimitT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public EntityOffLimitT rename(Name name) {
		return new EntityOffLimitT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public EntityOffLimitT rename(Table<?> name) {
		return new EntityOffLimitT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EntityOffLimitT where(Condition condition) {
		return new EntityOffLimitT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EntityOffLimitT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EntityOffLimitT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EntityOffLimitT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EntityOffLimitT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EntityOffLimitT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EntityOffLimitT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EntityOffLimitT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EntityOffLimitT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EntityOffLimitT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
