/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcontact.TblcontactPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbljob.TbljobPath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.JobSecondaryContactsTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobSecondaryContactsT extends TableImpl<JobSecondaryContactsTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>job_secondary_contacts_t</code>
	 */
	public static final JobSecondaryContactsT JOB_SECONDARY_CONTACTS_T = new JobSecondaryContactsT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<JobSecondaryContactsTRecord> getRecordType() {
		return JobSecondaryContactsTRecord.class;
	}

	/**
	 * The column <code>job_secondary_contacts_t.id</code>.
	 */
	public final TableField<JobSecondaryContactsTRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>job_secondary_contacts_t.job_id</code>.
	 */
	public final TableField<JobSecondaryContactsTRecord, Integer> JOB_ID = createField(DSL.name("job_id"),
			SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>job_secondary_contacts_t.contact_id</code>.
	 */
	public final TableField<JobSecondaryContactsTRecord, Integer> CONTACT_ID = createField(DSL.name("contact_id"),
			SQLDataType.INTEGER.nullable(false), this, "");

	private JobSecondaryContactsT(Name alias, Table<JobSecondaryContactsTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private JobSecondaryContactsT(Name alias, Table<JobSecondaryContactsTRecord> aliased, Field<?>[] parameters,
			Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>job_secondary_contacts_t</code> table reference
	 */
	public JobSecondaryContactsT(String alias) {
		this(DSL.name(alias), JOB_SECONDARY_CONTACTS_T);
	}

	/**
	 * Create an aliased <code>job_secondary_contacts_t</code> table reference
	 */
	public JobSecondaryContactsT(Name alias) {
		this(alias, JOB_SECONDARY_CONTACTS_T);
	}

	/**
	 * Create a <code>job_secondary_contacts_t</code> table reference
	 */
	public JobSecondaryContactsT() {
		this(DSL.name("job_secondary_contacts_t"), null);
	}

	public <O extends Record> JobSecondaryContactsT(Table<O> path, ForeignKey<O, JobSecondaryContactsTRecord> childPath,
			InverseForeignKey<O, JobSecondaryContactsTRecord> parentPath) {
		super(path, childPath, parentPath, JOB_SECONDARY_CONTACTS_T);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class JobSecondaryContactsTPath extends JobSecondaryContactsT
			implements Path<JobSecondaryContactsTRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> JobSecondaryContactsTPath(Table<O> path,
				ForeignKey<O, JobSecondaryContactsTRecord> childPath,
				InverseForeignKey<O, JobSecondaryContactsTRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private JobSecondaryContactsTPath(Name alias, Table<JobSecondaryContactsTRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public JobSecondaryContactsTPath as(String alias) {
			return new JobSecondaryContactsTPath(DSL.name(alias), this);
		}

		@Override
		public JobSecondaryContactsTPath as(Name alias) {
			return new JobSecondaryContactsTPath(alias, this);
		}

		@Override
		public JobSecondaryContactsTPath as(Table<?> alias) {
			return new JobSecondaryContactsTPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.JOB_SECONDARY_CONTACTS_T_FK_JOB__IDX,
				Indexes.JOB_SECONDARY_CONTACTS_T_FK_JOBSECONDARYCONTACT_CONTACT_IDX);
	}

	@Override
	public Identity<JobSecondaryContactsTRecord, Integer> getIdentity() {
		return (Identity<JobSecondaryContactsTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<JobSecondaryContactsTRecord> getPrimaryKey() {
		return Keys.KEY_JOB_SECONDARY_CONTACTS_T_PRIMARY;
	}

	@Override
	public List<UniqueKey<JobSecondaryContactsTRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_JOB_SECONDARY_CONTACTS_T_INDEX_JOB_CONTACT);
	}

	@Override
	public List<ForeignKey<JobSecondaryContactsTRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_JOBSECONDARYCONTACT_CONTACT, Keys.FK_JOBSECONDARYCONTACT_JOB);
	}

	private transient TblcontactPath _tblcontact;

	/**
	 * Get the implicit join path to the <code>tblcontact</code> table.
	 */
	public TblcontactPath tblcontact() {
		if (_tblcontact == null)
			_tblcontact = new TblcontactPath(this, Keys.FK_JOBSECONDARYCONTACT_CONTACT, null);

		return _tblcontact;
	}

	private transient TbljobPath _tbljob;

	/**
	 * Get the implicit join path to the <code>tbljob</code> table.
	 */
	public TbljobPath tbljob() {
		if (_tbljob == null)
			_tbljob = new TbljobPath(this, Keys.FK_JOBSECONDARYCONTACT_JOB, null);

		return _tbljob;
	}

	@Override
	public JobSecondaryContactsT as(String alias) {
		return new JobSecondaryContactsT(DSL.name(alias), this);
	}

	@Override
	public JobSecondaryContactsT as(Name alias) {
		return new JobSecondaryContactsT(alias, this);
	}

	@Override
	public JobSecondaryContactsT as(Table<?> alias) {
		return new JobSecondaryContactsT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public JobSecondaryContactsT rename(String name) {
		return new JobSecondaryContactsT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public JobSecondaryContactsT rename(Name name) {
		return new JobSecondaryContactsT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public JobSecondaryContactsT rename(Table<?> name) {
		return new JobSecondaryContactsT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public JobSecondaryContactsT where(Condition condition) {
		return new JobSecondaryContactsT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public JobSecondaryContactsT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public JobSecondaryContactsT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public JobSecondaryContactsT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public JobSecondaryContactsT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public JobSecondaryContactsT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public JobSecondaryContactsT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public JobSecondaryContactsT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public JobSecondaryContactsT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public JobSecondaryContactsT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
