/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.records.OffLimitStatusTRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OffLimitStatusT extends TableImpl<OffLimitStatusTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>off_limit_status_t</code>
	 */
	public static final OffLimitStatusT OFF_LIMIT_STATUS_T = new OffLimitStatusT();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<OffLimitStatusTRecord> getRecordType() {
		return OffLimitStatusTRecord.class;
	}

	/**
	 * The column <code>off_limit_status_t.id</code>.
	 */
	public final TableField<OffLimitStatusTRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>off_limit_status_t.status_label</code>. Lable for Off-Limit Status
	 */
	public final TableField<OffLimitStatusTRecord, String> STATUS_LABEL = createField(DSL.name("status_label"),
			SQLDataType.VARCHAR(50).nullable(false), this, "Lable for Off-Limit Status");

	/**
	 * The column <code>off_limit_status_t.status_colour_id</code>. Key referencing the
	 * offlimit_status_colour_id in off_limit_status_colour_t
	 */
	public final TableField<OffLimitStatusTRecord, String> STATUS_COLOUR_ID = createField(DSL.name("status_colour_id"),
			SQLDataType.VARCHAR(7).nullable(false), this,
			"Key referencing the offlimit_status_colour_id in off_limit_status_colour_t");

	/**
	 * The column <code>off_limit_status_t.sequence_no</code>. Sequence number according
	 * to the label
	 */
	public final TableField<OffLimitStatusTRecord, Integer> SEQUENCE_NO = createField(DSL.name("sequence_no"),
			SQLDataType.INTEGER.nullable(false), this, "Sequence number according to the label");

	/**
	 * The column <code>off_limit_status_t.account_id</code>. Account id of the status
	 */
	public final TableField<OffLimitStatusTRecord, Integer> ACCOUNT_ID = createField(DSL.name("account_id"),
			SQLDataType.INTEGER.nullable(false), this, "Account id of the status");

	/**
	 * The column <code>off_limit_status_t.default</code>. Flag for default status
	 */
	public final TableField<OffLimitStatusTRecord, Byte> DEFAULT = createField(DSL.name("default"),
			SQLDataType.TINYINT.nullable(false), this, "Flag for default status");

	private OffLimitStatusT(Name alias, Table<OffLimitStatusTRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private OffLimitStatusT(Name alias, Table<OffLimitStatusTRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>off_limit_status_t</code> table reference
	 */
	public OffLimitStatusT(String alias) {
		this(DSL.name(alias), OFF_LIMIT_STATUS_T);
	}

	/**
	 * Create an aliased <code>off_limit_status_t</code> table reference
	 */
	public OffLimitStatusT(Name alias) {
		this(alias, OFF_LIMIT_STATUS_T);
	}

	/**
	 * Create a <code>off_limit_status_t</code> table reference
	 */
	public OffLimitStatusT() {
		this(DSL.name("off_limit_status_t"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.OFF_LIMIT_STATUS_T_IDX_STATUS_COLOUR_ID,
				Indexes.OFF_LIMIT_STATUS_T_INDEX_ACCOUNT_ID, Indexes.OFF_LIMIT_STATUS_T_ISX_STATUS_LABEL);
	}

	@Override
	public Identity<OffLimitStatusTRecord, Integer> getIdentity() {
		return (Identity<OffLimitStatusTRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<OffLimitStatusTRecord> getPrimaryKey() {
		return Keys.KEY_OFF_LIMIT_STATUS_T_PRIMARY;
	}

	@Override
	public OffLimitStatusT as(String alias) {
		return new OffLimitStatusT(DSL.name(alias), this);
	}

	@Override
	public OffLimitStatusT as(Name alias) {
		return new OffLimitStatusT(alias, this);
	}

	@Override
	public OffLimitStatusT as(Table<?> alias) {
		return new OffLimitStatusT(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public OffLimitStatusT rename(String name) {
		return new OffLimitStatusT(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public OffLimitStatusT rename(Name name) {
		return new OffLimitStatusT(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public OffLimitStatusT rename(Table<?> name) {
		return new OffLimitStatusT(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public OffLimitStatusT where(Condition condition) {
		return new OffLimitStatusT(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public OffLimitStatusT where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public OffLimitStatusT where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public OffLimitStatusT where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public OffLimitStatusT where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public OffLimitStatusT where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public OffLimitStatusT where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public OffLimitStatusT where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public OffLimitStatusT whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public OffLimitStatusT whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
