/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.CandidateCustomFieldsT.CandidateCustomFieldsTPath;
import io.recruitcrm.microservice.search.models.jooq.tables.CandidateLastActivitiesT.CandidateLastActivitiesTPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblassignjobcandidate.TblassignjobcandidatePath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcurrency.TblcurrencyPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldealcandidates.TbldealcandidatesPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblgender.TblgenderPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbluser.TbluserPath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblcandidateRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tblcandidate extends TableImpl<TblcandidateRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>tblcandidate</code>
	 */
	public static final Tblcandidate TBLCANDIDATE = new Tblcandidate();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TblcandidateRecord> getRecordType() {
		return TblcandidateRecord.class;
	}

	/**
	 * The column <code>tblcandidate.id</code>.
	 */
	public final TableField<TblcandidateRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>tblcandidate.srno</code>. This serial number is for user to
	 * identify the record by id. This value is generated account wise. There will be same
	 * srno for different accounts but not in same account.
	 */
	public final TableField<TblcandidateRecord, Integer> SRNO = createField(DSL.name("srno"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"This serial number is for user to identify the record by id. This value is generated account wise. There will be same srno for different accounts but not in same account.");

	/**
	 * The column <code>tblcandidate.firstname</code>.
	 */
	public final TableField<TblcandidateRecord, String> FIRSTNAME = createField(DSL.name("firstname"),
			SQLDataType.VARCHAR(60), this, "");

	/**
	 * The column <code>tblcandidate.lastname</code>.
	 */
	public final TableField<TblcandidateRecord, String> LASTNAME = createField(DSL.name("lastname"),
			SQLDataType.VARCHAR(60), this, "");

	/**
	 * The column <code>tblcandidate.emailid</code>. Email Address of candidate.
	 */
	public final TableField<TblcandidateRecord, String> EMAILID = createField(DSL.name("emailid"),
			SQLDataType.VARCHAR(100).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this,
			"Email Address of candidate.");

	/**
	 * The column <code>tblcandidate.genderid</code>. Gender id of candidate.\nReference -
	 * tblgender
	 */
	public final TableField<TblcandidateRecord, Byte> GENDERID = createField(DSL.name("genderid"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Gender id of candidate.\\nReference - tblgender");

	/**
	 * The column <code>tblcandidate.contactnumber</code>. Contact number of candidate(can
	 * be multiple using comma).
	 */
	public final TableField<TblcandidateRecord, String> CONTACTNUMBER = createField(DSL.name("contactnumber"),
			SQLDataType.VARCHAR(100).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this,
			"Contact number of candidate(can be multiple using comma).");

	/**
	 * The column <code>tblcandidate.qualificationid</code>. Qualification of candidate.
	 * Reference - tblqualifications
	 */
	public final TableField<TblcandidateRecord, Integer> QUALIFICATIONID = createField(DSL.name("qualificationid"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Qualification of candidate.\nReference - tblqualifications");

	/**
	 * The column <code>tblcandidate.specialization</code>. Qualification specialization.
	 */
	public final TableField<TblcandidateRecord, String> SPECIALIZATION = createField(DSL.name("specialization"),
			SQLDataType.VARCHAR(200).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this,
			"Qualification specialization.");

	/**
	 * The column <code>tblcandidate.locationid</code>.
	 */
	public final TableField<TblcandidateRecord, Short> LOCATIONID = createField(DSL.name("locationid"),
			SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.SMALLINT)), this, "");

	/**
	 * The column <code>tblcandidate.workexpyr</code>. Work experience in years.
	 */
	public final TableField<TblcandidateRecord, Byte> WORKEXPYR = createField(DSL.name("workexpyr"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Work experience in years.");

	/**
	 * The column <code>tblcandidate.workexpmonth</code>. Work experience in months.
	 */
	public final TableField<TblcandidateRecord, Byte> WORKEXPMONTH = createField(DSL.name("workexpmonth"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Work experience in months.");

	/**
	 * The column <code>tblcandidate.candidatedob</code>. Date of birth of candidate.
	 */
	public final TableField<TblcandidateRecord, Integer> CANDIDATEDOB = createField(DSL.name("candidatedob"),
			SQLDataType.INTEGER, this, "Date of birth of candidate.");

	/**
	 * The column <code>tblcandidate.currentsalary</code>. Current salary of candidate.
	 */
	public final TableField<TblcandidateRecord, Double> CURRENTSALARY = createField(DSL.name("currentsalary"),
			SQLDataType.FLOAT.nullable(false).defaultValue(DSL.inline("0.00", SQLDataType.FLOAT)), this,
			"Current salary of candidate.");

	/**
	 * The column <code>tblcandidate.salaryexpectation</code>. Expected Salary of
	 * candidate.
	 */
	public final TableField<TblcandidateRecord, Double> SALARYEXPECTATION = createField(DSL.name("salaryexpectation"),
			SQLDataType.FLOAT.nullable(false).defaultValue(DSL.inline("0.00", SQLDataType.FLOAT)), this,
			"Expected Salary of candidate.");

	/**
	 * The column <code>tblcandidate.resume</code>. Link of the resume.
	 */
	public final TableField<TblcandidateRecord, String> RESUME = createField(DSL.name("resume"),
			SQLDataType.VARCHAR(350), this, "Link of the resume.");

	/**
	 * The column <code>tblcandidate.resumefilename</code>. Resume File name.
	 */
	public final TableField<TblcandidateRecord, String> RESUMEFILENAME = createField(DSL.name("resumefilename"),
			SQLDataType.VARCHAR(350), this, "Resume File name.");

	/**
	 * The column <code>tblcandidate.willingtorelocate</code>. Does candidate willing to
	 * relocate 0 - no, 1 -yes
	 */
	public final TableField<TblcandidateRecord, Byte> WILLINGTORELOCATE = createField(DSL.name("willingtorelocate"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Does candidate willing to relocate\n0 - no, \n1 -yes");

	/**
	 * The column <code>tblcandidate.lastorganisation</code>. Last organisation of
	 * candidate.
	 */
	public final TableField<TblcandidateRecord, String> LASTORGANISATION = createField(DSL.name("lastorganisation"),
			SQLDataType.VARCHAR(300).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this,
			"Last organisation of candidate.");

	/**
	 * The column <code>tblcandidate.currentstatus</code>. Current employment status.
	 */
	public final TableField<TblcandidateRecord, String> CURRENTSTATUS = createField(DSL.name("currentstatus"),
			SQLDataType.VARCHAR(45), this, "Current employment status.");

	/**
	 * The column <code>tblcandidate.noticeperiod</code>. Notice period in current
	 * company.
	 */
	public final TableField<TblcandidateRecord, Integer> NOTICEPERIOD = createField(DSL.name("noticeperiod"),
			SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Notice period in current company.");

	/**
	 * The column <code>tblcandidate.currencyid</code>. Currency of candidate. Reference -
	 * tblcurrency
	 */
	public final TableField<TblcandidateRecord, Integer> CURRENCYID = createField(DSL.name("currencyid"),
			SQLDataType.INTEGER, this, "Currency of candidate.\nReference - tblcurrency");

	/**
	 * The column <code>tblcandidate.slug</code>. Unique value generated using trigger.
	 */
	public final TableField<TblcandidateRecord, String> SLUG = createField(DSL.name("slug"),
			SQLDataType.VARCHAR(90).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this,
			"Unique value generated using trigger.");

	/**
	 * The column <code>tblcandidate.authid</code>.
	 */
	public final TableField<TblcandidateRecord, String> AUTHID = createField(DSL.name("authid"),
			SQLDataType.VARCHAR(100), this, "");

	/**
	 * The column <code>tblcandidate.resumeupdatedon</code>. Timestamp when last time
	 * resume updated.
	 */
	public final TableField<TblcandidateRecord, Integer> RESUMEUPDATEDON = createField(DSL.name("resumeupdatedon"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Timestamp when last time resume updated.");

	/**
	 * The column <code>tblcandidate.resumeupdaterequestedon</code>. Request profile
	 * updated link generated on time.
	 */
	public final TableField<TblcandidateRecord, Integer> RESUMEUPDATEREQUESTEDON = createField(
			DSL.name("resumeupdaterequestedon"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Request profile updated link generated on time.");

	/**
	 * The column <code>tblcandidate.requestresumelinkstatus</code>. Profile Update link
	 * status 0 - Not Active, 1 - Active
	 *
	 */
	public final TableField<TblcandidateRecord, Byte> REQUESTRESUMELINKSTATUS = createField(
			DSL.name("requestresumelinkstatus"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Profile Update link status\n0 - Not Active,\n1 - Active\n");

	/**
	 * The column <code>tblcandidate.resumeaddedon</code>. First time resume added time.
	 */
	public final TableField<TblcandidateRecord, Integer> RESUMEADDEDON = createField(DSL.name("resumeaddedon"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"First time resume added time.");

	/**
	 * The column <code>tblcandidate.profilepic</code>. Profile photo URL.
	 */
	public final TableField<TblcandidateRecord, String> PROFILEPIC = createField(DSL.name("profilepic"),
			SQLDataType.VARCHAR(250), this, "Profile photo URL.");

	/**
	 * The column <code>tblcandidate.profilefacebook</code>. Facebook profile url.
	 */
	public final TableField<TblcandidateRecord, String> PROFILEFACEBOOK = createField(DSL.name("profilefacebook"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "Facebook profile url.");

	/**
	 * The column <code>tblcandidate.profilegithub</code>. GitHub profile URL.
	 */
	public final TableField<TblcandidateRecord, String> PROFILEGITHUB = createField(DSL.name("profilegithub"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "GitHub profile URL.");

	/**
	 * The column <code>tblcandidate.profiletwitter</code>. Twitter profile url.
	 */
	public final TableField<TblcandidateRecord, String> PROFILETWITTER = createField(DSL.name("profiletwitter"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "Twitter profile url.");

	/**
	 * The column <code>tblcandidate.profilelinkedin</code>. Linkedin profile url.
	 */
	public final TableField<TblcandidateRecord, String> PROFILELINKEDIN = createField(DSL.name("profilelinkedin"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "Linkedin profile url.");

	/**
	 * The column <code>tblcandidate.deleted</code>.
	 */
	public final TableField<TblcandidateRecord, Byte> DELETED = createField(DSL.name("deleted"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

	/**
	 * The column <code>tblcandidate.ownerid</code>. User id who owns that record.
	 * Reference - tbluser
	 */
	public final TableField<TblcandidateRecord, Integer> OWNERID = createField(DSL.name("ownerid"), SQLDataType.INTEGER,
			this, "User id who owns that record.\nReference - tbluser");

	/**
	 * The column <code>tblcandidate.accountid</code>. Account id of candidate. Reference
	 * - tblaccount
	 */
	public final TableField<TblcandidateRecord, Integer> ACCOUNTID = createField(DSL.name("accountid"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Account id of candidate.\nReference - tblaccount");

	/**
	 * The column <code>tblcandidate.createdby</code>. User id who created the record.
	 */
	public final TableField<TblcandidateRecord, Integer> CREATEDBY = createField(DSL.name("createdby"),
			SQLDataType.INTEGER.nullable(false), this, "User id who created the record.");

	/**
	 * The column <code>tblcandidate.createdon</code>. Time when record added.
	 */
	public final TableField<TblcandidateRecord, Integer> CREATEDON = createField(DSL.name("createdon"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Time when record added.");

	/**
	 * The column <code>tblcandidate.updatedby</code>. User id who updated the record.
	 */
	public final TableField<TblcandidateRecord, Integer> UPDATEDBY = createField(DSL.name("updatedby"),
			SQLDataType.INTEGER.nullable(false), this, "User id who updated the record.");

	/**
	 * The column <code>tblcandidate.updatedon</code>. Time when record updated.
	 */
	public final TableField<TblcandidateRecord, Integer> UPDATEDON = createField(DSL.name("updatedon"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Time when record updated.");

	/**
	 * The column <code>tblcandidate.locality</code>. Locality of candidate.
	 */
	public final TableField<TblcandidateRecord, String> LOCALITY = createField(DSL.name("locality"),
			SQLDataType.VARCHAR(100).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "Locality of candidate.");

	/**
	 * The column <code>tblcandidate.city</code>. City of candidate.
	 */
	public final TableField<TblcandidateRecord, String> CITY = createField(DSL.name("city"),
			SQLDataType.VARCHAR(50).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "City of candidate.");

	/**
	 * The column <code>tblcandidate.state</code>.
	 */
	public final TableField<TblcandidateRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(50),
			this, "");

	/**
	 * The column <code>tblcandidate.country</code>.
	 */
	public final TableField<TblcandidateRecord, String> COUNTRY = createField(DSL.name("country"),
			SQLDataType.VARCHAR(50), this, "");

	/**
	 * The column <code>tblcandidate.lng</code>. Latitude - Used for radius search.
	 */
	public final TableField<TblcandidateRecord, Integer> LNG = createField(DSL.name("lng"),
			SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Latitude - Used for radius search.");

	/**
	 * The column <code>tblcandidate.relevantexperience</code>. Relevant Experience of
	 * candidate.
	 */
	public final TableField<TblcandidateRecord, Integer> RELEVANTEXPERIENCE = createField(
			DSL.name("relevantexperience"), SQLDataType.INTEGER, this, "Relevant Experience of candidate.");

	/**
	 * The column <code>tblcandidate.position</code>. Title/position of candidate.
	 */
	public final TableField<TblcandidateRecord, String> POSITION = createField(DSL.name("position"),
			SQLDataType.VARCHAR(512).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this,
			"Title/position of candidate.");

	/**
	 * The column <code>tblcandidate.canaccess</code>. User ids who is not owner and not
	 * having full access but need to see the record (comma separated).
	 */
	public final TableField<TblcandidateRecord, String> CANACCESS = createField(DSL.name("canaccess"), SQLDataType.CLOB,
			this, "User ids who is not owner and not having full access but need to see the record (comma separated).");

	/**
	 * The column <code>tblcandidate.availablefrom</code>. Unix timestamp frm when
	 * candidate is available to join.
	 */
	public final TableField<TblcandidateRecord, Integer> AVAILABLEFROM = createField(DSL.name("availablefrom"),
			SQLDataType.INTEGER, this, "Unix timestamp frm when candidate is available to join.");

	/**
	 * The column <code>tblcandidate.salarytype</code>. salary type id.
	 */
	public final TableField<TblcandidateRecord, String> SALARYTYPE = createField(DSL.name("salarytype"),
			SQLDataType.VARCHAR(30), this, "salary type id.");

	/**
	 * The column <code>tblcandidate.source</code>. Source where candidate came from.
	 */
	public final TableField<TblcandidateRecord, String> SOURCE = createField(DSL.name("source"), SQLDataType.CLOB, this,
			"Source where candidate came from.");

	/**
	 * The column <code>tblcandidate.sourceadded</code>. This is the system field to track
	 * from where candidate is added.
	 */
	public final TableField<TblcandidateRecord, String> SOURCEADDED = createField(DSL.name("sourceadded"),
			SQLDataType.CLOB, this, "This is the system field to track from where candidate is added.");

	/**
	 * The column <code>tblcandidate.languageskills</code>. Multiple language skills.
	 */
	public final TableField<TblcandidateRecord, String> LANGUAGESKILLS = createField(DSL.name("languageskills"),
			SQLDataType.CLOB, this, "Multiple language skills.");

	/**
	 * The column <code>tblcandidate.skill</code>. Skills of candidate in comma separated
	 * format.
	 */
	public final TableField<TblcandidateRecord, String> SKILL = createField(DSL.name("skill"), SQLDataType.CLOB, this,
			"Skills of candidate in comma separated format.");

	/**
	 * The column <code>tblcandidate.isduplicate</code>. Status if the candidate is
	 * duplicate.
	 */
	public final TableField<TblcandidateRecord, Byte> ISDUPLICATE = createField(DSL.name("isduplicate"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Status if the candidate is duplicate.");

	/**
	 * The column <code>tblcandidate.address</code>. Address of candidate.
	 */
	public final TableField<TblcandidateRecord, String> ADDRESS = createField(DSL.name("address"),
			SQLDataType.VARCHAR(500), this, "Address of candidate.");

	/**
	 * The column <code>tblcandidate.lat</code>. Latitude - Used for radius search.
	 */
	public final TableField<TblcandidateRecord, Integer> LAT = createField(DSL.name("lat"), SQLDataType.INTEGER, this,
			"Latitude - Used for radius search.");

	/**
	 * The column <code>tblcandidate.sourceid</code>.
	 */
	public final TableField<TblcandidateRecord, Integer> SOURCEID = createField(DSL.name("sourceid"),
			SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tblcandidate.migration_reserved1</code>.
	 */
	public final TableField<TblcandidateRecord, String> MIGRATION_RESERVED1 = createField(
			DSL.name("migration_reserved1"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>tblcandidate.migration_reserved2</code>.
	 */
	public final TableField<TblcandidateRecord, String> MIGRATION_RESERVED2 = createField(
			DSL.name("migration_reserved2"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>tblcandidate.email_opt_out</code>. Option to opt out from
	 * receiving the emails
	 */
	public final TableField<TblcandidateRecord, Byte> EMAIL_OPT_OUT = createField(DSL.name("email_opt_out"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Option to opt out from receiving the emails");

	/**
	 * The column <code>tblcandidate.profilexing</code>.
	 */
	public final TableField<TblcandidateRecord, String> PROFILEXING = createField(DSL.name("profilexing"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>tblcandidate.unavailable</code>.
	 */
	public final TableField<TblcandidateRecord, Byte> UNAVAILABLE = createField(DSL.name("unavailable"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

	/**
	 * The column <code>tblcandidate.availability_updated_by</code>.
	 */
	public final TableField<TblcandidateRecord, Integer> AVAILABILITY_UPDATED_BY = createField(
			DSL.name("availability_updated_by"), SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tblcandidate.sms_consent</code>.
	 */
	public final TableField<TblcandidateRecord, Byte> SMS_CONSENT = createField(DSL.name("sms_consent"),
			SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

	/**
	 * The column <code>tblcandidate.sovren_document_id</code>.
	 */
	public final TableField<TblcandidateRecord, String> SOVREN_DOCUMENT_ID = createField(DSL.name("sovren_document_id"),
			SQLDataType.VARCHAR(50), this, "");

	/**
	 * The column <code>tblcandidate.email_opt_out_source</code>.
	 */
	public final TableField<TblcandidateRecord, Byte> EMAIL_OPT_OUT_SOURCE = createField(
			DSL.name("email_opt_out_source"), SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>tblcandidate.merge_flag</code>.
	 */
	public final TableField<TblcandidateRecord, Byte> MERGE_FLAG = createField(DSL.name("merge_flag"),
			SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

	/**
	 * The column <code>tblcandidate.formatted_contact_number</code>.
	 */
	public final TableField<TblcandidateRecord, String> FORMATTED_CONTACT_NUMBER = createField(
			DSL.name("formatted_contact_number"),
			SQLDataType.VARCHAR(100).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>tblcandidate.external_profile_updated_on</code>. Unix timestamp of
	 * candidate updated from external page
	 */
	public final TableField<TblcandidateRecord, Integer> EXTERNAL_PROFILE_UPDATED_ON = createField(
			DSL.name("external_profile_updated_on"), SQLDataType.INTEGER, this,
			"Unix timestamp of candidate updated from external page");

	/**
	 * The column <code>tblcandidate.formatted_profilelinkedin</code>.
	 */
	public final TableField<TblcandidateRecord, String> FORMATTED_PROFILELINKEDIN = createField(
			DSL.name("formatted_profilelinkedin"),
			SQLDataType.VARCHAR(200).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>tblcandidate.formatted_profile_linkedin</code>.
	 */
	public final TableField<TblcandidateRecord, String> FORMATTED_PROFILE_LINKEDIN = createField(
			DSL.name("formatted_profile_linkedin"),
			SQLDataType.VARCHAR(200).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>tblcandidate.sms_opt_out</code>.
	 */
	public final TableField<TblcandidateRecord, Byte> SMS_OPT_OUT = createField(DSL.name("sms_opt_out"),
			SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

	/**
	 * The column <code>tblcandidate.postal_code</code>. Column to store Postal code of
	 * the candidate address
	 */
	public final TableField<TblcandidateRecord, String> POSTAL_CODE = createField(DSL.name("postal_code"),
			SQLDataType.VARCHAR(50), this, "Column to store Postal code of the candidate address");

	/**
	 * The column <code>tblcandidate.portal_access</code>. Portal access for candidate
	 */
	public final TableField<TblcandidateRecord, Byte> PORTAL_ACCESS = createField(DSL.name("portal_access"),
			SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"Portal access for candidate");

	private Tblcandidate(Name alias, Table<TblcandidateRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Tblcandidate(Name alias, Table<TblcandidateRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>tblcandidate</code> table reference
	 */
	public Tblcandidate(String alias) {
		this(DSL.name(alias), TBLCANDIDATE);
	}

	/**
	 * Create an aliased <code>tblcandidate</code> table reference
	 */
	public Tblcandidate(Name alias) {
		this(alias, TBLCANDIDATE);
	}

	/**
	 * Create a <code>tblcandidate</code> table reference
	 */
	public Tblcandidate() {
		this(DSL.name("tblcandidate"), null);
	}

	public <O extends Record> Tblcandidate(Table<O> path, ForeignKey<O, TblcandidateRecord> childPath,
			InverseForeignKey<O, TblcandidateRecord> parentPath) {
		super(path, childPath, parentPath, TBLCANDIDATE);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class TblcandidatePath extends Tblcandidate implements Path<TblcandidateRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> TblcandidatePath(Table<O> path, ForeignKey<O, TblcandidateRecord> childPath,
				InverseForeignKey<O, TblcandidateRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private TblcandidatePath(Name alias, Table<TblcandidateRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public TblcandidatePath as(String alias) {
			return new TblcandidatePath(DSL.name(alias), this);
		}

		@Override
		public TblcandidatePath as(Name alias) {
			return new TblcandidatePath(alias, this);
		}

		@Override
		public TblcandidatePath as(Table<?> alias) {
			return new TblcandidatePath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.TBLCANDIDATE_ACCOUNT_DELETED, Indexes.TBLCANDIDATE_ACCOUNT_EMAIL,
				Indexes.TBLCANDIDATE_ACCOUNT_SRNO, Indexes.TBLCANDIDATE_ACCOUNTID_EMAIL,
				Indexes.TBLCANDIDATE_ACCOUNTIDUPDATEDONINDEX, Indexes.TBLCANDIDATE_AUTH_ID_IDX,
				Indexes.TBLCANDIDATE_CONTACTNUMBER_IDX, Indexes.TBLCANDIDATE_FK_TBLCANDIDATE_TBLACCOUNT_IDX,
				Indexes.TBLCANDIDATE_FK_TBLCANDIDATE_TBLCURRENCY_IDX,
				Indexes.TBLCANDIDATE_FK_TBLCANDIDATE_TBLGENDER_IDX,
				Indexes.TBLCANDIDATE_FK_TBLCANDIDATE_TBLQUALIFICATIONS_IDX,
				Indexes.TBLCANDIDATE_FK_TBLCANDIDATE_TBLUSER_IDX, Indexes.TBLCANDIDATE_FORMATTED_CONTACT_NUMBER_IDX,
				Indexes.TBLCANDIDATE_IDX_CANDIDATE_FILTER_SORT, Indexes.TBLCANDIDATE_IDX_FORMATTED_PROFILE_LINKEDIN,
				Indexes.TBLCANDIDATE_IDX_LNG_LAT, Indexes.TBLCANDIDATE_IMPORT_FUNCTION,
				Indexes.TBLCANDIDATE_MIGRATION_RESERVED1, Indexes.TBLCANDIDATE_NAMEINDEX,
				Indexes.TBLCANDIDATE_SOURCE_ACCOUNT_IDX, Indexes.TBLCANDIDATE_SOVERN_IDX,
				Indexes.TBLCANDIDATE_SOVREN_IDX, Indexes.TBLCANDIDATE_TEST, Indexes.TBLCANDIDATE_TEXT1);
	}

	@Override
	public Identity<TblcandidateRecord, Integer> getIdentity() {
		return (Identity<TblcandidateRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<TblcandidateRecord> getPrimaryKey() {
		return Keys.KEY_TBLCANDIDATE_PRIMARY;
	}

	@Override
	public List<UniqueKey<TblcandidateRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_TBLCANDIDATE_SLUG_UNIQUE);
	}

	@Override
	public List<ForeignKey<TblcandidateRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_TBLCANDIDATE_TBLCURRENCY, Keys.FK_TBLCANDIDATE_TBLGENDER,
				Keys.FK_TBLCANDIDATE_TBLUSER);
	}

	private transient TblcurrencyPath _tblcurrency;

	/**
	 * Get the implicit join path to the <code>tblcurrency</code> table.
	 */
	public TblcurrencyPath tblcurrency() {
		if (_tblcurrency == null)
			_tblcurrency = new TblcurrencyPath(this, Keys.FK_TBLCANDIDATE_TBLCURRENCY, null);

		return _tblcurrency;
	}

	private transient TblgenderPath _tblgender;

	/**
	 * Get the implicit join path to the <code>tblgender</code> table.
	 */
	public TblgenderPath tblgender() {
		if (_tblgender == null)
			_tblgender = new TblgenderPath(this, Keys.FK_TBLCANDIDATE_TBLGENDER, null);

		return _tblgender;
	}

	private transient TbluserPath _tbluser;

	/**
	 * Get the implicit join path to the <code>tbluser</code> table.
	 */
	public TbluserPath tbluser() {
		if (_tbluser == null)
			_tbluser = new TbluserPath(this, Keys.FK_TBLCANDIDATE_TBLUSER, null);

		return _tbluser;
	}

	private transient CandidateLastActivitiesTPath _candidateLastActivitiesT;

	/**
	 * Get the implicit to-many join path to the <code>candidate_last_activities_t</code>
	 * table
	 */
	public CandidateLastActivitiesTPath candidateLastActivitiesT() {
		if (_candidateLastActivitiesT == null)
			_candidateLastActivitiesT = new CandidateLastActivitiesTPath(this, null,
					Keys.CANDIDATE_LAST_ACTIVITIES_T_IBFK_1.getInverseKey());

		return _candidateLastActivitiesT;
	}

	private transient CandidateCustomFieldsTPath _candidateCustomFieldsT;

	/**
	 * Get the implicit to-many join path to the <code>candidate_custom_fields_t</code>
	 * table
	 */
	public CandidateCustomFieldsTPath candidateCustomFieldsT() {
		if (_candidateCustomFieldsT == null)
			_candidateCustomFieldsT = new CandidateCustomFieldsTPath(this, null,
					Keys.FK_CUSTOM_FIELD_T_TBLCANDIDATE.getInverseKey());

		return _candidateCustomFieldsT;
	}

	private transient TblassignjobcandidatePath _tblassignjobcandidate;

	/**
	 * Get the implicit to-many join path to the <code>tblassignjobcandidate</code> table
	 */
	public TblassignjobcandidatePath tblassignjobcandidate() {
		if (_tblassignjobcandidate == null)
			_tblassignjobcandidate = new TblassignjobcandidatePath(this, null,
					Keys.FK_TBLASSIGNJOBCANDIDATE_TBLCANDIDATE.getInverseKey());

		return _tblassignjobcandidate;
	}

	private transient TbldealcandidatesPath _tbldealcandidates;

	/**
	 * Get the implicit to-many join path to the <code>tbldealcandidates</code> table
	 */
	public TbldealcandidatesPath tbldealcandidates() {
		if (_tbldealcandidates == null)
			_tbldealcandidates = new TbldealcandidatesPath(this, null,
					Keys.FK_TBLDEALCANDIDATES_TBLCANDIDATE.getInverseKey());

		return _tbldealcandidates;
	}

	@Override
	public Tblcandidate as(String alias) {
		return new Tblcandidate(DSL.name(alias), this);
	}

	@Override
	public Tblcandidate as(Name alias) {
		return new Tblcandidate(alias, this);
	}

	@Override
	public Tblcandidate as(Table<?> alias) {
		return new Tblcandidate(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tblcandidate rename(String name) {
		return new Tblcandidate(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tblcandidate rename(Name name) {
		return new Tblcandidate(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tblcandidate rename(Table<?> name) {
		return new Tblcandidate(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcandidate where(Condition condition) {
		return new Tblcandidate(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcandidate where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcandidate where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcandidate where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblcandidate where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblcandidate where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblcandidate where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblcandidate where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcandidate whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcandidate whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
