/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetSettingT.CstTimesheetSettingTPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcandidate.TblcandidatePath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbljob.TbljobPath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblcurrencyRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tblcurrency extends TableImpl<TblcurrencyRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>tblcurrency</code>
	 */
	public static final Tblcurrency TBLCURRENCY = new Tblcurrency();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TblcurrencyRecord> getRecordType() {
		return TblcurrencyRecord.class;
	}

	/**
	 * The column <code>tblcurrency.id</code>.
	 */
	public final TableField<TblcurrencyRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>tblcurrency.country</code>. Name of the country.
	 */
	public final TableField<TblcurrencyRecord, String> COUNTRY = createField(DSL.name("country"),
			SQLDataType.VARCHAR(100), this, "Name of the country.");

	/**
	 * The column <code>tblcurrency.currency</code>. Name of the Currency.
	 */
	public final TableField<TblcurrencyRecord, String> CURRENCY = createField(DSL.name("currency"),
			SQLDataType.VARCHAR(100), this, "Name of the Currency.");

	/**
	 * The column <code>tblcurrency.code</code>. Code of the company.
	 */
	public final TableField<TblcurrencyRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(25),
			this, "Code of the company.");

	/**
	 * The column <code>tblcurrency.symbol</code>. Symbol of the Country.
	 */
	public final TableField<TblcurrencyRecord, String> SYMBOL = createField(DSL.name("symbol"), SQLDataType.VARCHAR(25),
			this, "Symbol of the Country.");

	/**
	 * The column <code>tblcurrency.thousand_separator</code>. Thousand Separator for
	 * digits.
	 */
	public final TableField<TblcurrencyRecord, String> THOUSAND_SEPARATOR = createField(DSL.name("thousand_separator"),
			SQLDataType.VARCHAR(10), this, "Thousand Separator for digits.");

	/**
	 * The column <code>tblcurrency.decimal_separator</code>. Decimal separator for
	 * digits.
	 */
	public final TableField<TblcurrencyRecord, String> DECIMAL_SEPARATOR = createField(DSL.name("decimal_separator"),
			SQLDataType.VARCHAR(10), this, "Decimal separator for digits.");

	/**
	 * The column <code>tblcurrency.decimalcode</code>. Decimal in html code format.
	 */
	public final TableField<TblcurrencyRecord, String> DECIMALCODE = createField(DSL.name("decimalcode"),
			SQLDataType.VARCHAR(20), this, "Decimal in html code format.");

	private Tblcurrency(Name alias, Table<TblcurrencyRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Tblcurrency(Name alias, Table<TblcurrencyRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>tblcurrency</code> table reference
	 */
	public Tblcurrency(String alias) {
		this(DSL.name(alias), TBLCURRENCY);
	}

	/**
	 * Create an aliased <code>tblcurrency</code> table reference
	 */
	public Tblcurrency(Name alias) {
		this(alias, TBLCURRENCY);
	}

	/**
	 * Create a <code>tblcurrency</code> table reference
	 */
	public Tblcurrency() {
		this(DSL.name("tblcurrency"), null);
	}

	public <O extends Record> Tblcurrency(Table<O> path, ForeignKey<O, TblcurrencyRecord> childPath,
			InverseForeignKey<O, TblcurrencyRecord> parentPath) {
		super(path, childPath, parentPath, TBLCURRENCY);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class TblcurrencyPath extends Tblcurrency implements Path<TblcurrencyRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> TblcurrencyPath(Table<O> path, ForeignKey<O, TblcurrencyRecord> childPath,
				InverseForeignKey<O, TblcurrencyRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private TblcurrencyPath(Name alias, Table<TblcurrencyRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public TblcurrencyPath as(String alias) {
			return new TblcurrencyPath(DSL.name(alias), this);
		}

		@Override
		public TblcurrencyPath as(Name alias) {
			return new TblcurrencyPath(alias, this);
		}

		@Override
		public TblcurrencyPath as(Table<?> alias) {
			return new TblcurrencyPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<TblcurrencyRecord, Integer> getIdentity() {
		return (Identity<TblcurrencyRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<TblcurrencyRecord> getPrimaryKey() {
		return Keys.KEY_TBLCURRENCY_PRIMARY;
	}

	private transient CstTimesheetSettingTPath _fkBillCurrency;

	/**
	 * Get the implicit to-many join path to the <code>cst_timesheet_setting_t</code>
	 * table, via the <code>fk_bill_currency</code> key
	 */
	public CstTimesheetSettingTPath fkBillCurrency() {
		if (_fkBillCurrency == null)
			_fkBillCurrency = new CstTimesheetSettingTPath(this, null, Keys.FK_BILL_CURRENCY.getInverseKey());

		return _fkBillCurrency;
	}

	private transient CstTimesheetSettingTPath _fkPayCurrency;

	/**
	 * Get the implicit to-many join path to the <code>cst_timesheet_setting_t</code>
	 * table, via the <code>fk_pay_currency</code> key
	 */
	public CstTimesheetSettingTPath fkPayCurrency() {
		if (_fkPayCurrency == null)
			_fkPayCurrency = new CstTimesheetSettingTPath(this, null, Keys.FK_PAY_CURRENCY.getInverseKey());

		return _fkPayCurrency;
	}

	private transient TblcandidatePath _tblcandidate;

	/**
	 * Get the implicit to-many join path to the <code>tblcandidate</code> table
	 */
	public TblcandidatePath tblcandidate() {
		if (_tblcandidate == null)
			_tblcandidate = new TblcandidatePath(this, null, Keys.FK_TBLCANDIDATE_TBLCURRENCY.getInverseKey());

		return _tblcandidate;
	}

	private transient TbljobPath _tbljob;

	/**
	 * Get the implicit to-many join path to the <code>tbljob</code> table
	 */
	public TbljobPath tbljob() {
		if (_tbljob == null)
			_tbljob = new TbljobPath(this, null, Keys.FK_TBLJOB_TBLCURRENCY.getInverseKey());

		return _tbljob;
	}

	@Override
	public Tblcurrency as(String alias) {
		return new Tblcurrency(DSL.name(alias), this);
	}

	@Override
	public Tblcurrency as(Name alias) {
		return new Tblcurrency(alias, this);
	}

	@Override
	public Tblcurrency as(Table<?> alias) {
		return new Tblcurrency(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tblcurrency rename(String name) {
		return new Tblcurrency(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tblcurrency rename(Name name) {
		return new Tblcurrency(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tblcurrency rename(Table<?> name) {
		return new Tblcurrency(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcurrency where(Condition condition) {
		return new Tblcurrency(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcurrency where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcurrency where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcurrency where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblcurrency where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblcurrency where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblcurrency where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblcurrency where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcurrency whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblcurrency whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
