/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcandidate.TblcandidatePath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldeals.TbldealsPath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbldealcandidatesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tbldealcandidates extends TableImpl<TbldealcandidatesRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>tbldealcandidates</code>
	 */
	public static final Tbldealcandidates TBLDEALCANDIDATES = new Tbldealcandidates();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TbldealcandidatesRecord> getRecordType() {
		return TbldealcandidatesRecord.class;
	}

	/**
	 * The column <code>tbldealcandidates.id</code>.
	 */
	public final TableField<TbldealcandidatesRecord, UInteger> ID = createField(DSL.name("id"),
			SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

	/**
	 * The column <code>tbldealcandidates.dealid</code>.
	 */
	public final TableField<TbldealcandidatesRecord, Integer> DEALID = createField(DSL.name("dealid"),
			SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tbldealcandidates.candidateid</code>.
	 */
	public final TableField<TbldealcandidatesRecord, Integer> CANDIDATEID = createField(DSL.name("candidateid"),
			SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tbldealcandidates.candidateslug</code>.
	 */
	public final TableField<TbldealcandidatesRecord, String> CANDIDATESLUG = createField(DSL.name("candidateslug"),
			SQLDataType.VARCHAR(50).nullable(false), this, "");

	private Tbldealcandidates(Name alias, Table<TbldealcandidatesRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Tbldealcandidates(Name alias, Table<TbldealcandidatesRecord> aliased, Field<?>[] parameters,
			Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>tbldealcandidates</code> table reference
	 */
	public Tbldealcandidates(String alias) {
		this(DSL.name(alias), TBLDEALCANDIDATES);
	}

	/**
	 * Create an aliased <code>tbldealcandidates</code> table reference
	 */
	public Tbldealcandidates(Name alias) {
		this(alias, TBLDEALCANDIDATES);
	}

	/**
	 * Create a <code>tbldealcandidates</code> table reference
	 */
	public Tbldealcandidates() {
		this(DSL.name("tbldealcandidates"), null);
	}

	public <O extends Record> Tbldealcandidates(Table<O> path, ForeignKey<O, TbldealcandidatesRecord> childPath,
			InverseForeignKey<O, TbldealcandidatesRecord> parentPath) {
		super(path, childPath, parentPath, TBLDEALCANDIDATES);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class TbldealcandidatesPath extends Tbldealcandidates implements Path<TbldealcandidatesRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> TbldealcandidatesPath(Table<O> path, ForeignKey<O, TbldealcandidatesRecord> childPath,
				InverseForeignKey<O, TbldealcandidatesRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private TbldealcandidatesPath(Name alias, Table<TbldealcandidatesRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public TbldealcandidatesPath as(String alias) {
			return new TbldealcandidatesPath(DSL.name(alias), this);
		}

		@Override
		public TbldealcandidatesPath as(Name alias) {
			return new TbldealcandidatesPath(alias, this);
		}

		@Override
		public TbldealcandidatesPath as(Table<?> alias) {
			return new TbldealcandidatesPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.TBLDEALCANDIDATES_CANDIDATEID, Indexes.TBLDEALCANDIDATES_DEALID);
	}

	@Override
	public Identity<TbldealcandidatesRecord, UInteger> getIdentity() {
		return (Identity<TbldealcandidatesRecord, UInteger>) super.getIdentity();
	}

	@Override
	public UniqueKey<TbldealcandidatesRecord> getPrimaryKey() {
		return Keys.KEY_TBLDEALCANDIDATES_PRIMARY;
	}

	@Override
	public List<ForeignKey<TbldealcandidatesRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_TBLDEALCANDIDATES_TBLCANDIDATE, Keys.FK_TBLDEALCANDIDATES_TBLDEALS);
	}

	private transient TblcandidatePath _tblcandidate;

	/**
	 * Get the implicit join path to the <code>tblcandidate</code> table.
	 */
	public TblcandidatePath tblcandidate() {
		if (_tblcandidate == null)
			_tblcandidate = new TblcandidatePath(this, Keys.FK_TBLDEALCANDIDATES_TBLCANDIDATE, null);

		return _tblcandidate;
	}

	private transient TbldealsPath _tbldeals;

	/**
	 * Get the implicit join path to the <code>tbldeals</code> table.
	 */
	public TbldealsPath tbldeals() {
		if (_tbldeals == null)
			_tbldeals = new TbldealsPath(this, Keys.FK_TBLDEALCANDIDATES_TBLDEALS, null);

		return _tbldeals;
	}

	@Override
	public Tbldealcandidates as(String alias) {
		return new Tbldealcandidates(DSL.name(alias), this);
	}

	@Override
	public Tbldealcandidates as(Name alias) {
		return new Tbldealcandidates(alias, this);
	}

	@Override
	public Tbldealcandidates as(Table<?> alias) {
		return new Tbldealcandidates(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tbldealcandidates rename(String name) {
		return new Tbldealcandidates(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tbldealcandidates rename(Name name) {
		return new Tbldealcandidates(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tbldealcandidates rename(Table<?> name) {
		return new Tbldealcandidates(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbldealcandidates where(Condition condition) {
		return new Tbldealcandidates(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbldealcandidates where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbldealcandidates where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbldealcandidates where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbldealcandidates where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbldealcandidates where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbldealcandidates where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbldealcandidates where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbldealcandidates whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbldealcandidates whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
