/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcandidate.TblcandidatePath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblgenderRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tblgender extends TableImpl<TblgenderRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>tblgender</code>
	 */
	public static final Tblgender TBLGENDER = new Tblgender();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TblgenderRecord> getRecordType() {
		return TblgenderRecord.class;
	}

	/**
	 * The column <code>tblgender.id</code>. Primary key for the table.
	 */
	public final TableField<TblgenderRecord, Byte> ID = createField(DSL.name("id"), SQLDataType.TINYINT.nullable(false),
			this, "Primary key for the table.");

	/**
	 * The column <code>tblgender.label</code>. Label for the gender.
	 */
	public final TableField<TblgenderRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(50),
			this, "Label for the gender.");

	/**
	 * The column <code>tblgender.checkcdc</code>.
	 */
	public final TableField<TblgenderRecord, String> CHECKCDC = createField(DSL.name("checkcdc"),
			SQLDataType.VARCHAR(100).defaultValue(DSL.inline("hii", SQLDataType.VARCHAR)), this, "");

	private Tblgender(Name alias, Table<TblgenderRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Tblgender(Name alias, Table<TblgenderRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>tblgender</code> table reference
	 */
	public Tblgender(String alias) {
		this(DSL.name(alias), TBLGENDER);
	}

	/**
	 * Create an aliased <code>tblgender</code> table reference
	 */
	public Tblgender(Name alias) {
		this(alias, TBLGENDER);
	}

	/**
	 * Create a <code>tblgender</code> table reference
	 */
	public Tblgender() {
		this(DSL.name("tblgender"), null);
	}

	public <O extends Record> Tblgender(Table<O> path, ForeignKey<O, TblgenderRecord> childPath,
			InverseForeignKey<O, TblgenderRecord> parentPath) {
		super(path, childPath, parentPath, TBLGENDER);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class TblgenderPath extends Tblgender implements Path<TblgenderRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> TblgenderPath(Table<O> path, ForeignKey<O, TblgenderRecord> childPath,
				InverseForeignKey<O, TblgenderRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private TblgenderPath(Name alias, Table<TblgenderRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public TblgenderPath as(String alias) {
			return new TblgenderPath(DSL.name(alias), this);
		}

		@Override
		public TblgenderPath as(Name alias) {
			return new TblgenderPath(alias, this);
		}

		@Override
		public TblgenderPath as(Table<?> alias) {
			return new TblgenderPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<TblgenderRecord> getPrimaryKey() {
		return Keys.KEY_TBLGENDER_PRIMARY;
	}

	@Override
	public List<UniqueKey<TblgenderRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_TBLGENDER_LABEL);
	}

	private transient TblcandidatePath _tblcandidate;

	/**
	 * Get the implicit to-many join path to the <code>tblcandidate</code> table
	 */
	public TblcandidatePath tblcandidate() {
		if (_tblcandidate == null)
			_tblcandidate = new TblcandidatePath(this, null, Keys.FK_TBLCANDIDATE_TBLGENDER.getInverseKey());

		return _tblcandidate;
	}

	@Override
	public Tblgender as(String alias) {
		return new Tblgender(DSL.name(alias), this);
	}

	@Override
	public Tblgender as(Name alias) {
		return new Tblgender(alias, this);
	}

	@Override
	public Tblgender as(Table<?> alias) {
		return new Tblgender(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tblgender rename(String name) {
		return new Tblgender(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tblgender rename(Name name) {
		return new Tblgender(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tblgender rename(Table<?> name) {
		return new Tblgender(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblgender where(Condition condition) {
		return new Tblgender(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblgender where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblgender where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblgender where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblgender where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblgender where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblgender where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tblgender where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblgender whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tblgender whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
