/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.JobSecondaryContactsT.JobSecondaryContactsTPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblassignjobcandidate.TblassignjobcandidatePath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcompany.TblcompanyPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcontact.TblcontactPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcurrency.TblcurrencyPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldealjobs.TbldealjobsPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbljobstatus.TbljobstatusPath;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbluser.TbluserPath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbljobRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tbljob extends TableImpl<TbljobRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>tbljob</code>
	 */
	public static final Tbljob TBLJOB = new Tbljob();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TbljobRecord> getRecordType() {
		return TbljobRecord.class;
	}

	/**
	 * The column <code>tbljob.id</code>. Primary key for the table.
	 */
	public final TableField<TbljobRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "Primary key for the table.");

	/**
	 * The column <code>tbljob.srno</code>. This serial number is for user to identify the
	 * record by id. This value is generated account wise. There will be same srno for
	 * different accounts but not in same account.
	 */
	public final TableField<TbljobRecord, Integer> SRNO = createField(DSL.name("srno"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"This serial number is for user to identify the record by id. This value is generated account wise. There will be same srno for different accounts but not in same account.");

	/**
	 * The column <code>tbljob.name</code>.
	 */
	public final TableField<TbljobRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(300), this,
			"");

	/**
	 * The column <code>tbljob.description</code>. Short description of job/Note for
	 * candidate.
	 */
	public final TableField<TbljobRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB,
			this, "Short description of job/Note for candidate.");

	/**
	 * The column <code>tbljob.qualificationid</code>. Required qualification for job
	 * Reference.
	 */
	public final TableField<TbljobRecord, Integer> QUALIFICATIONID = createField(DSL.name("qualificationid"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Required qualification for job Reference.");

	/**
	 * The column <code>tbljob.specialization</code>. Educational specialization for job.
	 */
	public final TableField<TbljobRecord, String> SPECIALIZATION = createField(DSL.name("specialization"),
			SQLDataType.VARCHAR(300), this, "Educational specialization for job.");

	/**
	 * The column <code>tbljob.minexperienceinyears</code>. Minimum Experience for the Job
	 */
	public final TableField<TbljobRecord, Byte> MINEXPERIENCEINYEARS = createField(DSL.name("minexperienceinyears"),
			SQLDataType.TINYINT, this, "Minimum Experience for the Job");

	/**
	 * The column <code>tbljob.maxexperienceinyears</code>. Maximum Experience for the Job
	 */
	public final TableField<TbljobRecord, Byte> MAXEXPERIENCEINYEARS = createField(DSL.name("maxexperienceinyears"),
			SQLDataType.TINYINT, this, "Maximum Experience for the Job");

	/**
	 * The column <code>tbljob.annualsalarymin</code>. Minimum annual salary required for
	 * the job.
	 */
	public final TableField<TbljobRecord, Double> ANNUALSALARYMIN = createField(DSL.name("annualsalarymin"),
			SQLDataType.DOUBLE.nullable(false).defaultValue(DSL.inline("0.00", SQLDataType.DOUBLE)), this,
			"Minimum annual salary required for the job.");

	/**
	 * The column <code>tbljob.annualsalarymax</code>. Maximum annual salary required for
	 * the job.
	 */
	public final TableField<TbljobRecord, Double> ANNUALSALARYMAX = createField(DSL.name("annualsalarymax"),
			SQLDataType.DOUBLE.nullable(false).defaultValue(DSL.inline("0.00", SQLDataType.DOUBLE)), this,
			"Maximum annual salary required for the job.");

	/**
	 * The column <code>tbljob.noofopenings</code>. Number of opening for the job.
	 */
	public final TableField<TbljobRecord, Short> NOOFOPENINGS = createField(DSL.name("noofopenings"),
			SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.SMALLINT)), this,
			"Number of opening for the job.");

	/**
	 * The column <code>tbljob.jobstatus</code>. Current status ID of the job.\nReference
	 * - tbljobstatus
	 */
	public final TableField<TbljobRecord, Integer> JOBSTATUS = createField(DSL.name("jobstatus"),
			SQLDataType.INTEGER.defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this,
			"Current status ID of the job.\\nReference - tbljobstatus");

	/**
	 * The column <code>tbljob.companyid</code>. Company ID for which job is created.
	 * Reference - tblcompany
	 */
	public final TableField<TbljobRecord, Integer> COMPANYID = createField(DSL.name("companyid"), SQLDataType.INTEGER,
			this, "Company ID for which job is created.\nReference - tblcompany");

	/**
	 * The column <code>tbljob.contactid</code>. Responsible company contact for the job.
	 * Reference - tblcontact
	 */
	public final TableField<TbljobRecord, Integer> CONTACTID = createField(DSL.name("contactid"), SQLDataType.INTEGER,
			this, "Responsible company contact for the job.\nReference - tblcontact");

	/**
	 * The column <code>tbljob.currencyid</code>. Currency of salary for the job.
	 * Reference - tblcurrency
	 */
	public final TableField<TbljobRecord, Integer> CURRENCYID = createField(DSL.name("currencyid"), SQLDataType.INTEGER,
			this, "Currency of salary for the job.\nReference - tblcurrency");

	/**
	 * The column <code>tbljob.slug</code>. Unique value generated using trigger.
	 */
	public final TableField<TbljobRecord, String> SLUG = createField(DSL.name("slug"), SQLDataType.VARCHAR(90), this,
			"Unique value generated using trigger.");

	/**
	 * The column <code>tbljob.allowapply</code>. This setting is used to check where
	 * external application need to except or not.
	 */
	public final TableField<TbljobRecord, Byte> ALLOWAPPLY = createField(DSL.name("allowapply"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"This setting is used to check where external application need to except or not.");

	/**
	 * The column <code>tbljob.jdtext</code>. Job description text for this job in html
	 * format.
	 */
	public final TableField<TbljobRecord, String> JDTEXT = createField(DSL.name("jdtext"), SQLDataType.CLOB, this,
			"Job description text for this job in html format.");

	/**
	 * The column <code>tbljob.details</code>. URL for Job description file.
	 */
	public final TableField<TbljobRecord, String> DETAILS = createField(DSL.name("details"), SQLDataType.VARCHAR(300),
			this, "URL for Job description file.");

	/**
	 * The column <code>tbljob.detailfilename</code>. Job description file name.
	 */
	public final TableField<TbljobRecord, String> DETAILFILENAME = createField(DSL.name("detailfilename"),
			SQLDataType.VARCHAR(300), this, "Job description file name.");

	/**
	 * The column <code>tbljob.deleted</code>.
	 */
	public final TableField<TbljobRecord, Byte> DELETED = createField(DSL.name("deleted"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

	/**
	 * The column <code>tbljob.collaborator</code>. Comma separated ids of user who are
	 * also working on this job.
	 */
	public final TableField<TbljobRecord, String> COLLABORATOR = createField(DSL.name("collaborator"),
			SQLDataType.VARCHAR(100), this, "Comma separated ids of user who are also working on this job.");

	/**
	 * The column <code>tbljob.authid</code>.
	 */
	public final TableField<TbljobRecord, String> AUTHID = createField(DSL.name("authid"), SQLDataType.VARCHAR(100),
			this, "");

	/**
	 * The column <code>tbljob.ownerid</code>. User id who owns that record. Reference -
	 * tbluser
	 */
	public final TableField<TbljobRecord, Integer> OWNERID = createField(DSL.name("ownerid"), SQLDataType.INTEGER, this,
			"User id who owns that record.\nReference - tbluser");

	/**
	 * The column <code>tbljob.accountid</code>. Account id, for which, the job is
	 * associated. Reference - tblaccount
	 */
	public final TableField<TbljobRecord, Integer> ACCOUNTID = createField(DSL.name("accountid"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Account id, for which, the job is associated.\nReference - tblaccount");

	/**
	 * The column <code>tbljob.createdby</code>. User id who created the record.
	 */
	public final TableField<TbljobRecord, Integer> CREATEDBY = createField(DSL.name("createdby"),
			SQLDataType.INTEGER.nullable(false), this, "User id who created the record.");

	/**
	 * The column <code>tbljob.createdon</code>. Timestamp when record added.
	 */
	public final TableField<TbljobRecord, Integer> CREATEDON = createField(DSL.name("createdon"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Timestamp when record added.");

	/**
	 * The column <code>tbljob.updatedby</code>. User id who updated the record.
	 */
	public final TableField<TbljobRecord, Integer> UPDATEDBY = createField(DSL.name("updatedby"),
			SQLDataType.INTEGER.nullable(false), this, "User id who updated the record.");

	/**
	 * The column <code>tbljob.updatedon</code>. Timestamp when record updated.
	 */
	public final TableField<TbljobRecord, Integer> UPDATEDON = createField(DSL.name("updatedon"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Timestamp when record updated.");

	/**
	 * The column <code>tbljob.jobpostingdate</code>. Timestamp when job is posted to
	 * external job boards.
	 */
	public final TableField<TbljobRecord, Integer> JOBPOSTINGDATE = createField(DSL.name("jobpostingdate"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Timestamp when job is posted to external job boards.");

	/**
	 * The column <code>tbljob.locality</code>. Location of the job.
	 */
	public final TableField<TbljobRecord, String> LOCALITY = createField(DSL.name("locality"),
			SQLDataType.VARCHAR(100).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "Location of the job.");

	/**
	 * The column <code>tbljob.city</code>. City of the job.
	 */
	public final TableField<TbljobRecord, String> CITY = createField(DSL.name("city"),
			SQLDataType.VARCHAR(50).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "City of the job.");

	/**
	 * The column <code>tbljob.lat</code>. Latitude - Used for radius search.
	 */
	public final TableField<TbljobRecord, Integer> LAT = createField(DSL.name("lat"),
			SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Latitude - Used for radius search.");

	/**
	 * The column <code>tbljob.lng</code>. Longitude - Used for radius search.
	 */
	public final TableField<TbljobRecord, Integer> LNG = createField(DSL.name("lng"),
			SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Longitude - Used for radius search.");

	/**
	 * The column <code>tbljob.address</code>. Full address of the job.
	 */
	public final TableField<TbljobRecord, String> ADDRESS = createField(DSL.name("address"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this,
			"Full address of the job.");

	/**
	 * The column <code>tbljob.state</code>. State of the job.
	 */
	public final TableField<TbljobRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(50), this,
			"State of the job.");

	/**
	 * The column <code>tbljob.country</code>. Country of the job.
	 */
	public final TableField<TbljobRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.VARCHAR(50),
			this, "Country of the job.");

	/**
	 * The column <code>tbljob.jobpostingstatus</code>. To check the job post status on
	 * external job boards.\\\\\\\\n1 - Job In Review\\\\\\\\n2 - \\\\\\\\n3 -
	 * Rejected\\\\\\\\n4 - Posted\\\\\\\\n
	 */
	public final TableField<TbljobRecord, Integer> JOBPOSTINGSTATUS = createField(DSL.name("jobpostingstatus"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this,
			"To check the job post status on external job boards.\\\\\\\\\\\\\\\\n1 - Job In Review\\\\\\\\\\\\\\\\n2 - \\\\\\\\\\\\\\\\n3 - Rejected\\\\\\\\\\\\\\\\n4 - Posted\\\\\\\\\\\\\\\\n");

	/**
	 * The column <code>tbljob.jobcode</code>. Random code generated in trigger.
	 */
	public final TableField<TbljobRecord, String> JOBCODE = createField(DSL.name("jobcode"), SQLDataType.VARCHAR(10),
			this, "Random code generated in trigger.");

	/**
	 * The column <code>tbljob.showcompany</code>. This setting is used to show/hide
	 * company on external job page.
	 */
	public final TableField<TbljobRecord, Byte> SHOWCOMPANY = createField(DSL.name("showcompany"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this,
			"This setting is used to show/hide company on external job page.");

	/**
	 * The column <code>tbljob.showaccountname</code>. This setting is used to show/hide
	 * account name on external job page.
	 */
	public final TableField<TbljobRecord, Byte> SHOWACCOUNTNAME = createField(DSL.name("showaccountname"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"This setting is used to show/hide account name on external job page.");

	/**
	 * The column <code>tbljob.canaccess</code>. User ids who is not owner and not having
	 * full access but need to see the record (comma separated).
	 */
	public final TableField<TbljobRecord, String> CANACCESS = createField(DSL.name("canaccess"), SQLDataType.CLOB, this,
			"User ids who is not owner and not having full access but need to see the record (comma separated).");

	/**
	 * The column <code>tbljob.salarytype</code>. Salary type of job(Annually, Monthly,
	 * weekly).
	 */
	public final TableField<TbljobRecord, String> SALARYTYPE = createField(DSL.name("salarytype"),
			SQLDataType.VARCHAR(30), this, "Salary type of job(Annually, Monthly, weekly).");

	/**
	 * The column <code>tbljob.jobstatuscomment</code>. Any comment while changing job
	 * status.
	 */
	public final TableField<TbljobRecord, String> JOBSTATUSCOMMENT = createField(DSL.name("jobstatuscomment"),
			SQLDataType.CLOB, this, "Any comment while changing job status.");

	/**
	 * The column <code>tbljob.jobquestions</code>. Questions related to this job. These
	 * question are asked on the external job application form.
	 */
	public final TableField<TbljobRecord, String> JOBQUESTIONS = createField(DSL.name("jobquestions"),
			SQLDataType.VARCHAR(512), this,
			"Questions related to this job. These question are asked on the external job application form. ");

	/**
	 * The column <code>tbljob.sharecandidatefields</code>. Fields shared with contact on
	 * external submit candidate page. If this is empty, fields shared with client will be
	 * used on account level.
	 */
	public final TableField<TbljobRecord, String> SHARECANDIDATEFIELDS = createField(DSL.name("sharecandidatefields"),
			SQLDataType.CLOB, this,
			"Fields shared with contact on external submit candidate page. If this is empty, fields shared with client will be used on account level.");

	/**
	 * The column <code>tbljob.submitcandidateemailsenton</code>. Timestamp when last
	 * email sent for submit candidates.
	 */
	public final TableField<TbljobRecord, Integer> SUBMITCANDIDATEEMAILSENTON = createField(
			DSL.name("submitcandidateemailsenton"),
			SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this,
			"Timestamp when last email sent for submit candidates.");

	/**
	 * The column <code>tbljob.cvljobpostingid</code>.
	 */
	public final TableField<TbljobRecord, Long> CVLJOBPOSTINGID = createField(DSL.name("cvljobpostingid"),
			SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>tbljob.sourceid</code>.
	 */
	public final TableField<TbljobRecord, Integer> SOURCEID = createField(DSL.name("sourceid"), SQLDataType.INTEGER,
			this, "");

	/**
	 * The column <code>tbljob.migration_reserved1</code>.
	 */
	public final TableField<TbljobRecord, String> MIGRATION_RESERVED1 = createField(DSL.name("migration_reserved1"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>tbljob.migration_reserved2</code>.
	 */
	public final TableField<TbljobRecord, String> MIGRATION_RESERVED2 = createField(DSL.name("migration_reserved2"),
			SQLDataType.VARCHAR(500).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>tbljob.hiring_pipeline_id</code>.
	 */
	public final TableField<TbljobRecord, Integer> HIRING_PIPELINE_ID = createField(DSL.name("hiring_pipeline_id"),
			SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tbljob.archived</code>.
	 */
	public final TableField<TbljobRecord, UByte> ARCHIVED = createField(DSL.name("archived"),
			SQLDataType.TINYINTUNSIGNED.defaultValue(DSL.inline("0", SQLDataType.TINYINTUNSIGNED)), this, "");

	/**
	 * The column <code>tbljob.job_type</code>.
	 */
	public final TableField<TbljobRecord, String> JOB_TYPE = createField(DSL.name("job_type"), SQLDataType.VARCHAR(20),
			this, "");

	/**
	 * The column <code>tbljob.job_category</code>.
	 */
	public final TableField<TbljobRecord, String> JOB_CATEGORY = createField(DSL.name("job_category"),
			SQLDataType.VARCHAR(100), this, "");

	/**
	 * The column <code>tbljob.mapped_pending_job_id</code>. null - not mapped, 1 - mapped
	 */
	public final TableField<TbljobRecord, Integer> MAPPED_PENDING_JOB_ID = createField(
			DSL.name("mapped_pending_job_id"), SQLDataType.INTEGER, this, "null - not mapped, 1 - mapped");

	/**
	 * The column <code>tbljob.closed_logicmelon_advert</code>. This flag is indicate that
	 * closed or archived advert at logimelon application
	 */
	public final TableField<TbljobRecord, Byte> CLOSED_LOGICMELON_ADVERT = createField(
			DSL.name("closed_logicmelon_advert"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this,
			"This flag is indicate that closed or archived advert at logimelon application");

	/**
	 * The column <code>tbljob.enable_vms_link</code>.
	 */
	public final TableField<TbljobRecord, Byte> ENABLE_VMS_LINK = createField(DSL.name("enable_vms_link"),
			SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

	/**
	 * The column <code>tbljob.job_skill</code>.
	 */
	public final TableField<TbljobRecord, String> JOB_SKILL = createField(DSL.name("job_skill"), SQLDataType.CLOB, this,
			"");

	/**
	 * The column <code>tbljob.kanban_visible_fields</code>.
	 */
	public final TableField<TbljobRecord, String> KANBAN_VISIBLE_FIELDS = createField(DSL.name("kanban_visible_fields"),
			SQLDataType.CLOB, this, "");

	/**
	 * The column <code>tbljob.remote</code>. Job Location Type field
	 */
	public final TableField<TbljobRecord, String> REMOTE = createField(DSL.name("remote"), SQLDataType.VARCHAR(2), this,
			"Job Location Type field");

	/**
	 * The column <code>tbljob.job_document_id</code>. Column to store job sovren document
	 * id
	 */
	public final TableField<TbljobRecord, String> JOB_DOCUMENT_ID = createField(DSL.name("job_document_id"),
			SQLDataType.VARCHAR(200), this, "Column to store job sovren document id");

	/**
	 * The column <code>tbljob.postalcode</code>. postal code field for job
	 */
	public final TableField<TbljobRecord, String> POSTALCODE = createField(DSL.name("postalcode"),
			SQLDataType.VARCHAR(20), this, "postal code field for job");

	/**
	 * The column <code>tbljob.merge_flag</code>. To store the Merge Flag
	 */
	public final TableField<TbljobRecord, Byte> MERGE_FLAG = createField(DSL.name("merge_flag"),
			SQLDataType.TINYINT.defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "To store the Merge Flag");

	/**
	 * The column <code>tbljob.job_online_candidate_list_passcode</code>. Online Candidate
	 * List Passcode at Job Level
	 */
	public final TableField<TbljobRecord, String> JOB_ONLINE_CANDIDATE_LIST_PASSCODE = createField(
			DSL.name("job_online_candidate_list_passcode"), SQLDataType.VARCHAR(13), this,
			"Online Candidate List Passcode at Job Level");

	/**
	 * The column <code>tbljob.pay_rate_dep</code>. Pay rate for the job
	 */
	public final TableField<TbljobRecord, BigDecimal> PAY_RATE_DEP = createField(DSL.name("pay_rate_dep"),
			SQLDataType.DECIMAL(65, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this,
			"Pay rate for the job");

	/**
	 * The column <code>tbljob.bill_rate_dep</code>. Bill rate for the job
	 */
	public final TableField<TbljobRecord, BigDecimal> BILL_RATE_DEP = createField(DSL.name("bill_rate_dep"),
			SQLDataType.DECIMAL(65, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this,
			"Bill rate for the job");

	/**
	 * The column <code>tbljob.pay_rate</code>. Pay rate for the job
	 */
	public final TableField<TbljobRecord, Double> PAY_RATE = createField(DSL.name("pay_rate"),
			SQLDataType.DOUBLE.defaultValue(DSL.inline("0.00", SQLDataType.DOUBLE)), this, "Pay rate for the job");

	/**
	 * The column <code>tbljob.bill_rate</code>. Bill rate for the job
	 */
	public final TableField<TbljobRecord, Double> BILL_RATE = createField(DSL.name("bill_rate"),
			SQLDataType.DOUBLE.defaultValue(DSL.inline("0.00", SQLDataType.DOUBLE)), this, "Bill rate for the job");

	/**
	 * The column <code>tbljob.job_function</code>. Job function for Organic Posting
	 * Network (OPN)
	 */
	public final TableField<TbljobRecord, String> JOB_FUNCTION = createField(DSL.name("job_function"),
			SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this,
			"Job function for Organic Posting Network (OPN)");

	/**
	 * The column <code>tbljob.job_industry</code>. Job industry for Organic Posting
	 * Network (OPN)
	 */
	public final TableField<TbljobRecord, String> JOB_INDUSTRY = createField(DSL.name("job_industry"),
			SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this,
			"Job industry for Organic Posting Network (OPN)");

	/**
	 * The column <code>tbljob.last_posted_on_opn</code>. Unix timestamp of when the job
	 * was last posted on the Organic Posting Network (OPN)
	 */
	public final TableField<TbljobRecord, Integer> LAST_POSTED_ON_OPN = createField(DSL.name("last_posted_on_opn"),
			SQLDataType.INTEGER, this,
			"Unix timestamp of when the job was last posted on the Organic Posting Network (OPN)");

	private Tbljob(Name alias, Table<TbljobRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Tbljob(Name alias, Table<TbljobRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>tbljob</code> table reference
	 */
	public Tbljob(String alias) {
		this(DSL.name(alias), TBLJOB);
	}

	/**
	 * Create an aliased <code>tbljob</code> table reference
	 */
	public Tbljob(Name alias) {
		this(alias, TBLJOB);
	}

	/**
	 * Create a <code>tbljob</code> table reference
	 */
	public Tbljob() {
		this(DSL.name("tbljob"), null);
	}

	public <O extends Record> Tbljob(Table<O> path, ForeignKey<O, TbljobRecord> childPath,
			InverseForeignKey<O, TbljobRecord> parentPath) {
		super(path, childPath, parentPath, TBLJOB);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class TbljobPath extends Tbljob implements Path<TbljobRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> TbljobPath(Table<O> path, ForeignKey<O, TbljobRecord> childPath,
				InverseForeignKey<O, TbljobRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private TbljobPath(Name alias, Table<TbljobRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public TbljobPath as(String alias) {
			return new TbljobPath(DSL.name(alias), this);
		}

		@Override
		public TbljobPath as(Name alias) {
			return new TbljobPath(alias, this);
		}

		@Override
		public TbljobPath as(Table<?> alias) {
			return new TbljobPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.TBLJOB_ACCOUNT_SRNO, Indexes.TBLJOB_ACCOUNTID_SRNO, Indexes.TBLJOB_AUTH_IDX,
				Indexes.TBLJOB_AUTHID, Indexes.TBLJOB_FK_TBLJOB_TBLCOMPANY_IDX, Indexes.TBLJOB_FK_TBLJOB_TBLCONTACT_IDX,
				Indexes.TBLJOB_FK_TBLJOB_TBLCURRENCY_IDX, Indexes.TBLJOB_FK_TBLJOB_TBLJOBSTATUS_IDX,
				Indexes.TBLJOB_FK_TBLJOB_TBLQUALIFICATIONS_IDX, Indexes.TBLJOB_FK_TBLJOB_TBLUSER_IDX,
				Indexes.TBLJOB_HIRING_PIPELINE_ID_ACCOUNTID, Indexes.TBLJOB_IDX_JOB_AUTHID,
				Indexes.TBLJOB_IDX_JOB_JOB_CODE, Indexes.TBLJOB_TEST);
	}

	@Override
	public Identity<TbljobRecord, Integer> getIdentity() {
		return (Identity<TbljobRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<TbljobRecord> getPrimaryKey() {
		return Keys.KEY_TBLJOB_PRIMARY;
	}

	@Override
	public List<UniqueKey<TbljobRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_TBLJOB_JOBSLUG);
	}

	@Override
	public List<ForeignKey<TbljobRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_TBLJOB_TBLCOMPANY, Keys.FK_TBLJOB_TBLCONTACT, Keys.FK_TBLJOB_TBLCURRENCY,
				Keys.FK_TBLJOB_TBLJOBSTATUS, Keys.FK_TBLJOB_TBLUSER);
	}

	private transient TblcompanyPath _tblcompany;

	/**
	 * Get the implicit join path to the <code>tblcompany</code> table.
	 */
	public TblcompanyPath tblcompany() {
		if (_tblcompany == null)
			_tblcompany = new TblcompanyPath(this, Keys.FK_TBLJOB_TBLCOMPANY, null);

		return _tblcompany;
	}

	private transient TblcontactPath _tblcontact;

	/**
	 * Get the implicit join path to the <code>tblcontact</code> table.
	 */
	public TblcontactPath tblcontact() {
		if (_tblcontact == null)
			_tblcontact = new TblcontactPath(this, Keys.FK_TBLJOB_TBLCONTACT, null);

		return _tblcontact;
	}

	private transient TblcurrencyPath _tblcurrency;

	/**
	 * Get the implicit join path to the <code>tblcurrency</code> table.
	 */
	public TblcurrencyPath tblcurrency() {
		if (_tblcurrency == null)
			_tblcurrency = new TblcurrencyPath(this, Keys.FK_TBLJOB_TBLCURRENCY, null);

		return _tblcurrency;
	}

	private transient TbljobstatusPath _tbljobstatus;

	/**
	 * Get the implicit join path to the <code>tbljobstatus</code> table.
	 */
	public TbljobstatusPath tbljobstatus() {
		if (_tbljobstatus == null)
			_tbljobstatus = new TbljobstatusPath(this, Keys.FK_TBLJOB_TBLJOBSTATUS, null);

		return _tbljobstatus;
	}

	private transient TbluserPath _tbluser;

	/**
	 * Get the implicit join path to the <code>tbluser</code> table.
	 */
	public TbluserPath tbluser() {
		if (_tbluser == null)
			_tbluser = new TbluserPath(this, Keys.FK_TBLJOB_TBLUSER, null);

		return _tbluser;
	}

	private transient JobSecondaryContactsTPath _jobSecondaryContactsT;

	/**
	 * Get the implicit to-many join path to the <code>job_secondary_contacts_t</code>
	 * table
	 */
	public JobSecondaryContactsTPath jobSecondaryContactsT() {
		if (_jobSecondaryContactsT == null)
			_jobSecondaryContactsT = new JobSecondaryContactsTPath(this, null,
					Keys.FK_JOBSECONDARYCONTACT_JOB.getInverseKey());

		return _jobSecondaryContactsT;
	}

	private transient TblassignjobcandidatePath _tblassignjobcandidate;

	/**
	 * Get the implicit to-many join path to the <code>tblassignjobcandidate</code> table
	 */
	public TblassignjobcandidatePath tblassignjobcandidate() {
		if (_tblassignjobcandidate == null)
			_tblassignjobcandidate = new TblassignjobcandidatePath(this, null,
					Keys.FK_TBLASSIGNJOBCANDIDATE_TBLJOB.getInverseKey());

		return _tblassignjobcandidate;
	}

	private transient TbldealjobsPath _tbldealjobs;

	/**
	 * Get the implicit to-many join path to the <code>tbldealjobs</code> table
	 */
	public TbldealjobsPath tbldealjobs() {
		if (_tbldealjobs == null)
			_tbldealjobs = new TbldealjobsPath(this, null, Keys.FK_TBLDEALJOBS_TBLJOB.getInverseKey());

		return _tbldealjobs;
	}

	@Override
	public Tbljob as(String alias) {
		return new Tbljob(DSL.name(alias), this);
	}

	@Override
	public Tbljob as(Name alias) {
		return new Tbljob(alias, this);
	}

	@Override
	public Tbljob as(Table<?> alias) {
		return new Tbljob(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tbljob rename(String name) {
		return new Tbljob(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tbljob rename(Name name) {
		return new Tbljob(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tbljob rename(Table<?> name) {
		return new Tbljob(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljob where(Condition condition) {
		return new Tbljob(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljob where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljob where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljob where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbljob where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbljob where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbljob where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbljob where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljob whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljob whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
