/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables;

import io.recruitcrm.microservice.search.models.jooq.DefaultSchema;
import io.recruitcrm.microservice.search.models.jooq.Indexes;
import io.recruitcrm.microservice.search.models.jooq.Keys;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbljob.TbljobPath;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbljobstatusRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tbljobstatus extends TableImpl<TbljobstatusRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>tbljobstatus</code>
	 */
	public static final Tbljobstatus TBLJOBSTATUS = new Tbljobstatus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TbljobstatusRecord> getRecordType() {
		return TbljobstatusRecord.class;
	}

	/**
	 * The column <code>tbljobstatus.id</code>.
	 */
	public final TableField<TbljobstatusRecord, Integer> ID = createField(DSL.name("id"),
			SQLDataType.INTEGER.nullable(false).identity(true), this, "");

	/**
	 * The column <code>tbljobstatus.label</code>.
	 */
	public final TableField<TbljobstatusRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(50),
			this, "");

	/**
	 * The column <code>tbljobstatus.accountid</code>.
	 */
	public final TableField<TbljobstatusRecord, Integer> ACCOUNTID = createField(DSL.name("accountid"),
			SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tbljobstatus.sequenceno</code>.
	 */
	public final TableField<TbljobstatusRecord, Integer> SEQUENCENO = createField(DSL.name("sequenceno"),
			SQLDataType.INTEGER.nullable(false), this, "");

	private Tbljobstatus(Name alias, Table<TbljobstatusRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Tbljobstatus(Name alias, Table<TbljobstatusRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>tbljobstatus</code> table reference
	 */
	public Tbljobstatus(String alias) {
		this(DSL.name(alias), TBLJOBSTATUS);
	}

	/**
	 * Create an aliased <code>tbljobstatus</code> table reference
	 */
	public Tbljobstatus(Name alias) {
		this(alias, TBLJOBSTATUS);
	}

	/**
	 * Create a <code>tbljobstatus</code> table reference
	 */
	public Tbljobstatus() {
		this(DSL.name("tbljobstatus"), null);
	}

	public <O extends Record> Tbljobstatus(Table<O> path, ForeignKey<O, TbljobstatusRecord> childPath,
			InverseForeignKey<O, TbljobstatusRecord> parentPath) {
		super(path, childPath, parentPath, TBLJOBSTATUS);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class TbljobstatusPath extends Tbljobstatus implements Path<TbljobstatusRecord> {

		private static final long serialVersionUID = 1L;

		public <O extends Record> TbljobstatusPath(Table<O> path, ForeignKey<O, TbljobstatusRecord> childPath,
				InverseForeignKey<O, TbljobstatusRecord> parentPath) {
			super(path, childPath, parentPath);
		}

		private TbljobstatusPath(Name alias, Table<TbljobstatusRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public TbljobstatusPath as(String alias) {
			return new TbljobstatusPath(DSL.name(alias), this);
		}

		@Override
		public TbljobstatusPath as(Name alias) {
			return new TbljobstatusPath(alias, this);
		}

		@Override
		public TbljobstatusPath as(Table<?> alias) {
			return new TbljobstatusPath(alias.getQualifiedName(), this);
		}

	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.TBLJOBSTATUS_FK_TBLJOBSTATUS_TBLACCOUNT_IDX);
	}

	@Override
	public Identity<TbljobstatusRecord, Integer> getIdentity() {
		return (Identity<TbljobstatusRecord, Integer>) super.getIdentity();
	}

	@Override
	public UniqueKey<TbljobstatusRecord> getPrimaryKey() {
		return Keys.KEY_TBLJOBSTATUS_PRIMARY;
	}

	private transient TbljobPath _tbljob;

	/**
	 * Get the implicit to-many join path to the <code>tbljob</code> table
	 */
	public TbljobPath tbljob() {
		if (_tbljob == null)
			_tbljob = new TbljobPath(this, null, Keys.FK_TBLJOB_TBLJOBSTATUS.getInverseKey());

		return _tbljob;
	}

	@Override
	public Tbljobstatus as(String alias) {
		return new Tbljobstatus(DSL.name(alias), this);
	}

	@Override
	public Tbljobstatus as(Name alias) {
		return new Tbljobstatus(alias, this);
	}

	@Override
	public Tbljobstatus as(Table<?> alias) {
		return new Tbljobstatus(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tbljobstatus rename(String name) {
		return new Tbljobstatus(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tbljobstatus rename(Name name) {
		return new Tbljobstatus(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Tbljobstatus rename(Table<?> name) {
		return new Tbljobstatus(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljobstatus where(Condition condition) {
		return new Tbljobstatus(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljobstatus where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljobstatus where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljobstatus where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbljobstatus where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbljobstatus where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbljobstatus where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Tbljobstatus where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljobstatus whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Tbljobstatus whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}

}
