/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq;

import io.recruitcrm.microservice.search.models.jooq.tables.CandidateCustomFieldsT;
import io.recruitcrm.microservice.search.models.jooq.tables.CandidateLastActivitiesT;
import io.recruitcrm.microservice.search.models.jooq.tables.ClientPortalStatusT;
import io.recruitcrm.microservice.search.models.jooq.tables.ContactCompanyT;
import io.recruitcrm.microservice.search.models.jooq.tables.ContractorPortalStatusT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstJobTimesheetAccessT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstRuleTemplateT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimeLogBreakIntervalT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimeLogIntervalT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimeLogT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetApprovalT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetApproverT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetInvoiceT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetReimbursementClientShareHistoryT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetReimbursementStatusHistoryT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetReimbursementT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetSettingAssociationT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetSettingT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetT;
import io.recruitcrm.microservice.search.models.jooq.tables.EntityOffLimitT;
import io.recruitcrm.microservice.search.models.jooq.tables.JobSecondaryContactsT;
import io.recruitcrm.microservice.search.models.jooq.tables.OffLimitStatusColourT;
import io.recruitcrm.microservice.search.models.jooq.tables.OffLimitStatusT;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblassignjobcandidate;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcandidate;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcompany;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcontact;

import java.util.Arrays;
import java.util.List;

import io.recruitcrm.microservice.search.models.jooq.tables.Tblcurrency;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldealcandidates;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldealjobs;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldealpipelinestages;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldeals;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblextrafields;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblgender;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbljob;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbljobstatus;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbluser;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>DEFAULT_SCHEMA</code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * The table <code>candidate_custom_fields_t</code>.
	 */
	public final CandidateCustomFieldsT CANDIDATE_CUSTOM_FIELDS_T = CandidateCustomFieldsT.CANDIDATE_CUSTOM_FIELDS_T;

	/**
	 * The table <code>candidate_last_activities_t</code>.
	 */
	public final CandidateLastActivitiesT CANDIDATE_LAST_ACTIVITIES_T = CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T;

	/**
	 * Stores contractor portal status and email send tracking details
	 */
	public final ContractorPortalStatusT CONTRACTOR_PORTAL_STATUS_T = ContractorPortalStatusT.CONTRACTOR_PORTAL_STATUS_T;

	/**
	 * Client portal lifecycle per HMP user within an RCRM account.
	 */
	public final ClientPortalStatusT CLIENT_PORTAL_STATUS_T = ClientPortalStatusT.CLIENT_PORTAL_STATUS_T;

	/**
	 * The table <code>contact_company_t</code>.
	 */
	public final ContactCompanyT CONTACT_COMPANY_T = ContactCompanyT.CONTACT_COMPANY_T;

	/**
	 * Timesheet access control per job
	 */
	public final CstJobTimesheetAccessT CST_JOB_TIMESHEET_ACCESS_T = CstJobTimesheetAccessT.CST_JOB_TIMESHEET_ACCESS_T;

	/**
	 * Denormalized table to store rule templates and their associated configurations in
	 * JSON
	 */
	public final CstRuleTemplateT CST_RULE_TEMPLATE_T = CstRuleTemplateT.CST_RULE_TEMPLATE_T;

	/**
	 * Store break interval
	 */
	public final CstTimeLogBreakIntervalT CST_TIME_LOG_BREAK_INTERVAL_T = CstTimeLogBreakIntervalT.CST_TIME_LOG_BREAK_INTERVAL_T;

	/**
	 * Store time log interval
	 */
	public final CstTimeLogIntervalT CST_TIME_LOG_INTERVAL_T = CstTimeLogIntervalT.CST_TIME_LOG_INTERVAL_T;

	/**
	 * Table to store time log entries including work time
	 */
	public final CstTimeLogT CST_TIME_LOG_T = CstTimeLogT.CST_TIME_LOG_T;

	/**
	 * Table to store timesheet approval records
	 */
	public final CstTimesheetApprovalT CST_TIMESHEET_APPROVAL_T = CstTimesheetApprovalT.CST_TIMESHEET_APPROVAL_T;

	/**
	 * Table to store approvers associated with timesheet settings
	 */
	public final CstTimesheetApproverT CST_TIMESHEET_APPROVER_T = CstTimesheetApproverT.CST_TIMESHEET_APPROVER_T;

	/**
	 * Table to store invoice details that are associated with timesheets, including pay,
	 * bill, payout, and audit information
	 */
	public final CstTimesheetInvoiceT CST_TIMESHEET_INVOICE_T = CstTimesheetInvoiceT.CST_TIMESHEET_INVOICE_T;

	/**
	 * Append-only audit log tracking every status transition for reimbursements
	 */
	public final CstTimesheetReimbursementStatusHistoryT CST_TIMESHEET_REIMBURSEMENT_STATUS_HISTORY_T = CstTimesheetReimbursementStatusHistoryT.CST_TIMESHEET_REIMBURSEMENT_STATUS_HISTORY_T;

	/**
	 * Stores reimbursement line items linked to timesheets with payable/billable flags
	 * and audit trail
	 */
	public final CstTimesheetReimbursementT CST_TIMESHEET_REIMBURSEMENT_T = CstTimesheetReimbursementT.CST_TIMESHEET_REIMBURSEMENT_T;

	/**
	 * Table to store approvers associated with timesheet settings
	 */
	public final CstTimesheetSettingAssociationT CST_TIMESHEET_SETTING_ASSOCIATION_T = CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T;

	/**
	 * Table to store timesheet settings including job and pay type details
	 */
	public final CstTimesheetSettingT CST_TIMESHEET_SETTING_T = CstTimesheetSettingT.CST_TIMESHEET_SETTING_T;

	/**
	 * Table to store timesheet records including payment and billing data
	 */
	public final CstTimesheetT CST_TIMESHEET_T = CstTimesheetT.CST_TIMESHEET_T;

	/**
	 * The table <code>entity_off_limit_t</code>.
	 */
	public final EntityOffLimitT ENTITY_OFF_LIMIT_T = EntityOffLimitT.ENTITY_OFF_LIMIT_T;

	/**
	 * The table <code>job_secondary_contacts_t</code>.
	 */
	public final JobSecondaryContactsT JOB_SECONDARY_CONTACTS_T = JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T;

	/**
	 * The table <code>off_limit_status_colour_t</code>.
	 */
	public final OffLimitStatusColourT OFF_LIMIT_STATUS_COLOUR_T = OffLimitStatusColourT.OFF_LIMIT_STATUS_COLOUR_T;

	/**
	 * The table <code>off_limit_status_t</code>.
	 */
	public final OffLimitStatusT OFF_LIMIT_STATUS_T = OffLimitStatusT.OFF_LIMIT_STATUS_T;

	/**
	 * The table <code>tblassignjobcandidate</code>.
	 */
	public final Tblassignjobcandidate TBLASSIGNJOBCANDIDATE = Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE;

	/**
	 * The table <code>tblcandidate</code>.
	 */
	public final Tblcandidate TBLCANDIDATE = Tblcandidate.TBLCANDIDATE;

	/**
	 * The table <code>tblcompany</code>.
	 */
	public final Tblcompany TBLCOMPANY = Tblcompany.TBLCOMPANY;

	/**
	 * The table <code>tblcontact</code>.
	 */
	public final Tblcontact TBLCONTACT = Tblcontact.TBLCONTACT;

	/**
	 * The table <code>tblcurrency</code>.
	 */
	public final Tblcurrency TBLCURRENCY = Tblcurrency.TBLCURRENCY;

	/**
	 * The table <code>tbldealcandidates</code>.
	 */
	public final Tbldealcandidates TBLDEALCANDIDATES = Tbldealcandidates.TBLDEALCANDIDATES;

	/**
	 * The table <code>tbldealjobs</code>.
	 */
	public final Tbldealjobs TBLDEALJOBS = Tbldealjobs.TBLDEALJOBS;

	/**
	 * The table <code>tbldealpipelinestages</code>.
	 */
	public final Tbldealpipelinestages TBLDEALPIPELINESTAGES = Tbldealpipelinestages.TBLDEALPIPELINESTAGES;

	/**
	 * The table <code>tbldeals</code>.
	 */
	public final Tbldeals TBLDEALS = Tbldeals.TBLDEALS;

	/**
	 * The table <code>tblextrafields</code>.
	 */
	public final Tblextrafields TBLEXTRAFIELDS = Tblextrafields.TBLEXTRAFIELDS;

	/**
	 * The table <code>tblgender</code>.
	 */
	public final Tblgender TBLGENDER = Tblgender.TBLGENDER;

	/**
	 * The table <code>tbljob</code>.
	 */
	public final Tbljob TBLJOB = Tbljob.TBLJOB;

	/**
	 * The table <code>tbljobstatus</code>.
	 */
	public final Tbljobstatus TBLJOBSTATUS = Tbljobstatus.TBLJOBSTATUS;

	/**
	 * The table <code>tbluser</code>.
	 */
	public final Tbluser TBLUSER = Tbluser.TBLUSER;

	public final CstTimesheetReimbursementClientShareHistoryT CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T = CstTimesheetReimbursementClientShareHistoryT.CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T;

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super(DSL.name(""), null, DSL.comment(""));
	}

	@Override
	public Catalog getCatalog() {
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables() {
		return Arrays.asList(CandidateCustomFieldsT.CANDIDATE_CUSTOM_FIELDS_T,
				CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T,
				ContractorPortalStatusT.CONTRACTOR_PORTAL_STATUS_T, ClientPortalStatusT.CLIENT_PORTAL_STATUS_T,
				ContactCompanyT.CONTACT_COMPANY_T, CstJobTimesheetAccessT.CST_JOB_TIMESHEET_ACCESS_T,
				CstRuleTemplateT.CST_RULE_TEMPLATE_T, CstTimeLogBreakIntervalT.CST_TIME_LOG_BREAK_INTERVAL_T,
				CstTimeLogIntervalT.CST_TIME_LOG_INTERVAL_T, CstTimeLogT.CST_TIME_LOG_T,
				CstTimesheetApprovalT.CST_TIMESHEET_APPROVAL_T, CstTimesheetApproverT.CST_TIMESHEET_APPROVER_T,
				CstTimesheetInvoiceT.CST_TIMESHEET_INVOICE_T,
				CstTimesheetReimbursementStatusHistoryT.CST_TIMESHEET_REIMBURSEMENT_STATUS_HISTORY_T,
				CstTimesheetReimbursementT.CST_TIMESHEET_REIMBURSEMENT_T,
				CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T,
				CstTimesheetSettingT.CST_TIMESHEET_SETTING_T, CstTimesheetT.CST_TIMESHEET_T,
				EntityOffLimitT.ENTITY_OFF_LIMIT_T, JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T,
				OffLimitStatusColourT.OFF_LIMIT_STATUS_COLOUR_T, OffLimitStatusT.OFF_LIMIT_STATUS_T,
				Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE, Tblcandidate.TBLCANDIDATE, Tblcompany.TBLCOMPANY,
				Tblcontact.TBLCONTACT, Tblcurrency.TBLCURRENCY, Tbldealcandidates.TBLDEALCANDIDATES,
				Tbldealjobs.TBLDEALJOBS, Tbldealpipelinestages.TBLDEALPIPELINESTAGES, Tbldeals.TBLDEALS,
				Tblextrafields.TBLEXTRAFIELDS, Tblgender.TBLGENDER, Tbljob.TBLJOB, Tbljobstatus.TBLJOBSTATUS,
				Tbluser.TBLUSER,
				CstTimesheetReimbursementClientShareHistoryT.CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T);
	}

}
