/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq;

import io.recruitcrm.microservice.search.models.jooq.tables.CandidateCustomFieldsT;
import io.recruitcrm.microservice.search.models.jooq.tables.CandidateLastActivitiesT;
import io.recruitcrm.microservice.search.models.jooq.tables.ClientPortalStatusT;
import io.recruitcrm.microservice.search.models.jooq.tables.ContactCompanyT;
import io.recruitcrm.microservice.search.models.jooq.tables.ContractorPortalStatusT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstJobTimesheetAccessT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstRuleTemplateT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimeLogBreakIntervalT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimeLogIntervalT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimeLogT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetApprovalT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetApproverT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetInvoiceT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetReimbursementStatusHistoryT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetReimbursementT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetSettingAssociationT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetSettingT;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetT;
import io.recruitcrm.microservice.search.models.jooq.tables.EntityOffLimitT;
import io.recruitcrm.microservice.search.models.jooq.tables.JobSecondaryContactsT;
import io.recruitcrm.microservice.search.models.jooq.tables.OffLimitStatusColourT;
import io.recruitcrm.microservice.search.models.jooq.tables.OffLimitStatusT;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblassignjobcandidate;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcandidate;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcompany;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcontact;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblcurrency;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldealcandidates;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldealjobs;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldealpipelinestages;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbldeals;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblextrafields;
import io.recruitcrm.microservice.search.models.jooq.tables.Tblgender;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbljob;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbljobstatus;
import io.recruitcrm.microservice.search.models.jooq.tables.Tbluser;
import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetReimbursementClientShareHistoryT;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CandidateCustomFieldsTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CandidateLastActivitiesTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.ClientPortalStatusTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.ContactCompanyTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.ContractorPortalStatusTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstJobTimesheetAccessTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstRuleTemplateTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimeLogBreakIntervalTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimeLogIntervalTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimeLogTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetApprovalTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetApproverTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetInvoiceTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetReimbursementStatusHistoryTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetReimbursementTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetSettingAssociationTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetSettingTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.EntityOffLimitTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.JobSecondaryContactsTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.OffLimitStatusColourTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.OffLimitStatusTRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblassignjobcandidateRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblcandidateRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblcompanyRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblcontactRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblcurrencyRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbldealcandidatesRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbldealjobsRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbldealpipelinestagesRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbldealsRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblextrafieldsRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TblgenderRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbljobRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbljobstatusRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.TbluserRecord;
import io.recruitcrm.microservice.search.models.jooq.tables.records.CstTimesheetReimbursementClientShareHistoryTRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;

/**
 * A class modelling foreign key relationships and constraints of tables in the default
 * schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<CandidateCustomFieldsTRecord> KEY_CANDIDATE_CUSTOM_FIELDS_T_PRIMARY = Internal
		.createUniqueKey(CandidateCustomFieldsT.CANDIDATE_CUSTOM_FIELDS_T,
				DSL.name("KEY_candidate_custom_fields_t_PRIMARY"),
				new TableField[] { CandidateCustomFieldsT.CANDIDATE_CUSTOM_FIELDS_T.CUSTOM_FIELD_ID }, true);

	public static final UniqueKey<CandidateCustomFieldsTRecord> KEY_CANDIDATE_CUSTOM_FIELDS_T_UNIQUE_CANDIDATEID_SLUG = Internal
		.createUniqueKey(CandidateCustomFieldsT.CANDIDATE_CUSTOM_FIELDS_T,
				DSL.name("KEY_candidate_custom_fields_t_unique_candidateid_slug"),
				new TableField[] { CandidateCustomFieldsT.CANDIDATE_CUSTOM_FIELDS_T.CANDIDATE_ID,
						CandidateCustomFieldsT.CANDIDATE_CUSTOM_FIELDS_T.IMPORT_SLUG },
				true);

	public static final UniqueKey<CandidateLastActivitiesTRecord> KEY_CANDIDATE_LAST_ACTIVITIES_T_CANDIDATE_ID = Internal
		.createUniqueKey(CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T,
				DSL.name("KEY_candidate_last_activities_t_candidate_id"),
				new TableField[] { CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T.CANDIDATE_ID }, true);

	public static final UniqueKey<CandidateLastActivitiesTRecord> KEY_CANDIDATE_LAST_ACTIVITIES_T_PRIMARY = Internal
		.createUniqueKey(CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T,
				DSL.name("KEY_candidate_last_activities_t_PRIMARY"),
				new TableField[] { CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T.ID }, true);

	public static final UniqueKey<ContractorPortalStatusTRecord> KEY_CONTRACTOR_PORTAL_STATUS_T_CONTRACTOR_ID = Internal
		.createUniqueKey(ContractorPortalStatusT.CONTRACTOR_PORTAL_STATUS_T,
				DSL.name("KEY_contractor_portal_status_t_contractor_id"),
				new TableField[] { ContractorPortalStatusT.CONTRACTOR_PORTAL_STATUS_T.CONTRACTOR_ID }, true);

	public static final UniqueKey<ContractorPortalStatusTRecord> KEY_CONTRACTOR_PORTAL_STATUS_T_PRIMARY = Internal
		.createUniqueKey(ContractorPortalStatusT.CONTRACTOR_PORTAL_STATUS_T,
				DSL.name("KEY_contractor_portal_status_t_PRIMARY"),
				new TableField[] { ContractorPortalStatusT.CONTRACTOR_PORTAL_STATUS_T.ID }, true);

	public static final UniqueKey<ClientPortalStatusTRecord> KEY_CLIENT_PORTAL_STATUS_T_PRIMARY = Internal
		.createUniqueKey(ClientPortalStatusT.CLIENT_PORTAL_STATUS_T, DSL.name("KEY_client_portal_status_t_PRIMARY"),
				new TableField[] { ClientPortalStatusT.CLIENT_PORTAL_STATUS_T.ID }, true);

	public static final UniqueKey<ClientPortalStatusTRecord> KEY_CLIENT_PORTAL_STATUS_T_UQ_VMS_USER_ACCOUNT = Internal
		.createUniqueKey(ClientPortalStatusT.CLIENT_PORTAL_STATUS_T,
				DSL.name("KEY_client_portal_status_t_uq_vms_user_account"),
				new TableField[] { ClientPortalStatusT.CLIENT_PORTAL_STATUS_T.VMS_USER_ID,
						ClientPortalStatusT.CLIENT_PORTAL_STATUS_T.ACCOUNT_ID },
				true);

	public static final UniqueKey<ContactCompanyTRecord> KEY_CONTACT_COMPANY_T_CONTACT_COMPANY_UNIQUE_IDX = Internal
		.createUniqueKey(ContactCompanyT.CONTACT_COMPANY_T,
				DSL.name("KEY_contact_company_t_contact_company_unique_idx"), new TableField[] {
						ContactCompanyT.CONTACT_COMPANY_T.CONTACT_ID, ContactCompanyT.CONTACT_COMPANY_T.COMPANY_ID },
				true);

	public static final UniqueKey<ContactCompanyTRecord> KEY_CONTACT_COMPANY_T_PRIMARY = Internal.createUniqueKey(
			ContactCompanyT.CONTACT_COMPANY_T, DSL.name("KEY_contact_company_t_PRIMARY"),
			new TableField[] { ContactCompanyT.CONTACT_COMPANY_T.ID }, true);

	public static final UniqueKey<CstJobTimesheetAccessTRecord> KEY_CST_JOB_TIMESHEET_ACCESS_T_JOB_ID = Internal
		.createUniqueKey(CstJobTimesheetAccessT.CST_JOB_TIMESHEET_ACCESS_T,
				DSL.name("KEY_cst_job_timesheet_access_t_job_id"),
				new TableField[] { CstJobTimesheetAccessT.CST_JOB_TIMESHEET_ACCESS_T.JOB_ID }, true);

	public static final UniqueKey<CstJobTimesheetAccessTRecord> KEY_CST_JOB_TIMESHEET_ACCESS_T_PRIMARY = Internal
		.createUniqueKey(CstJobTimesheetAccessT.CST_JOB_TIMESHEET_ACCESS_T,
				DSL.name("KEY_cst_job_timesheet_access_t_PRIMARY"),
				new TableField[] { CstJobTimesheetAccessT.CST_JOB_TIMESHEET_ACCESS_T.ID }, true);

	public static final UniqueKey<CstRuleTemplateTRecord> KEY_CST_RULE_TEMPLATE_T_PRIMARY = Internal.createUniqueKey(
			CstRuleTemplateT.CST_RULE_TEMPLATE_T, DSL.name("KEY_cst_rule_template_t_PRIMARY"),
			new TableField[] { CstRuleTemplateT.CST_RULE_TEMPLATE_T.ID }, true);

	public static final UniqueKey<CstRuleTemplateTRecord> KEY_CST_RULE_TEMPLATE_T_UK_RULE_TEMPLATE_NAME = Internal
		.createUniqueKey(CstRuleTemplateT.CST_RULE_TEMPLATE_T,
				DSL.name("KEY_cst_rule_template_t_uk_rule_template_name"),
				new TableField[] { CstRuleTemplateT.CST_RULE_TEMPLATE_T.TEMPLATE_NAME,
						CstRuleTemplateT.CST_RULE_TEMPLATE_T.ACCOUNT_ID },
				true);

	public static final UniqueKey<CstTimeLogBreakIntervalTRecord> KEY_CST_TIME_LOG_BREAK_INTERVAL_T_PRIMARY = Internal
		.createUniqueKey(CstTimeLogBreakIntervalT.CST_TIME_LOG_BREAK_INTERVAL_T,
				DSL.name("KEY_cst_time_log_break_interval_t_PRIMARY"),
				new TableField[] { CstTimeLogBreakIntervalT.CST_TIME_LOG_BREAK_INTERVAL_T.ID }, true);

	public static final UniqueKey<CstTimeLogIntervalTRecord> KEY_CST_TIME_LOG_INTERVAL_T_PRIMARY = Internal
		.createUniqueKey(CstTimeLogIntervalT.CST_TIME_LOG_INTERVAL_T, DSL.name("KEY_cst_time_log_interval_t_PRIMARY"),
				new TableField[] { CstTimeLogIntervalT.CST_TIME_LOG_INTERVAL_T.ID }, true);

	public static final UniqueKey<CstTimeLogTRecord> KEY_CST_TIME_LOG_T_PRIMARY = Internal.createUniqueKey(
			CstTimeLogT.CST_TIME_LOG_T, DSL.name("KEY_cst_time_log_t_PRIMARY"),
			new TableField[] { CstTimeLogT.CST_TIME_LOG_T.ID }, true);

	public static final UniqueKey<CstTimesheetApprovalTRecord> KEY_CST_TIMESHEET_APPROVAL_T_PRIMARY = Internal
		.createUniqueKey(CstTimesheetApprovalT.CST_TIMESHEET_APPROVAL_T,
				DSL.name("KEY_cst_timesheet_approval_t_PRIMARY"),
				new TableField[] { CstTimesheetApprovalT.CST_TIMESHEET_APPROVAL_T.ID }, true);

	public static final UniqueKey<CstTimesheetApproverTRecord> KEY_CST_TIMESHEET_APPROVER_T_PRIMARY = Internal
		.createUniqueKey(CstTimesheetApproverT.CST_TIMESHEET_APPROVER_T,
				DSL.name("KEY_cst_timesheet_approver_t_PRIMARY"),
				new TableField[] { CstTimesheetApproverT.CST_TIMESHEET_APPROVER_T.ID }, true);

	public static final UniqueKey<CstTimesheetInvoiceTRecord> KEY_CST_TIMESHEET_INVOICE_T_PRIMARY = Internal
		.createUniqueKey(CstTimesheetInvoiceT.CST_TIMESHEET_INVOICE_T, DSL.name("KEY_cst_timesheet_invoice_t_PRIMARY"),
				new TableField[] { CstTimesheetInvoiceT.CST_TIMESHEET_INVOICE_T.ID }, true);

	public static final UniqueKey<CstTimesheetReimbursementStatusHistoryTRecord> KEY_CST_TIMESHEET_REIMBURSEMENT_STATUS_HISTORY_T_PRIMARY = Internal
		.createUniqueKey(CstTimesheetReimbursementStatusHistoryT.CST_TIMESHEET_REIMBURSEMENT_STATUS_HISTORY_T,
				DSL.name("KEY_cst_timesheet_reimbursement_status_history_t_PRIMARY"),
				new TableField[] {
						CstTimesheetReimbursementStatusHistoryT.CST_TIMESHEET_REIMBURSEMENT_STATUS_HISTORY_T.ID },
				true);

	public static final UniqueKey<CstTimesheetReimbursementTRecord> KEY_CST_TIMESHEET_REIMBURSEMENT_T_PRIMARY = Internal
		.createUniqueKey(CstTimesheetReimbursementT.CST_TIMESHEET_REIMBURSEMENT_T,
				DSL.name("KEY_cst_timesheet_reimbursement_t_PRIMARY"),
				new TableField[] { CstTimesheetReimbursementT.CST_TIMESHEET_REIMBURSEMENT_T.ID }, true);

	public static final UniqueKey<CstTimesheetSettingAssociationTRecord> KEY_CST_TIMESHEET_SETTING_ASSOCIATION_T_JOB_CONTRACTOR_IDX = Internal
		.createUniqueKey(CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T,
				DSL.name("KEY_cst_timesheet_setting_association_t_job_contractor_idx"),
				new TableField[] { CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T.JOB_ID,
						CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T.CONTRACTOR_ID },
				true);

	public static final UniqueKey<CstTimesheetSettingAssociationTRecord> KEY_CST_TIMESHEET_SETTING_ASSOCIATION_T_PRIMARY = Internal
		.createUniqueKey(CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T,
				DSL.name("KEY_cst_timesheet_setting_association_t_PRIMARY"),
				new TableField[] { CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T.ID }, true);

	public static final UniqueKey<CstTimesheetSettingTRecord> KEY_CST_TIMESHEET_SETTING_T_PRIMARY = Internal
		.createUniqueKey(CstTimesheetSettingT.CST_TIMESHEET_SETTING_T, DSL.name("KEY_cst_timesheet_setting_t_PRIMARY"),
				new TableField[] { CstTimesheetSettingT.CST_TIMESHEET_SETTING_T.ID }, true);

	public static final UniqueKey<CstTimesheetTRecord> KEY_CST_TIMESHEET_T_PRIMARY = Internal.createUniqueKey(
			CstTimesheetT.CST_TIMESHEET_T, DSL.name("KEY_cst_timesheet_t_PRIMARY"),
			new TableField[] { CstTimesheetT.CST_TIMESHEET_T.ID }, true);

	public static final UniqueKey<EntityOffLimitTRecord> KEY_ENTITY_OFF_LIMIT_T_ENTITY_OFF_LIMIT_INDEX_ENTITY_TYPE_ENTITY_ID = Internal
		.createUniqueKey(EntityOffLimitT.ENTITY_OFF_LIMIT_T,
				DSL.name("KEY_entity_off_limit_t_entity_off_limit_index_entity_type_entity_id"), new TableField[] {
						EntityOffLimitT.ENTITY_OFF_LIMIT_T.ENTITY_TYPE, EntityOffLimitT.ENTITY_OFF_LIMIT_T.ENTITY_ID },
				true);

	public static final UniqueKey<EntityOffLimitTRecord> KEY_ENTITY_OFF_LIMIT_T_PRIMARY = Internal.createUniqueKey(
			EntityOffLimitT.ENTITY_OFF_LIMIT_T, DSL.name("KEY_entity_off_limit_t_PRIMARY"),
			new TableField[] { EntityOffLimitT.ENTITY_OFF_LIMIT_T.ID }, true);

	public static final UniqueKey<JobSecondaryContactsTRecord> KEY_JOB_SECONDARY_CONTACTS_T_INDEX_JOB_CONTACT = Internal
		.createUniqueKey(JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T,
				DSL.name("KEY_job_secondary_contacts_t_index_job_contact"),
				new TableField[] { JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T.JOB_ID,
						JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T.CONTACT_ID },
				true);

	public static final UniqueKey<JobSecondaryContactsTRecord> KEY_JOB_SECONDARY_CONTACTS_T_PRIMARY = Internal
		.createUniqueKey(JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T,
				DSL.name("KEY_job_secondary_contacts_t_PRIMARY"),
				new TableField[] { JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T.ID }, true);

	public static final UniqueKey<OffLimitStatusColourTRecord> KEY_OFF_LIMIT_STATUS_COLOUR_T_PRIMARY = Internal
		.createUniqueKey(OffLimitStatusColourT.OFF_LIMIT_STATUS_COLOUR_T,
				DSL.name("KEY_off_limit_status_colour_t_PRIMARY"),
				new TableField[] { OffLimitStatusColourT.OFF_LIMIT_STATUS_COLOUR_T.OFFLIMIT_STATUS_COLOUR_ID }, true);

	public static final UniqueKey<OffLimitStatusTRecord> KEY_OFF_LIMIT_STATUS_T_PRIMARY = Internal.createUniqueKey(
			OffLimitStatusT.OFF_LIMIT_STATUS_T, DSL.name("KEY_off_limit_status_t_PRIMARY"),
			new TableField[] { OffLimitStatusT.OFF_LIMIT_STATUS_T.ID }, true);

	public static final UniqueKey<TblassignjobcandidateRecord> KEY_TBLASSIGNJOBCANDIDATE_PRIMARY = Internal
		.createUniqueKey(Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE, DSL.name("KEY_tblassignjobcandidate_PRIMARY"),
				new TableField[] { Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE.ID }, true);

	public static final UniqueKey<TblcandidateRecord> KEY_TBLCANDIDATE_PRIMARY = Internal.createUniqueKey(
			Tblcandidate.TBLCANDIDATE, DSL.name("KEY_tblcandidate_PRIMARY"),
			new TableField[] { Tblcandidate.TBLCANDIDATE.ID }, true);

	public static final UniqueKey<TblcandidateRecord> KEY_TBLCANDIDATE_SLUG_UNIQUE = Internal.createUniqueKey(
			Tblcandidate.TBLCANDIDATE, DSL.name("KEY_tblcandidate_slug_UNIQUE"),
			new TableField[] { Tblcandidate.TBLCANDIDATE.SLUG }, true);

	public static final UniqueKey<TblcompanyRecord> KEY_TBLCOMPANY_COMPANYSLUG = Internal.createUniqueKey(
			Tblcompany.TBLCOMPANY, DSL.name("KEY_tblcompany_companyslug"),
			new TableField[] { Tblcompany.TBLCOMPANY.SLUG }, true);

	public static final UniqueKey<TblcompanyRecord> KEY_TBLCOMPANY_PRIMARY = Internal.createUniqueKey(
			Tblcompany.TBLCOMPANY, DSL.name("KEY_tblcompany_PRIMARY"), new TableField[] { Tblcompany.TBLCOMPANY.ID },
			true);

	public static final UniqueKey<TblcontactRecord> KEY_TBLCONTACT_PRIMARY = Internal.createUniqueKey(
			Tblcontact.TBLCONTACT, DSL.name("KEY_tblcontact_PRIMARY"), new TableField[] { Tblcontact.TBLCONTACT.ID },
			true);

	public static final UniqueKey<TblcontactRecord> KEY_TBLCONTACT_RELATEDTOCANDIDATE_UNIQUE = Internal.createUniqueKey(
			Tblcontact.TBLCONTACT, DSL.name("KEY_tblcontact_relatedtocandidate_UNIQUE"),
			new TableField[] { Tblcontact.TBLCONTACT.RELATEDTOCANDIDATE }, true);

	public static final UniqueKey<TblcontactRecord> KEY_TBLCONTACT_SLUG_UNIQUE = Internal.createUniqueKey(
			Tblcontact.TBLCONTACT, DSL.name("KEY_tblcontact_slug_UNIQUE"),
			new TableField[] { Tblcontact.TBLCONTACT.SLUG }, true);

	public static final UniqueKey<TblcurrencyRecord> KEY_TBLCURRENCY_PRIMARY = Internal.createUniqueKey(
			Tblcurrency.TBLCURRENCY, DSL.name("KEY_tblcurrency_PRIMARY"),
			new TableField[] { Tblcurrency.TBLCURRENCY.ID }, true);

	public static final UniqueKey<TbldealcandidatesRecord> KEY_TBLDEALCANDIDATES_PRIMARY = Internal.createUniqueKey(
			Tbldealcandidates.TBLDEALCANDIDATES, DSL.name("KEY_tbldealcandidates_PRIMARY"),
			new TableField[] { Tbldealcandidates.TBLDEALCANDIDATES.ID }, true);

	public static final UniqueKey<TbldealjobsRecord> KEY_TBLDEALJOBS_PRIMARY = Internal.createUniqueKey(
			Tbldealjobs.TBLDEALJOBS, DSL.name("KEY_tbldealjobs_PRIMARY"),
			new TableField[] { Tbldealjobs.TBLDEALJOBS.ID }, true);

	public static final UniqueKey<TbldealpipelinestagesRecord> KEY_TBLDEALPIPELINESTAGES_PRIMARY = Internal
		.createUniqueKey(Tbldealpipelinestages.TBLDEALPIPELINESTAGES, DSL.name("KEY_tbldealpipelinestages_PRIMARY"),
				new TableField[] { Tbldealpipelinestages.TBLDEALPIPELINESTAGES.ID }, true);

	public static final UniqueKey<TbldealsRecord> KEY_TBLDEALS_DEALSLUG = Internal.createUniqueKey(Tbldeals.TBLDEALS,
			DSL.name("KEY_tbldeals_dealslug"), new TableField[] { Tbldeals.TBLDEALS.SLUG }, true);

	public static final UniqueKey<TbldealsRecord> KEY_TBLDEALS_PRIMARY = Internal.createUniqueKey(Tbldeals.TBLDEALS,
			DSL.name("KEY_tbldeals_PRIMARY"), new TableField[] { Tbldeals.TBLDEALS.ID }, true);

	public static final UniqueKey<TblextrafieldsRecord> KEY_TBLEXTRAFIELDS_PRIMARY = Internal.createUniqueKey(
			Tblextrafields.TBLEXTRAFIELDS, DSL.name("KEY_tblextrafields_PRIMARY"),
			new TableField[] { Tblextrafields.TBLEXTRAFIELDS.ID }, true);

	public static final UniqueKey<TblgenderRecord> KEY_TBLGENDER_LABEL = Internal.createUniqueKey(Tblgender.TBLGENDER,
			DSL.name("KEY_tblgender_label"), new TableField[] { Tblgender.TBLGENDER.LABEL }, true);

	public static final UniqueKey<TblgenderRecord> KEY_TBLGENDER_PRIMARY = Internal.createUniqueKey(Tblgender.TBLGENDER,
			DSL.name("KEY_tblgender_PRIMARY"), new TableField[] { Tblgender.TBLGENDER.ID }, true);

	public static final UniqueKey<TbljobRecord> KEY_TBLJOB_JOBSLUG = Internal.createUniqueKey(Tbljob.TBLJOB,
			DSL.name("KEY_tbljob_jobslug"), new TableField[] { Tbljob.TBLJOB.SLUG }, true);

	public static final UniqueKey<TbljobRecord> KEY_TBLJOB_PRIMARY = Internal.createUniqueKey(Tbljob.TBLJOB,
			DSL.name("KEY_tbljob_PRIMARY"), new TableField[] { Tbljob.TBLJOB.ID }, true);

	public static final UniqueKey<TbljobstatusRecord> KEY_TBLJOBSTATUS_PRIMARY = Internal.createUniqueKey(
			Tbljobstatus.TBLJOBSTATUS, DSL.name("KEY_tbljobstatus_PRIMARY"),
			new TableField[] { Tbljobstatus.TBLJOBSTATUS.ID }, true);

	public static final UniqueKey<TbluserRecord> KEY_TBLUSER_APITOKEN = Internal.createUniqueKey(Tbluser.TBLUSER,
			DSL.name("KEY_tbluser_apitoken"), new TableField[] { Tbluser.TBLUSER.APITOKEN }, true);

	public static final UniqueKey<TbluserRecord> KEY_TBLUSER_PRIMARY = Internal.createUniqueKey(Tbluser.TBLUSER,
			DSL.name("KEY_tbluser_PRIMARY"), new TableField[] { Tbluser.TBLUSER.ID }, true);

	public static final UniqueKey<TbluserRecord> KEY_TBLUSER_USERSLUG = Internal.createUniqueKey(Tbluser.TBLUSER,
			DSL.name("KEY_tbluser_userslug"), new TableField[] { Tbluser.TBLUSER.SLUG }, true);

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<CandidateCustomFieldsTRecord, TblcandidateRecord> FK_CUSTOM_FIELD_T_TBLCANDIDATE = Internal
		.createForeignKey(CandidateCustomFieldsT.CANDIDATE_CUSTOM_FIELDS_T, DSL.name("fk_custom_field_t_tblcandidate"),
				new TableField[] { CandidateCustomFieldsT.CANDIDATE_CUSTOM_FIELDS_T.CANDIDATE_ID },
				Keys.KEY_TBLCANDIDATE_PRIMARY, new TableField[] { Tblcandidate.TBLCANDIDATE.ID }, true,
				ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<CandidateLastActivitiesTRecord, TblcandidateRecord> CANDIDATE_LAST_ACTIVITIES_T_IBFK_1 = Internal
		.createForeignKey(CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T,
				DSL.name("candidate_last_activities_t_ibfk_1"),
				new TableField[] { CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T.CANDIDATE_ID },
				Keys.KEY_TBLCANDIDATE_PRIMARY, new TableField[] { Tblcandidate.TBLCANDIDATE.ID }, true,
				ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<ContactCompanyTRecord, TblcontactRecord> CONTACT_COMPANY_T_IBFK_1 = Internal
		.createForeignKey(ContactCompanyT.CONTACT_COMPANY_T, DSL.name("contact_company_t_ibfk_1"),
				new TableField[] { ContactCompanyT.CONTACT_COMPANY_T.CONTACT_ID }, Keys.KEY_TBLCONTACT_PRIMARY,
				new TableField[] { Tblcontact.TBLCONTACT.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<ContactCompanyTRecord, TblcompanyRecord> CONTACT_COMPANY_T_IBFK_2 = Internal
		.createForeignKey(ContactCompanyT.CONTACT_COMPANY_T, DSL.name("contact_company_t_ibfk_2"),
				new TableField[] { ContactCompanyT.CONTACT_COMPANY_T.COMPANY_ID }, Keys.KEY_TBLCOMPANY_PRIMARY,
				new TableField[] { Tblcompany.TBLCOMPANY.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<CstTimeLogBreakIntervalTRecord, CstTimeLogTRecord> FK_TIME_LOG_CST = Internal
		.createForeignKey(CstTimeLogBreakIntervalT.CST_TIME_LOG_BREAK_INTERVAL_T, DSL.name("fk_time_log_cst"),
				new TableField[] { CstTimeLogBreakIntervalT.CST_TIME_LOG_BREAK_INTERVAL_T.TIME_LOG_ID },
				Keys.KEY_CST_TIME_LOG_T_PRIMARY, new TableField[] { CstTimeLogT.CST_TIME_LOG_T.ID }, true,
				ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<CstTimeLogTRecord, CstTimesheetTRecord> FK_TIME_LOG_TIMESHEET = Internal
		.createForeignKey(CstTimeLogT.CST_TIME_LOG_T, DSL.name("fk_time_log_timesheet"),
				new TableField[] { CstTimeLogT.CST_TIME_LOG_T.TIMESHEET_ID }, Keys.KEY_CST_TIMESHEET_T_PRIMARY,
				new TableField[] { CstTimesheetT.CST_TIMESHEET_T.ID }, true, ForeignKeyRule.NO_ACTION,
				ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<CstTimesheetApprovalTRecord, CstTimesheetTRecord> FK_TIMESHEET_APPROVAL_T_TIMESHEET = Internal
		.createForeignKey(CstTimesheetApprovalT.CST_TIMESHEET_APPROVAL_T, DSL.name("fk_timesheet_approval_t_timesheet"),
				new TableField[] { CstTimesheetApprovalT.CST_TIMESHEET_APPROVAL_T.TIMESHEET_ID },
				Keys.KEY_CST_TIMESHEET_T_PRIMARY, new TableField[] { CstTimesheetT.CST_TIMESHEET_T.ID }, true,
				ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<CstTimesheetApproverTRecord, CstTimesheetSettingTRecord> FK_TIMESHEET_APPROVER_TIMESHEET_SETTING = Internal
		.createForeignKey(CstTimesheetApproverT.CST_TIMESHEET_APPROVER_T,
				DSL.name("fk_timesheet_approver_timesheet_setting"),
				new TableField[] { CstTimesheetApproverT.CST_TIMESHEET_APPROVER_T.TIMESHEET_SETTING_ID },
				Keys.KEY_CST_TIMESHEET_SETTING_T_PRIMARY,
				new TableField[] { CstTimesheetSettingT.CST_TIMESHEET_SETTING_T.ID }, true, ForeignKeyRule.NO_ACTION,
				ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<CstTimesheetSettingTRecord, TblcurrencyRecord> FK_BILL_CURRENCY = Internal
		.createForeignKey(CstTimesheetSettingT.CST_TIMESHEET_SETTING_T, DSL.name("fk_bill_currency"),
				new TableField[] { CstTimesheetSettingT.CST_TIMESHEET_SETTING_T.BILL_CURRENCY_ID },
				Keys.KEY_TBLCURRENCY_PRIMARY, new TableField[] { Tblcurrency.TBLCURRENCY.ID }, true,
				ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<CstTimesheetSettingTRecord, TblcurrencyRecord> FK_PAY_CURRENCY = Internal
		.createForeignKey(CstTimesheetSettingT.CST_TIMESHEET_SETTING_T, DSL.name("fk_pay_currency"),
				new TableField[] { CstTimesheetSettingT.CST_TIMESHEET_SETTING_T.PAY_CURRENCY_ID },
				Keys.KEY_TBLCURRENCY_PRIMARY, new TableField[] { Tblcurrency.TBLCURRENCY.ID }, true,
				ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<CstTimesheetSettingTRecord, CstTimesheetSettingAssociationTRecord> FK_TIMESHEET_SETTING_ASSOCIATION = Internal
		.createForeignKey(CstTimesheetSettingT.CST_TIMESHEET_SETTING_T, DSL.name("fk_timesheet_setting_association"),
				new TableField[] { CstTimesheetSettingT.CST_TIMESHEET_SETTING_T.ASSOCIATION_ID },
				Keys.KEY_CST_TIMESHEET_SETTING_ASSOCIATION_T_PRIMARY,
				new TableField[] { CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T.ID }, true,
				ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<CstTimesheetTRecord, CstTimesheetSettingTRecord> FK_TIMESHEET_SETTING_TIMESHEET_T = Internal
		.createForeignKey(CstTimesheetT.CST_TIMESHEET_T, DSL.name("fk_timesheet_setting_timesheet_t"),
				new TableField[] { CstTimesheetT.CST_TIMESHEET_T.TIMESHEET_SETTING_ID },
				Keys.KEY_CST_TIMESHEET_SETTING_T_PRIMARY,
				new TableField[] { CstTimesheetSettingT.CST_TIMESHEET_SETTING_T.ID }, true, ForeignKeyRule.NO_ACTION,
				ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<JobSecondaryContactsTRecord, TblcontactRecord> FK_JOBSECONDARYCONTACT_CONTACT = Internal
		.createForeignKey(JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T, DSL.name("fk_jobsecondarycontact_contact"),
				new TableField[] { JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T.CONTACT_ID },
				Keys.KEY_TBLCONTACT_PRIMARY, new TableField[] { Tblcontact.TBLCONTACT.ID }, true,
				ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<JobSecondaryContactsTRecord, TbljobRecord> FK_JOBSECONDARYCONTACT_JOB = Internal
		.createForeignKey(JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T, DSL.name("fk_jobsecondarycontact_job"),
				new TableField[] { JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T.JOB_ID }, Keys.KEY_TBLJOB_PRIMARY,
				new TableField[] { Tbljob.TBLJOB.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TblassignjobcandidateRecord, TblcandidateRecord> FK_TBLASSIGNJOBCANDIDATE_TBLCANDIDATE = Internal
		.createForeignKey(Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE,
				DSL.name("fk_tblassignjobcandidate_tblcandidate"),
				new TableField[] { Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE.CANDIDATEID },
				Keys.KEY_TBLCANDIDATE_PRIMARY, new TableField[] { Tblcandidate.TBLCANDIDATE.ID }, true,
				ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TblassignjobcandidateRecord, TbljobRecord> FK_TBLASSIGNJOBCANDIDATE_TBLJOB = Internal
		.createForeignKey(Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE, DSL.name("fk_tblassignjobcandidate_tbljob"),
				new TableField[] { Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE.JOBID }, Keys.KEY_TBLJOB_PRIMARY,
				new TableField[] { Tbljob.TBLJOB.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TblassignjobcandidateRecord, TbluserRecord> FK_TBLASSIGNJOBCANDIDATE_TBLUSER = Internal
		.createForeignKey(Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE, DSL.name("fk_tblassignjobcandidate_tbluser"),
				new TableField[] { Tblassignjobcandidate.TBLASSIGNJOBCANDIDATE.OWNERID }, Keys.KEY_TBLUSER_PRIMARY,
				new TableField[] { Tbluser.TBLUSER.ID }, true, ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TblcandidateRecord, TblcurrencyRecord> FK_TBLCANDIDATE_TBLCURRENCY = Internal
		.createForeignKey(Tblcandidate.TBLCANDIDATE, DSL.name("fk_tblcandidate_tblcurrency"),
				new TableField[] { Tblcandidate.TBLCANDIDATE.CURRENCYID }, Keys.KEY_TBLCURRENCY_PRIMARY,
				new TableField[] { Tblcurrency.TBLCURRENCY.ID }, true, ForeignKeyRule.NO_ACTION,
				ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TblcandidateRecord, TblgenderRecord> FK_TBLCANDIDATE_TBLGENDER = Internal
		.createForeignKey(Tblcandidate.TBLCANDIDATE, DSL.name("fk_tblcandidate_tblgender"),
				new TableField[] { Tblcandidate.TBLCANDIDATE.GENDERID }, Keys.KEY_TBLGENDER_PRIMARY,
				new TableField[] { Tblgender.TBLGENDER.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TblcandidateRecord, TbluserRecord> FK_TBLCANDIDATE_TBLUSER = Internal
		.createForeignKey(Tblcandidate.TBLCANDIDATE, DSL.name("fk_tblcandidate_tbluser"),
				new TableField[] { Tblcandidate.TBLCANDIDATE.OWNERID }, Keys.KEY_TBLUSER_PRIMARY,
				new TableField[] { Tbluser.TBLUSER.ID }, true, ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TblcompanyRecord, TbluserRecord> FK_TBLCOMPANY_TBLUSER = Internal.createForeignKey(
			Tblcompany.TBLCOMPANY, DSL.name("fk_tblcompany_tbluser"),
			new TableField[] { Tblcompany.TBLCOMPANY.OWNERID }, Keys.KEY_TBLUSER_PRIMARY,
			new TableField[] { Tbluser.TBLUSER.ID }, true, ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TblcontactRecord, TblcompanyRecord> FK_TBLCONTACT_TBLCOMPANY = Internal
		.createForeignKey(Tblcontact.TBLCONTACT, DSL.name("fk_tblcontact_tblcompany"),
				new TableField[] { Tblcontact.TBLCONTACT.COMPANYID }, Keys.KEY_TBLCOMPANY_PRIMARY,
				new TableField[] { Tblcompany.TBLCOMPANY.ID }, true, ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TblcontactRecord, TbluserRecord> FK_TBLCONTACT_TBLUSER = Internal.createForeignKey(
			Tblcontact.TBLCONTACT, DSL.name("fk_tblcontact_tbluser"),
			new TableField[] { Tblcontact.TBLCONTACT.OWNERID }, Keys.KEY_TBLUSER_PRIMARY,
			new TableField[] { Tbluser.TBLUSER.ID }, true, ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbldealcandidatesRecord, TblcandidateRecord> FK_TBLDEALCANDIDATES_TBLCANDIDATE = Internal
		.createForeignKey(Tbldealcandidates.TBLDEALCANDIDATES, DSL.name("fk_tbldealcandidates_tblcandidate"),
				new TableField[] { Tbldealcandidates.TBLDEALCANDIDATES.CANDIDATEID }, Keys.KEY_TBLCANDIDATE_PRIMARY,
				new TableField[] { Tblcandidate.TBLCANDIDATE.ID }, true, ForeignKeyRule.CASCADE,
				ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbldealcandidatesRecord, TbldealsRecord> FK_TBLDEALCANDIDATES_TBLDEALS = Internal
		.createForeignKey(Tbldealcandidates.TBLDEALCANDIDATES, DSL.name("fk_tbldealcandidates_tbldeals"),
				new TableField[] { Tbldealcandidates.TBLDEALCANDIDATES.DEALID }, Keys.KEY_TBLDEALS_PRIMARY,
				new TableField[] { Tbldeals.TBLDEALS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbldealjobsRecord, TbldealsRecord> FK_TBLDEALJOBS_TBLDEALS = Internal
		.createForeignKey(Tbldealjobs.TBLDEALJOBS, DSL.name("fk_tbldealjobs_tbldeals"),
				new TableField[] { Tbldealjobs.TBLDEALJOBS.DEALID }, Keys.KEY_TBLDEALS_PRIMARY,
				new TableField[] { Tbldeals.TBLDEALS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbldealjobsRecord, TbljobRecord> FK_TBLDEALJOBS_TBLJOB = Internal.createForeignKey(
			Tbldealjobs.TBLDEALJOBS, DSL.name("fk_tbldealjobs_tbljob"),
			new TableField[] { Tbldealjobs.TBLDEALJOBS.JOBID }, Keys.KEY_TBLJOB_PRIMARY,
			new TableField[] { Tbljob.TBLJOB.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbldealsRecord, TblcompanyRecord> FK_TBLDEALS_TBLCOMPANY = Internal.createForeignKey(
			Tbldeals.TBLDEALS, DSL.name("fk_tbldeals_tblcompany"),
			new TableField[] { Tbldeals.TBLDEALS.RELATEDCOMPANY }, Keys.KEY_TBLCOMPANY_PRIMARY,
			new TableField[] { Tblcompany.TBLCOMPANY.ID }, true, ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbldealsRecord, TbldealpipelinestagesRecord> FK_TBLDEALS_TBLDEALPIPELINESTAGES = Internal
		.createForeignKey(Tbldeals.TBLDEALS, DSL.name("fk_tbldeals_tbldealpipelinestages"),
				new TableField[] { Tbldeals.TBLDEALS.DEALSTAGE }, Keys.KEY_TBLDEALPIPELINESTAGES_PRIMARY,
				new TableField[] { Tbldealpipelinestages.TBLDEALPIPELINESTAGES.ID }, true, ForeignKeyRule.SET_NULL,
				ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbldealsRecord, TbluserRecord> FK_TBLDEALS_TBLUSER = Internal.createForeignKey(
			Tbldeals.TBLDEALS, DSL.name("fk_tbldeals_tbluser"), new TableField[] { Tbldeals.TBLDEALS.OWNERID },
			Keys.KEY_TBLUSER_PRIMARY, new TableField[] { Tbluser.TBLUSER.ID }, true, ForeignKeyRule.SET_NULL,
			ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbljobRecord, TblcompanyRecord> FK_TBLJOB_TBLCOMPANY = Internal.createForeignKey(
			Tbljob.TBLJOB, DSL.name("fk_tbljob_tblcompany"), new TableField[] { Tbljob.TBLJOB.COMPANYID },
			Keys.KEY_TBLCOMPANY_PRIMARY, new TableField[] { Tblcompany.TBLCOMPANY.ID }, true, ForeignKeyRule.SET_NULL,
			ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbljobRecord, TblcontactRecord> FK_TBLJOB_TBLCONTACT = Internal.createForeignKey(
			Tbljob.TBLJOB, DSL.name("fk_tbljob_tblcontact"), new TableField[] { Tbljob.TBLJOB.CONTACTID },
			Keys.KEY_TBLCONTACT_PRIMARY, new TableField[] { Tblcontact.TBLCONTACT.ID }, true, ForeignKeyRule.SET_NULL,
			ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbljobRecord, TblcurrencyRecord> FK_TBLJOB_TBLCURRENCY = Internal.createForeignKey(
			Tbljob.TBLJOB, DSL.name("fk_tbljob_tblcurrency"), new TableField[] { Tbljob.TBLJOB.CURRENCYID },
			Keys.KEY_TBLCURRENCY_PRIMARY, new TableField[] { Tblcurrency.TBLCURRENCY.ID }, true,
			ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbljobRecord, TbljobstatusRecord> FK_TBLJOB_TBLJOBSTATUS = Internal.createForeignKey(
			Tbljob.TBLJOB, DSL.name("fk_tbljob_tbljobstatus"), new TableField[] { Tbljob.TBLJOB.JOBSTATUS },
			Keys.KEY_TBLJOBSTATUS_PRIMARY, new TableField[] { Tbljobstatus.TBLJOBSTATUS.ID }, true,
			ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION);

	public static final ForeignKey<TbljobRecord, TbluserRecord> FK_TBLJOB_TBLUSER = Internal.createForeignKey(
			Tbljob.TBLJOB, DSL.name("fk_tbljob_tbluser"), new TableField[] { Tbljob.TBLJOB.OWNERID },
			Keys.KEY_TBLUSER_PRIMARY, new TableField[] { Tbluser.TBLUSER.ID }, true, ForeignKeyRule.SET_NULL,
			ForeignKeyRule.NO_ACTION);

	public static final UniqueKey<CstTimesheetReimbursementClientShareHistoryTRecord> KEY_CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T_PRIMARY = Internal
		.createUniqueKey(
				CstTimesheetReimbursementClientShareHistoryT.CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T,
				DSL.name("KEY_cst_timesheet_reimbursement_client_share_history_t_PRIMARY"),
				new TableField[] {
						CstTimesheetReimbursementClientShareHistoryT.CST_TIMESHEET_REIMBURSEMENT_CLIENT_SHARE_HISTORY_T.ID },
				true);

}
