package io.recruitcrm.microservice.timesheet.dao.job_timesheet_access;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import javax.sql.DataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;
import org.springframework.test.context.BootstrapWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.ContextCustomizerFactory;
import org.springframework.test.context.support.DefaultTestContextBootstrapper;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.annotation.Transactional;

import io.recruitcrm.contract_staffing.entity.model.JobTimesheetAccess;
import io.recruitcrm.microservice.timesheet.testdata.JobTimesheetAccessTestDataFactory;

/**
 * Slice tests for {@link JobTimesheetAccessJpaRepository} using an isolated JPA context
 * (no full {@code TimesheetApplication}) so repository queries and Spring Data wiring are
 * validated without unrelated beans such as {@code JooqORMConfiguration}.
 */
@ExtendWith(SpringExtension.class)
@BootstrapWith(JobTimesheetAccessJpaRepositoryTests.NoDuplicateJsonWarningBootstrapper.class)
@ContextConfiguration(classes = JobTimesheetAccessJpaRepositoryTests.JobTimesheetAccessJpaTestApplication.class)
@Transactional
@DisplayName("JobTimesheetAccessJpaRepository Tests")
class JobTimesheetAccessJpaRepositoryTests {

	private static final String DUPLICATE_JSON_OBJECT_CONTEXT_CUSTOMIZER_FACTORY = "org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory";

	@Autowired
	private EntityManager entityManager;

	@Autowired
	private JobTimesheetAccessJpaRepository repository;

	@BeforeEach
	void setUp() {
		this.entityManager
			.createNativeQuery("CREATE TABLE IF NOT EXISTS cst_job_timesheet_access_t ("
					+ "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," + "job_id INTEGER,"
					+ "can_create INTEGER," + "can_edit INTEGER," + "can_delete INTEGER," + "updated_by INTEGER,"
					+ "updated_on INTEGER," + "account_id INTEGER)")
			.executeUpdate();
	}

	private void persistAndFlush(JobTimesheetAccess access) {
		this.entityManager.persist(access);
		this.entityManager.flush();
	}

	private void flushAndClear() {
		this.entityManager.flush();
		this.entityManager.clear();
	}

	@Test
	@DisplayName("findByJobId returns access when job id exists")
	void testFindByJobIdValidJobIdReturnsJobTimesheetAccess() {
		// Given
		JobTimesheetAccess access = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(1001),
				Integer.valueOf(100));
		this.persistAndFlush(access);

		// When
		Optional<JobTimesheetAccess> result = this.repository.findByJobId(Integer.valueOf(1001));

		// Then
		assertThat(result).isPresent();
		assertThat(result.get().getJobId()).isEqualTo(Integer.valueOf(1001));
		assertThat(result.get().getAccountId()).isEqualTo(Integer.valueOf(100));
		assertThat(result.get().getCanCreate()).isEqualTo(JobTimesheetAccessTestDataFactory.DEFAULT_CAN_CREATE);
	}

	@Test
	@DisplayName("findByJobId returns empty when job id does not exist")
	void testFindByJobIdInvalidJobIdReturnsEmpty() {
		// Given
		Integer nonExistentJobId = Integer.valueOf(9999);

		// When
		Optional<JobTimesheetAccess> result = this.repository.findByJobId(nonExistentJobId);

		// Then
		assertThat(result).isEmpty();
	}

	@Test
	@DisplayName("findByJobId throws when multiple records share the same job id")
	void testFindByJobIdMultipleRecordsThrowsIncorrectResultSize() {
		// Given
		JobTimesheetAccess access1 = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(2001),
				Integer.valueOf(200));
		this.persistAndFlush(access1);

		JobTimesheetAccess access2 = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(2001),
				Integer.valueOf(201), JobTimesheetAccessTestDataFactory.CAN_CREATE_DISABLED,
				JobTimesheetAccessTestDataFactory.DEFAULT_CAN_EDIT,
				JobTimesheetAccessTestDataFactory.DEFAULT_CAN_DELETE);
		this.persistAndFlush(access2);

		// When and Then
		assertThatThrownBy(() -> this.repository.findByJobId(Integer.valueOf(2001)))
			.isInstanceOf(org.springframework.dao.IncorrectResultSizeDataAccessException.class);
	}

	@Test
	@DisplayName("findByJobIdAndAccountId returns access when both ids match")
	void testFindByJobIdAndAccountIdValidIdsReturnsJobTimesheetAccess() {
		// Given
		JobTimesheetAccess access = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(3001),
				Integer.valueOf(300), JobTimesheetAccessTestDataFactory.DEFAULT_CAN_CREATE,
				JobTimesheetAccessTestDataFactory.DEFAULT_CAN_EDIT, Integer.valueOf(1));
		this.persistAndFlush(access);

		// When
		Optional<JobTimesheetAccess> result = this.repository.findByJobIdAndAccountId(Integer.valueOf(3001),
				Integer.valueOf(300));

		// Then
		assertThat(result).isPresent();
		assertThat(result.get().getJobId()).isEqualTo(Integer.valueOf(3001));
		assertThat(result.get().getAccountId()).isEqualTo(Integer.valueOf(300));
		assertThat(result.get().getCanCreate()).isEqualTo(JobTimesheetAccessTestDataFactory.DEFAULT_CAN_CREATE);
		assertThat(result.get().getCanEdit()).isEqualTo(JobTimesheetAccessTestDataFactory.DEFAULT_CAN_EDIT);
	}

	@Test
	@DisplayName("findByJobIdAndAccountId returns empty when job id does not match")
	void testFindByJobIdAndAccountIdInvalidJobIdReturnsEmpty() {
		// Given
		JobTimesheetAccess access = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(4001),
				Integer.valueOf(400));
		this.persistAndFlush(access);

		// When
		Optional<JobTimesheetAccess> result = this.repository.findByJobIdAndAccountId(Integer.valueOf(9999),
				Integer.valueOf(400));

		// Then
		assertThat(result).isEmpty();
	}

	@Test
	@DisplayName("findByJobIdAndAccountId returns empty when account id does not match")
	void testFindByJobIdAndAccountIdInvalidAccountIdReturnsEmpty() {
		// Given
		JobTimesheetAccess access = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(5001),
				Integer.valueOf(500));
		this.persistAndFlush(access);

		// When
		Optional<JobTimesheetAccess> result = this.repository.findByJobIdAndAccountId(Integer.valueOf(5001),
				Integer.valueOf(9999));

		// Then
		assertThat(result).isEmpty();
	}

	@Test
	@DisplayName("findByJobIdAndAccountId returns empty when neither id matches")
	void testFindByJobIdAndAccountIdBothIdsInvalidReturnsEmpty() {
		// Given
		JobTimesheetAccess access = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(6001),
				Integer.valueOf(600));
		this.persistAndFlush(access);

		// When
		Optional<JobTimesheetAccess> result = this.repository.findByJobIdAndAccountId(Integer.valueOf(9999),
				Integer.valueOf(9999));

		// Then
		assertThat(result).isEmpty();
	}

	@Test
	@DisplayName("findByJobIdAndAccountId returns correct row when multiple rows exist")
	void testFindByJobIdAndAccountIdFiltersCorrectlyWithMultipleRecords() {
		// Given
		JobTimesheetAccess access1 = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(7001),
				Integer.valueOf(700));
		this.persistAndFlush(access1);

		JobTimesheetAccess access2 = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(7001),
				Integer.valueOf(701), JobTimesheetAccessTestDataFactory.CAN_CREATE_DISABLED,
				JobTimesheetAccessTestDataFactory.DEFAULT_CAN_EDIT,
				JobTimesheetAccessTestDataFactory.DEFAULT_CAN_DELETE);
		this.persistAndFlush(access2);

		JobTimesheetAccess access3 = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(7002),
				Integer.valueOf(700), JobTimesheetAccessTestDataFactory.CAN_CREATE_DISABLED,
				JobTimesheetAccessTestDataFactory.DEFAULT_CAN_EDIT,
				JobTimesheetAccessTestDataFactory.DEFAULT_CAN_DELETE);
		this.persistAndFlush(access3);

		// When
		Optional<JobTimesheetAccess> result = this.repository.findByJobIdAndAccountId(Integer.valueOf(7001),
				Integer.valueOf(700));

		// Then
		assertThat(result).isPresent();
		assertThat(result.get().getJobId()).isEqualTo(Integer.valueOf(7001));
		assertThat(result.get().getAccountId()).isEqualTo(Integer.valueOf(700));
		assertThat(result.get().getCanCreate()).isEqualTo(JobTimesheetAccessTestDataFactory.DEFAULT_CAN_CREATE);
	}

	@Test
	@DisplayName("findByJobIdsAndAccountId returns all matching rows for account")
	void testFindByJobIdsAndAccountIdReturnsMatchingRows() {
		// Given
		Integer accountId = Integer.valueOf(8100);
		this.persistAndFlush(
				JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(8101), accountId));
		this.persistAndFlush(
				JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(8102), accountId));
		this.persistAndFlush(JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(8103),
				Integer.valueOf(999)));

		// When
		List<JobTimesheetAccess> result = this.repository.findByJobIdsAndAccountId(
				List.of(Integer.valueOf(8101), Integer.valueOf(8102), Integer.valueOf(8103)), accountId);

		// Then
		assertThat(result).hasSize(2);
		assertThat(result).extracting(JobTimesheetAccess::getJobId)
			.containsExactlyInAnyOrder(Integer.valueOf(8101), Integer.valueOf(8102));
	}

	@Test
	@DisplayName("findByJobIdsAndAccountId returns empty list when no job ids match account")
	void testFindByJobIdsAndAccountIdNoMatchesReturnsEmpty() {
		// Given
		this.persistAndFlush(JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(8201),
				Integer.valueOf(8200)));

		// When
		List<JobTimesheetAccess> result = this.repository
			.findByJobIdsAndAccountId(List.of(Integer.valueOf(8201), Integer.valueOf(8202)), Integer.valueOf(9999));

		// Then
		assertThat(result).isEmpty();
	}

	@Test
	@DisplayName("findByJobIdsAndAccountId returns empty list when account id is null")
	void testFindByJobIdsAndAccountIdNullAccountIdReturnsEmpty() {
		// Given
		this.persistAndFlush(JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(8210),
				Integer.valueOf(8211)));

		// When
		List<JobTimesheetAccess> result = this.repository.findByJobIdsAndAccountId(List.of(Integer.valueOf(8210)),
				null);

		// Then
		assertThat(result).isEmpty();
	}

	@Test
	@DisplayName("findByJobIdsAndAccountId returns empty list when job id list is empty")
	void testFindByJobIdsAndAccountIdEmptyJobIdsReturnsEmpty() {
		// Given
		this.persistAndFlush(JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(8301),
				Integer.valueOf(8300)));

		// When
		List<JobTimesheetAccess> result = this.repository.findByJobIdsAndAccountId(List.of(), Integer.valueOf(8300));

		// Then
		assertThat(result).isEmpty();
	}

	@Test
	@DisplayName("save persists new JobTimesheetAccess")
	void testSaveNewJobTimesheetAccessPersistsSuccessfully() {
		// Given
		JobTimesheetAccess newAccess = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(8001),
				Integer.valueOf(800));

		// When
		JobTimesheetAccess savedAccess = this.repository.save(newAccess);
		this.flushAndClear();

		// Then
		assertThat(savedAccess.getId()).isNotNull();
		Optional<JobTimesheetAccess> found = this.repository.findByJobIdAndAccountId(Integer.valueOf(8001),
				Integer.valueOf(800));
		assertThat(found).isPresent();
		assertThat(found.get().getJobId()).isEqualTo(Integer.valueOf(8001));
		assertThat(found.get().getAccountId()).isEqualTo(Integer.valueOf(800));
	}

	@Test
	@DisplayName("save updates existing JobTimesheetAccess")
	void testSaveExistingJobTimesheetAccessUpdatesSuccessfully() {
		// Given
		JobTimesheetAccess access = JobTimesheetAccessTestDataFactory.createJobTimesheetAccess(Integer.valueOf(9001),
				Integer.valueOf(900), JobTimesheetAccessTestDataFactory.DEFAULT_CAN_CREATE,
				JobTimesheetAccessTestDataFactory.CAN_CREATE_DISABLED,
				JobTimesheetAccessTestDataFactory.DEFAULT_CAN_DELETE);
		this.persistAndFlush(access);
		Integer accessId = access.getId();

		// When
		access.setCanEdit(JobTimesheetAccessTestDataFactory.DEFAULT_CAN_EDIT);
		access.setCanDelete(Integer.valueOf(1));
		JobTimesheetAccess updatedAccess = this.repository.save(access);
		this.flushAndClear();

		// Then
		assertThat(updatedAccess.getId()).isEqualTo(accessId);
		Optional<JobTimesheetAccess> found = this.repository.findByJobIdAndAccountId(Integer.valueOf(9001),
				Integer.valueOf(900));
		assertThat(found).isPresent();
		assertThat(found.get().getCanEdit()).isEqualTo(JobTimesheetAccessTestDataFactory.DEFAULT_CAN_EDIT);
		assertThat(found.get().getCanDelete()).isEqualTo(Integer.valueOf(1));
	}

	@Test
	@DisplayName("repository bean is injectable in slice context")
	void testRepositoryBeanIsInjectable() {
		// When
		JobTimesheetAccessJpaRepository resolved = this.repository;

		// Then
		assertThat(resolved).isNotNull().isInstanceOf(JobTimesheetAccessJpaRepository.class);
	}

	static class NoDuplicateJsonWarningBootstrapper extends DefaultTestContextBootstrapper {

		@Override
		protected List<ContextCustomizerFactory> getContextCustomizerFactories() {
			List<ContextCustomizerFactory> factories = new ArrayList<>();
			for (ContextCustomizerFactory factory : super.getContextCustomizerFactories()) {
				if (!JobTimesheetAccessJpaRepositoryTests.DUPLICATE_JSON_OBJECT_CONTEXT_CUSTOMIZER_FACTORY
					.equals(factory.getClass().getName())) {
					factories.add(factory);
				}
			}
			return factories;
		}

	}

	@Configuration
	@EnableTransactionManagement
	@EnableJpaRepositories(basePackageClasses = JobTimesheetAccessJpaRepository.class)
	static class JobTimesheetAccessJpaTestApplication {

		@Bean
		DataSource dataSource() {
			return new EmbeddedDatabaseBuilder().setType(EmbeddedDatabaseType.H2).build();
		}

		@Bean
		LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource dataSource) {
			HibernateJpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
			vendorAdapter.setGenerateDdl(false);
			vendorAdapter.setShowSql(false);

			LocalContainerEntityManagerFactoryBean factoryBean = new LocalContainerEntityManagerFactoryBean();
			factoryBean.setDataSource(dataSource);
			factoryBean.setJpaVendorAdapter(vendorAdapter);
			factoryBean.setPackagesToScan(JobTimesheetAccess.class.getPackageName());
			factoryBean.setJpaPropertyMap(Map.of("hibernate.hbm2ddl.auto", "none"));
			return factoryBean;
		}

		@Bean
		PlatformTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
			return new JpaTransactionManager(entityManagerFactory);
		}

	}

}
