/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.CandidateLastActivitiesT;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CandidateLastActivitiesTRecord extends UpdatableRecordImpl<CandidateLastActivitiesTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>candidate_last_activities_t.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.candidate_id</code>. Candidate id from
	 * tblcandidate
	 */
	public void setCandidateId(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.candidate_id</code>. Candidate id from
	 * tblcandidate
	 */
	public Integer getCandidateId() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.calllog_id</code>. Last Calllog id
	 * from tblcalllog
	 */
	public void setCalllogId(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.calllog_id</code>. Last Calllog id
	 * from tblcalllog
	 */
	public Integer getCalllogId() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.calllog_created_on</code>. Last
	 * Calllog Created Timestamp
	 */
	public void setCalllogCreatedOn(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.calllog_created_on</code>. Last
	 * Calllog Created Timestamp
	 */
	public Integer getCalllogCreatedOn() {
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.calllog_created_by</code>. Last
	 * Calllog Created By
	 */
	public void setCalllogCreatedBy(Integer value) {
		set(4, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.calllog_created_by</code>. Last
	 * Calllog Created By
	 */
	public Integer getCalllogCreatedBy() {
		return (Integer) get(4);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.sms_id</code>. Last SMS id of
	 * conversation_message_t
	 */
	public void setSmsId(Integer value) {
		set(5, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.sms_id</code>. Last SMS id of
	 * conversation_message_t
	 */
	public Integer getSmsId() {
		return (Integer) get(5);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.sms_sent_on</code>. Last SMS Sent
	 * Timestamp
	 */
	public void setSmsSentOn(Integer value) {
		set(6, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.sms_sent_on</code>. Last SMS Sent
	 * Timestamp
	 */
	public Integer getSmsSentOn() {
		return (Integer) get(6);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.sms_sent_by</code>. Last SMS Sent By
	 */
	public void setSmsSentBy(Integer value) {
		set(7, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.sms_sent_by</code>. Last SMS Sent By
	 */
	public Integer getSmsSentBy() {
		return (Integer) get(7);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.email_sent_on</code>. Last Email Sent
	 * Timestamp
	 */
	public void setEmailSentOn(Integer value) {
		set(8, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.email_sent_on</code>. Last Email Sent
	 * Timestamp
	 */
	public Integer getEmailSentOn() {
		return (Integer) get(8);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.email_sent_by</code>. Last Email Sent
	 * By
	 */
	public void setEmailSentBy(Integer value) {
		set(9, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.email_sent_by</code>. Last Email Sent
	 * By
	 */
	public Integer getEmailSentBy() {
		return (Integer) get(9);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.last_communication_method</code>.
	 * Values can be email, sms, calllog, meeting,linkedin message
	 */
	public void setLastCommunicationMethod(String value) {
		set(10, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.last_communication_method</code>.
	 * Values can be email, sms, calllog, meeting,linkedin message
	 */
	public String getLastCommunicationMethod() {
		return (String) get(10);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.last_communication_timestamp</code>.
	 * Last Communication Timestamp
	 */
	public void setLastCommunicationTimestamp(Integer value) {
		set(11, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.last_communication_timestamp</code>.
	 * Last Communication Timestamp
	 */
	public Integer getLastCommunicationTimestamp() {
		return (Integer) get(11);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.meeting_id</code>. Stores ID of the
	 * last meeting associated with tblnotetaskappointment
	 */
	public void setMeetingId(Integer value) {
		set(12, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.meeting_id</code>. Stores ID of the
	 * last meeting associated with tblnotetaskappointment
	 */
	public Integer getMeetingId() {
		return (Integer) get(12);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.meeting_created_on</code>. Unix
	 * timestamp of when the meeting was created
	 */
	public void setMeetingCreatedOn(Integer value) {
		set(13, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.meeting_created_on</code>. Unix
	 * timestamp of when the meeting was created
	 */
	public Integer getMeetingCreatedOn() {
		return (Integer) get(13);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.meeting_created_by</code>. User ID of
	 * the person who created the meeting
	 */
	public void setMeetingCreatedBy(Integer value) {
		set(14, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.meeting_created_by</code>. User ID of
	 * the person who created the meeting
	 */
	public Integer getMeetingCreatedBy() {
		return (Integer) get(14);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.message_id</code>. Id of linkedin
	 * message sent from RCRM
	 */
	public void setMessageId(String value) {
		set(15, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.message_id</code>. Id of linkedin
	 * message sent from RCRM
	 */
	public String getMessageId() {
		return (String) get(15);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.message_sent_on</code>. Unix timestamp
	 * of linkedin message sent
	 */
	public void setMessageSentOn(Integer value) {
		set(16, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.message_sent_on</code>. Unix timestamp
	 * of linkedin message sent
	 */
	public Integer getMessageSentOn() {
		return (Integer) get(16);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.message_sent_by</code>. User ID of the
	 * person sended linkedin message
	 */
	public void setMessageSentBy(Integer value) {
		set(17, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.message_sent_by</code>. User ID of the
	 * person sended linkedin message
	 */
	public Integer getMessageSentBy() {
		return (Integer) get(17);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.note_id</code>. Stores ID of the last
	 * note associated with tblnotetaskappointment
	 */
	public void setNoteId(Integer value) {
		set(18, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.note_id</code>. Stores ID of the last
	 * note associated with tblnotetaskappointment
	 */
	public Integer getNoteId() {
		return (Integer) get(18);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.note_created_on</code>. Unix timestamp
	 * of when the note was created
	 */
	public void setNoteCreatedOn(Integer value) {
		set(19, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.note_created_on</code>. Unix timestamp
	 * of when the note was created
	 */
	public Integer getNoteCreatedOn() {
		return (Integer) get(19);
	}

	/**
	 * Setter for <code>candidate_last_activities_t.note_created_by</code>. User ID of the
	 * person who created the note
	 */
	public void setNoteCreatedBy(Integer value) {
		set(20, value);
	}

	/**
	 * Getter for <code>candidate_last_activities_t.note_created_by</code>. User ID of the
	 * person who created the note
	 */
	public Integer getNoteCreatedBy() {
		return (Integer) get(20);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CandidateLastActivitiesTRecord
	 */
	public CandidateLastActivitiesTRecord() {
		super(CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T);
	}

	/**
	 * Create a detached, initialised CandidateLastActivitiesTRecord
	 */
	public CandidateLastActivitiesTRecord(Integer id, Integer candidateId, Integer calllogId, Integer calllogCreatedOn,
			Integer calllogCreatedBy, Integer smsId, Integer smsSentOn, Integer smsSentBy, Integer emailSentOn,
			Integer emailSentBy, String lastCommunicationMethod, Integer lastCommunicationTimestamp, Integer meetingId,
			Integer meetingCreatedOn, Integer meetingCreatedBy, String messageId, Integer messageSentOn,
			Integer messageSentBy, Integer noteId, Integer noteCreatedOn, Integer noteCreatedBy) {
		super(CandidateLastActivitiesT.CANDIDATE_LAST_ACTIVITIES_T);

		setId(id);
		setCandidateId(candidateId);
		setCalllogId(calllogId);
		setCalllogCreatedOn(calllogCreatedOn);
		setCalllogCreatedBy(calllogCreatedBy);
		setSmsId(smsId);
		setSmsSentOn(smsSentOn);
		setSmsSentBy(smsSentBy);
		setEmailSentOn(emailSentOn);
		setEmailSentBy(emailSentBy);
		setLastCommunicationMethod(lastCommunicationMethod);
		setLastCommunicationTimestamp(lastCommunicationTimestamp);
		setMeetingId(meetingId);
		setMeetingCreatedOn(meetingCreatedOn);
		setMeetingCreatedBy(meetingCreatedBy);
		setMessageId(messageId);
		setMessageSentOn(messageSentOn);
		setMessageSentBy(messageSentBy);
		setNoteId(noteId);
		setNoteCreatedOn(noteCreatedOn);
		setNoteCreatedBy(noteCreatedBy);
		resetTouchedOnNotNull();
	}

}
