/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetSettingAssociationT;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * Table to store approvers associated with timesheet settings
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstTimesheetSettingAssociationTRecord extends UpdatableRecordImpl<CstTimesheetSettingAssociationTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>cst_timesheet_setting_association_t.id</code>. Primary key for the
	 * association record
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>cst_timesheet_setting_association_t.id</code>. Primary key for the
	 * association record
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>cst_timesheet_setting_association_t.job_id</code>. Job ID from
	 * tbljob (no FK)
	 */
	public void setJobId(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>cst_timesheet_setting_association_t.job_id</code>. Job ID from
	 * tbljob (no FK)
	 */
	public Integer getJobId() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>cst_timesheet_setting_association_t.contractor_id</code>.
	 * Contractor ID from tblcandidate (no FK)
	 */
	public void setContractorId(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>cst_timesheet_setting_association_t.contractor_id</code>.
	 * Contractor ID from tblcandidate (no FK)
	 */
	public Integer getContractorId() {
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CstTimesheetSettingAssociationTRecord
	 */
	public CstTimesheetSettingAssociationTRecord() {
		super(CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T);
	}

	/**
	 * Create a detached, initialised CstTimesheetSettingAssociationTRecord
	 */
	public CstTimesheetSettingAssociationTRecord(Integer id, Integer jobId, Integer contractorId) {
		super(CstTimesheetSettingAssociationT.CST_TIMESHEET_SETTING_ASSOCIATION_T);

		setId(id);
		setJobId(jobId);
		setContractorId(contractorId);
		resetTouchedOnNotNull();
	}

}
