/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetReimbursementT;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * Stores reimbursement line items linked to timesheets with payable/billable flags and
 * audit trail
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstTimesheetReimbursementTRecord extends UpdatableRecordImpl<CstTimesheetReimbursementTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.id</code>. Unique reimbursement
	 * record ID
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.id</code>. Unique reimbursement
	 * record ID
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.cst_timesheet_id</code>. Reference
	 * to the parent timesheet (cst_timesheet_t.id)
	 */
	public void setCstTimesheetId(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.cst_timesheet_id</code>. Reference
	 * to the parent timesheet (cst_timesheet_t.id)
	 */
	public Integer getCstTimesheetId() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.description</code>. Reimbursement
	 * description/details entered by user
	 */
	public void setDescription(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.description</code>. Reimbursement
	 * description/details entered by user
	 */
	public String getDescription() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.amount</code>. Reimbursement
	 * monetary amount (non-negative)
	 */
	public void setAmount(BigDecimal value) {
		set(3, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.amount</code>. Reimbursement
	 * monetary amount (non-negative)
	 */
	public BigDecimal getAmount() {
		return (BigDecimal) get(3);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.document_token</code>. Document
	 * token used to fetch the documents
	 */
	public void setDocumentToken(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.document_token</code>. Document
	 * token used to fetch the documents
	 */
	public String getDocumentToken() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.file_name</code>. Original file name
	 * of the attached document
	 */
	public void setFileName(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.file_name</code>. Original file name
	 * of the attached document
	 */
	public String getFileName() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.status</code>. Current workflow
	 * status (FK to cst_timesheet_reimbursement_status_type_t.id)
	 */
	public void setStatus(Integer value) {
		set(6, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.status</code>. Current workflow
	 * status (FK to cst_timesheet_reimbursement_status_type_t.id)
	 */
	public Integer getStatus() {
		return (Integer) get(6);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.is_payable</code>. Whether included
	 * in payable calculations (0=no, 1=yes)
	 */
	public void setIsPayable(Byte value) {
		set(7, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.is_payable</code>. Whether included
	 * in payable calculations (0=no, 1=yes)
	 */
	public Byte getIsPayable() {
		return (Byte) get(7);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.is_billable</code>. Whether included
	 * in billable calculations (0=no, 1=yes)
	 */
	public void setIsBillable(Byte value) {
		set(8, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.is_billable</code>. Whether included
	 * in billable calculations (0=no, 1=yes)
	 */
	public Byte getIsBillable() {
		return (Byte) get(8);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.currency_id</code>. Reference to the
	 * parent timesheet (tblcurrency.id)
	 */
	public void setCurrencyId(Integer value) {
		set(9, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.currency_id</code>. Reference to the
	 * parent timesheet (tblcurrency.id)
	 */
	public Integer getCurrencyId() {
		return (Integer) get(9);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.account_id</code>. Reference to the
	 * parent timesheet (tblaccount.id)
	 */
	public void setAccountId(Integer value) {
		set(10, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.account_id</code>. Reference to the
	 * parent timesheet (tblaccount.id)
	 */
	public Integer getAccountId() {
		return (Integer) get(10);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.added_by</code>. User ID who created
	 * the record
	 */
	public void setAddedBy(Integer value) {
		set(11, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.added_by</code>. User ID who created
	 * the record
	 */
	public Integer getAddedBy() {
		return (Integer) get(11);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.added_by_user_type_id</code>. User
	 * type of the actor who performed the action; references cst_user_type_t.id.
	 */
	public void setAddedByUserTypeId(Integer value) {
		set(12, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.added_by_user_type_id</code>. User
	 * type of the actor who performed the action; references cst_user_type_t.id.
	 */
	public Integer getAddedByUserTypeId() {
		return (Integer) get(12);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.added_on</code>. Creation timestamp
	 * (Unix epoch)
	 */
	public void setAddedOn(Integer value) {
		set(13, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.added_on</code>. Creation timestamp
	 * (Unix epoch)
	 */
	public Integer getAddedOn() {
		return (Integer) get(13);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.updated_by</code>. User ID who last
	 * updated the record
	 */
	public void setUpdatedBy(Integer value) {
		set(14, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.updated_by</code>. User ID who last
	 * updated the record
	 */
	public Integer getUpdatedBy() {
		return (Integer) get(14);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.updated_by_user_type_id</code>. User
	 * type of the actor who performed the action; references cst_user_type_t.id.
	 */
	public void setUpdatedByUserTypeId(Integer value) {
		set(15, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.updated_by_user_type_id</code>. User
	 * type of the actor who performed the action; references cst_user_type_t.id.
	 */
	public Integer getUpdatedByUserTypeId() {
		return (Integer) get(15);
	}

	/**
	 * Setter for <code>cst_timesheet_reimbursement_t.updated_on</code>. Last update
	 * timestamp (Unix epoch)
	 */
	public void setUpdatedOn(Integer value) {
		set(16, value);
	}

	/**
	 * Getter for <code>cst_timesheet_reimbursement_t.updated_on</code>. Last update
	 * timestamp (Unix epoch)
	 */
	public Integer getUpdatedOn() {
		return (Integer) get(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CstTimesheetReimbursementTRecord
	 */
	public CstTimesheetReimbursementTRecord() {
		super(CstTimesheetReimbursementT.CST_TIMESHEET_REIMBURSEMENT_T);
	}

	/**
	 * Create a detached, initialised CstTimesheetReimbursementTRecord
	 */
	public CstTimesheetReimbursementTRecord(Integer id, Integer cstTimesheetId, String description, BigDecimal amount,
			String documentToken, String fileName, Integer status, Byte isPayable, Byte isBillable, Integer currencyId,
			Integer accountId, Integer addedBy, Integer addedByUserTypeId, Integer addedOn, Integer updatedBy,
			Integer updatedByUserTypeId, Integer updatedOn) {
		super(CstTimesheetReimbursementT.CST_TIMESHEET_REIMBURSEMENT_T);

		setId(id);
		setCstTimesheetId(cstTimesheetId);
		setDescription(description);
		setAmount(amount);
		setDocumentToken(documentToken);
		setFileName(fileName);
		setStatus(status);
		setIsPayable(isPayable);
		setIsBillable(isBillable);
		setCurrencyId(currencyId);
		setAccountId(accountId);
		setAddedBy(addedBy);
		setAddedByUserTypeId(addedByUserTypeId);
		setAddedOn(addedOn);
		setUpdatedBy(updatedBy);
		setUpdatedByUserTypeId(updatedByUserTypeId);
		setUpdatedOn(updatedOn);
		resetTouchedOnNotNull();
	}

}
