/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetT;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * Table to store timesheet records including payment and billing data
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstTimesheetTRecord extends UpdatableRecordImpl<CstTimesheetTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>cst_timesheet_t.id</code>. Primary key for the timesheet record
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.id</code>. Primary key for the timesheet record
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>cst_timesheet_t.period_start</code>. Start date and time of the
	 * timesheet period
	 */
	public void setPeriodStart(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.period_start</code>. Start date and time of the
	 * timesheet period
	 */
	public Integer getPeriodStart() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>cst_timesheet_t.period_end</code>. End date and time of the
	 * timesheet period
	 */
	public void setPeriodEnd(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.period_end</code>. End date and time of the
	 * timesheet period
	 */
	public Integer getPeriodEnd() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>cst_timesheet_t.pay_data</code>. Payment data with up to 2 decimal
	 * places
	 */
	public void setPayData(BigDecimal value) {
		set(3, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.pay_data</code>. Payment data with up to 2 decimal
	 * places
	 */
	public BigDecimal getPayData() {
		return (BigDecimal) get(3);
	}

	/**
	 * Setter for <code>cst_timesheet_t.bill_data</code>. Billing data with up to 2
	 * decimal places
	 */
	public void setBillData(BigDecimal value) {
		set(4, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.bill_data</code>. Billing data with up to 2
	 * decimal places
	 */
	public BigDecimal getBillData() {
		return (BigDecimal) get(4);
	}

	/**
	 * Setter for <code>cst_timesheet_t.added_on</code>. Timestamp when the record was
	 * added
	 */
	public void setAddedOn(Integer value) {
		set(5, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.added_on</code>. Timestamp when the record was
	 * added
	 */
	public Integer getAddedOn() {
		return (Integer) get(5);
	}

	/**
	 * Setter for <code>cst_timesheet_t.added_by</code>. User ID who added the record
	 */
	public void setAddedBy(Integer value) {
		set(6, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.added_by</code>. User ID who added the record
	 */
	public Integer getAddedBy() {
		return (Integer) get(6);
	}

	/**
	 * Setter for <code>cst_timesheet_t.added_by_user_type_id</code>. User type ID who
	 * added the record, references cst_user_type_t PK
	 */
	public void setAddedByUserTypeId(Integer value) {
		set(7, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.added_by_user_type_id</code>. User type ID who
	 * added the record, references cst_user_type_t PK
	 */
	public Integer getAddedByUserTypeId() {
		return (Integer) get(7);
	}

	/**
	 * Setter for <code>cst_timesheet_t.updated_on</code>. Timestamp when the record was
	 * last updated
	 */
	public void setUpdatedOn(Integer value) {
		set(8, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.updated_on</code>. Timestamp when the record was
	 * last updated
	 */
	public Integer getUpdatedOn() {
		return (Integer) get(8);
	}

	/**
	 * Setter for <code>cst_timesheet_t.updated_by</code>. User ID who last updated the
	 * record
	 */
	public void setUpdatedBy(Integer value) {
		set(9, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.updated_by</code>. User ID who last updated the
	 * record
	 */
	public Integer getUpdatedBy() {
		return (Integer) get(9);
	}

	/**
	 * Setter for <code>cst_timesheet_t.updated_by_user_type_id</code>. User type ID who
	 * last updated the record, references cst_user_type_t PK
	 */
	public void setUpdatedByUserTypeId(Integer value) {
		set(10, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.updated_by_user_type_id</code>. User type ID who
	 * last updated the record, references cst_user_type_t PK
	 */
	public Integer getUpdatedByUserTypeId() {
		return (Integer) get(10);
	}

	/**
	 * Setter for <code>cst_timesheet_t.timesheet_setting_id</code>. Timesheet setting ID,
	 * references cst_timesheet_setting_t PK
	 */
	public void setTimesheetSettingId(Integer value) {
		set(11, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.timesheet_setting_id</code>. Timesheet setting ID,
	 * references cst_timesheet_setting_t PK
	 */
	public Integer getTimesheetSettingId() {
		return (Integer) get(11);
	}

	/**
	 * Setter for <code>cst_timesheet_t.timesheet_bill_status_id</code>. Timesheet billing
	 * status ID, references cst_timesheet_bill_status_type_t PK
	 */
	public void setTimesheetBillStatusId(Integer value) {
		set(12, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.timesheet_bill_status_id</code>. Timesheet billing
	 * status ID, references cst_timesheet_bill_status_type_t PK
	 */
	public Integer getTimesheetBillStatusId() {
		return (Integer) get(12);
	}

	/**
	 * Setter for <code>cst_timesheet_t.timesheet_pay_status_id</code>. Timesheet payment
	 * status ID, references timesheet_pay_status_t PK
	 */
	public void setTimesheetPayStatusId(Integer value) {
		set(13, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.timesheet_pay_status_id</code>. Timesheet payment
	 * status ID, references timesheet_pay_status_t PK
	 */
	public Integer getTimesheetPayStatusId() {
		return (Integer) get(13);
	}

	/**
	 * Setter for <code>cst_timesheet_t.account_id</code>. Account Id for the Timesheet
	 */
	public void setAccountId(Integer value) {
		set(14, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.account_id</code>. Account Id for the Timesheet
	 */
	public Integer getAccountId() {
		return (Integer) get(14);
	}

	/**
	 * Setter for <code>cst_timesheet_t.migration_reserved1</code>. column for migration
	 * data
	 */
	public void setMigrationReserved1(String value) {
		set(15, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.migration_reserved1</code>. column for migration
	 * data
	 */
	public String getMigrationReserved1() {
		return (String) get(15);
	}

	/**
	 * Setter for <code>cst_timesheet_t.migration_reserved2</code>. column for migration
	 * data
	 */
	public void setMigrationReserved2(String value) {
		set(16, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.migration_reserved2</code>. column for migration
	 * data
	 */
	public String getMigrationReserved2() {
		return (String) get(16);
	}

	/**
	 * Setter for <code>cst_timesheet_t.total_time</code>. Total time in seconds
	 */
	public void setTotalTime(Integer value) {
		set(17, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.total_time</code>. Total time in seconds
	 */
	public Integer getTotalTime() {
		return (Integer) get(17);
	}

	/**
	 * Setter for <code>cst_timesheet_t.total_work_time</code>. Total work time in seconds
	 */
	public void setTotalWorkTime(Integer value) {
		set(18, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.total_work_time</code>. Total work time in seconds
	 */
	public Integer getTotalWorkTime() {
		return (Integer) get(18);
	}

	/**
	 * Setter for <code>cst_timesheet_t.total_overtime</code>. Total overtime in seconds
	 */
	public void setTotalOvertime(Integer value) {
		set(19, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.total_overtime</code>. Total overtime in seconds
	 */
	public Integer getTotalOvertime() {
		return (Integer) get(19);
	}

	/**
	 * Setter for <code>cst_timesheet_t.total_weekly_overtime</code>. Net weekly overtime
	 * duration in seconds (rule engine aggregate for the timesheet period)
	 */
	public void setTotalWeeklyOvertime(Integer value) {
		set(20, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.total_weekly_overtime</code>. Net weekly overtime
	 * duration in seconds (rule engine aggregate for the timesheet period)
	 */
	public Integer getTotalWeeklyOvertime() {
		return (Integer) get(20);
	}

	/**
	 * Setter for <code>cst_timesheet_t.total_regular_hour</code>. total regular time of
	 * timesheet
	 */
	public void setTotalRegularHour(Integer value) {
		set(21, value);
	}

	/**
	 * Getter for <code>cst_timesheet_t.total_regular_hour</code>. total regular time of
	 * timesheet
	 */
	public Integer getTotalRegularHour() {
		return (Integer) get(21);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CstTimesheetTRecord
	 */
	public CstTimesheetTRecord() {
		super(CstTimesheetT.CST_TIMESHEET_T);
	}

	/**
	 * Create a detached, initialised CstTimesheetTRecord
	 */
	public CstTimesheetTRecord(Integer id, Integer periodStart, Integer periodEnd, BigDecimal payData,
			BigDecimal billData, Integer addedOn, Integer addedBy, Integer addedByUserTypeId, Integer updatedOn,
			Integer updatedBy, Integer updatedByUserTypeId, Integer timesheetSettingId, Integer timesheetBillStatusId,
			Integer timesheetPayStatusId, Integer accountId, String migrationReserved1, String migrationReserved2,
			Integer totalTime, Integer totalWorkTime, Integer totalOvertime, Integer totalWeeklyOvertime,
			Integer totalRegularHour) {
		super(CstTimesheetT.CST_TIMESHEET_T);

		setId(id);
		setPeriodStart(periodStart);
		setPeriodEnd(periodEnd);
		setPayData(payData);
		setBillData(billData);
		setAddedOn(addedOn);
		setAddedBy(addedBy);
		setAddedByUserTypeId(addedByUserTypeId);
		setUpdatedOn(updatedOn);
		setUpdatedBy(updatedBy);
		setUpdatedByUserTypeId(updatedByUserTypeId);
		setTimesheetSettingId(timesheetSettingId);
		setTimesheetBillStatusId(timesheetBillStatusId);
		setTimesheetPayStatusId(timesheetPayStatusId);
		setAccountId(accountId);
		setMigrationReserved1(migrationReserved1);
		setMigrationReserved2(migrationReserved2);
		setTotalTime(totalTime);
		setTotalWorkTime(totalWorkTime);
		setTotalOvertime(totalOvertime);
		setTotalWeeklyOvertime(totalWeeklyOvertime);
		setTotalRegularHour(totalRegularHour);
		resetTouchedOnNotNull();
	}

}
