/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.CstTimesheetApprovalT;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * Table to store timesheet approval records
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstTimesheetApprovalTRecord extends UpdatableRecordImpl<CstTimesheetApprovalTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>cst_timesheet_approval_t.id</code>. Primary key for the timesheet
	 * approval record
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>cst_timesheet_approval_t.id</code>. Primary key for the timesheet
	 * approval record
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>cst_timesheet_approval_t.timesheet_id</code>. Foreign key
	 * referencing cst_timesheet_t PK
	 */
	public void setTimesheetId(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>cst_timesheet_approval_t.timesheet_id</code>. Foreign key
	 * referencing cst_timesheet_t PK
	 */
	public Integer getTimesheetId() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>cst_timesheet_approval_t.user_type_id</code>. Foreign key
	 * referencing cst_user_type_t PK
	 */
	public void setUserTypeId(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>cst_timesheet_approval_t.user_type_id</code>. Foreign key
	 * referencing cst_user_type_t PK
	 */
	public Integer getUserTypeId() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>cst_timesheet_approval_t.entity_id</code>. Foreign key referencing
	 * the PK of either contractor_t or agency_contact_t (polymorphic field)
	 */
	public void setEntityId(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>cst_timesheet_approval_t.entity_id</code>. Foreign key referencing
	 * the PK of either contractor_t or agency_contact_t (polymorphic field)
	 */
	public Integer getEntityId() {
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>cst_timesheet_approval_t.timesheet_approval_status_type_id</code>.
	 * Foreign key referencing cst_timesheet_approval_status_type_t PK
	 */
	public void setTimesheetApprovalStatusTypeId(Integer value) {
		set(4, value);
	}

	/**
	 * Getter for <code>cst_timesheet_approval_t.timesheet_approval_status_type_id</code>.
	 * Foreign key referencing cst_timesheet_approval_status_type_t PK
	 */
	public Integer getTimesheetApprovalStatusTypeId() {
		return (Integer) get(4);
	}

	/**
	 * Setter for <code>cst_timesheet_approval_t.remark</code>. Additional remarks or
	 * notes for the approval
	 */
	public void setRemark(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>cst_timesheet_approval_t.remark</code>. Additional remarks or
	 * notes for the approval
	 */
	public String getRemark() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>cst_timesheet_approval_t.created_on</code>. Timestamp when the
	 * record was last updated
	 */
	public void setCreatedOn(Integer value) {
		set(6, value);
	}

	/**
	 * Getter for <code>cst_timesheet_approval_t.created_on</code>. Timestamp when the
	 * record was last updated
	 */
	public Integer getCreatedOn() {
		return (Integer) get(6);
	}

	/**
	 * Setter for <code>cst_timesheet_approval_t.migration_reserved1</code>. column for
	 * migration data
	 */
	public void setMigrationReserved1(String value) {
		set(7, value);
	}

	/**
	 * Getter for <code>cst_timesheet_approval_t.migration_reserved1</code>. column for
	 * migration data
	 */
	public String getMigrationReserved1() {
		return (String) get(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CstTimesheetApprovalTRecord
	 */
	public CstTimesheetApprovalTRecord() {
		super(CstTimesheetApprovalT.CST_TIMESHEET_APPROVAL_T);
	}

	/**
	 * Create a detached, initialised CstTimesheetApprovalTRecord
	 */
	public CstTimesheetApprovalTRecord(Integer id, Integer timesheetId, Integer userTypeId, Integer entityId,
			Integer timesheetApprovalStatusTypeId, String remark, Integer createdOn, String migrationReserved1) {
		super(CstTimesheetApprovalT.CST_TIMESHEET_APPROVAL_T);

		setId(id);
		setTimesheetId(timesheetId);
		setUserTypeId(userTypeId);
		setEntityId(entityId);
		setTimesheetApprovalStatusTypeId(timesheetApprovalStatusTypeId);
		setRemark(remark);
		setCreatedOn(createdOn);
		setMigrationReserved1(migrationReserved1);
		resetTouchedOnNotNull();
	}

}
