/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.CstTimeLogIntervalT;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * Store time log interval
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CstTimeLogIntervalTRecord extends UpdatableRecordImpl<CstTimeLogIntervalTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>cst_time_log_interval_t.id</code>. Record ID
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>cst_time_log_interval_t.id</code>. Record ID
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>cst_time_log_interval_t.time_log_id</code>. Referencing
	 * cst_time_log_t
	 */
	public void setTimeLogId(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>cst_time_log_interval_t.time_log_id</code>. Referencing
	 * cst_time_log_t
	 */
	public Integer getTimeLogId() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>cst_time_log_interval_t.work_start_time</code>. Start time of the
	 * work period
	 */
	public void setWorkStartTime(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>cst_time_log_interval_t.work_start_time</code>. Start time of the
	 * work period
	 */
	public Integer getWorkStartTime() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>cst_time_log_interval_t.work_end_time</code>. End time of the work
	 * period
	 */
	public void setWorkEndTime(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>cst_time_log_interval_t.work_end_time</code>. End time of the work
	 * period
	 */
	public Integer getWorkEndTime() {
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>cst_time_log_interval_t.range_based_remark</code>. Remarks for the
	 * time log entry
	 */
	public void setRangeBasedRemark(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>cst_time_log_interval_t.range_based_remark</code>. Remarks for the
	 * time log entry
	 */
	public String getRangeBasedRemark() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>cst_time_log_interval_t.break_interval</code>. Break interval data
	 * in JSON format
	 */
	public void setBreakInterval(JSON value) {
		set(5, value);
	}

	/**
	 * Getter for <code>cst_time_log_interval_t.break_interval</code>. Break interval data
	 * in JSON format
	 */
	public JSON getBreakInterval() {
		return (JSON) get(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CstTimeLogIntervalTRecord
	 */
	public CstTimeLogIntervalTRecord() {
		super(CstTimeLogIntervalT.CST_TIME_LOG_INTERVAL_T);
	}

	/**
	 * Create a detached, initialised CstTimeLogIntervalTRecord
	 */
	public CstTimeLogIntervalTRecord(Integer id, Integer timeLogId, Integer workStartTime, Integer workEndTime,
			String rangeBasedRemark, JSON breakInterval) {
		super(CstTimeLogIntervalT.CST_TIME_LOG_INTERVAL_T);

		setId(id);
		setTimeLogId(timeLogId);
		setWorkStartTime(workStartTime);
		setWorkEndTime(workEndTime);
		setRangeBasedRemark(rangeBasedRemark);
		setBreakInterval(breakInterval);
		resetTouchedOnNotNull();
	}

}
