/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.JobSecondaryContactsT;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobSecondaryContactsTRecord extends UpdatableRecordImpl<JobSecondaryContactsTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>job_secondary_contacts_t.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>job_secondary_contacts_t.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>job_secondary_contacts_t.job_id</code>.
	 */
	public void setJobId(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>job_secondary_contacts_t.job_id</code>.
	 */
	public Integer getJobId() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>job_secondary_contacts_t.contact_id</code>.
	 */
	public void setContactId(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>job_secondary_contacts_t.contact_id</code>.
	 */
	public Integer getContactId() {
		return (Integer) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JobSecondaryContactsTRecord
	 */
	public JobSecondaryContactsTRecord() {
		super(JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T);
	}

	/**
	 * Create a detached, initialised JobSecondaryContactsTRecord
	 */
	public JobSecondaryContactsTRecord(Integer id, Integer jobId, Integer contactId) {
		super(JobSecondaryContactsT.JOB_SECONDARY_CONTACTS_T);

		setId(id);
		setJobId(jobId);
		setContactId(contactId);
		resetTouchedOnNotNull();
	}

}
