/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.OffLimitStatusColourT;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OffLimitStatusColourTRecord extends UpdatableRecordImpl<OffLimitStatusColourTRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>off_limit_status_colour_t.offlimit_status_colour_id</code>.
	 */
	public void setOfflimitStatusColourId(String value) {
		set(0, value);
	}

	/**
	 * Getter for <code>off_limit_status_colour_t.offlimit_status_colour_id</code>.
	 */
	public String getOfflimitStatusColourId() {
		return (String) get(0);
	}

	/**
	 * Setter for <code>off_limit_status_colour_t.background_color_hex</code>. Background
	 * colour for off-limit status
	 */
	public void setBackgroundColorHex(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>off_limit_status_colour_t.background_color_hex</code>. Background
	 * colour for off-limit status
	 */
	public String getBackgroundColorHex() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>off_limit_status_colour_t.text_color_hex</code>. Background colour
	 * for off-limit status
	 */
	public void setTextColorHex(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>off_limit_status_colour_t.text_color_hex</code>. Background colour
	 * for off-limit status
	 */
	public String getTextColorHex() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>off_limit_status_colour_t.hover_color_hex</code>. Hover colour for
	 * off-limit status
	 */
	public void setHoverColorHex(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>off_limit_status_colour_t.hover_color_hex</code>. Hover colour for
	 * off-limit status
	 */
	public String getHoverColorHex() {
		return (String) get(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OffLimitStatusColourTRecord
	 */
	public OffLimitStatusColourTRecord() {
		super(OffLimitStatusColourT.OFF_LIMIT_STATUS_COLOUR_T);
	}

	/**
	 * Create a detached, initialised OffLimitStatusColourTRecord
	 */
	public OffLimitStatusColourTRecord(String offlimitStatusColourId, String backgroundColorHex, String textColorHex,
			String hoverColorHex) {
		super(OffLimitStatusColourT.OFF_LIMIT_STATUS_COLOUR_T);

		setOfflimitStatusColourId(offlimitStatusColourId);
		setBackgroundColorHex(backgroundColorHex);
		setTextColorHex(textColorHex);
		setHoverColorHex(hoverColorHex);
		resetTouchedOnNotNull();
	}

}
