/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.Tblcontact;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TblcontactRecord extends UpdatableRecordImpl<TblcontactRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>tblcontact.id</code>. Primary key for the table.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>tblcontact.id</code>. Primary key for the table.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>tblcontact.srno</code>. This serial number is for user to identify
	 * the record by id. This value is generated account wise. There will be same srno for
	 * different accounts but not in same account.
	 */
	public void setSrno(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>tblcontact.srno</code>. This serial number is for user to identify
	 * the record by id. This value is generated account wise. There will be same srno for
	 * different accounts but not in same account.
	 */
	public Integer getSrno() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>tblcontact.companyid</code>. ID of the company which is associated
	 * with contact. Reference - tblcompany
	 */
	public void setCompanyid(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>tblcontact.companyid</code>. ID of the company which is associated
	 * with contact. Reference - tblcompany
	 */
	public Integer getCompanyid() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>tblcontact.companyslug</code>. Slug of company associated with
	 * contact.
	 */
	public void setCompanyslug(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>tblcontact.companyslug</code>. Slug of company associated with
	 * contact.
	 */
	public String getCompanyslug() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>tblcontact.firstname</code>. First Name of the contact.
	 */
	public void setFirstname(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>tblcontact.firstname</code>. First Name of the contact.
	 */
	public String getFirstname() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>tblcontact.lastname</code>. Last Name of the contact.
	 *
	 */
	public void setLastname(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>tblcontact.lastname</code>. Last Name of the contact.
	 *
	 */
	public String getLastname() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>tblcontact.email</code>. Email address of the contact.
	 */
	public void setEmail(String value) {
		set(6, value);
	}

	/**
	 * Getter for <code>tblcontact.email</code>. Email address of the contact.
	 */
	public String getEmail() {
		return (String) get(6);
	}

	/**
	 * Setter for <code>tblcontact.contactnumber</code>.
	 */
	public void setContactnumber(String value) {
		set(7, value);
	}

	/**
	 * Getter for <code>tblcontact.contactnumber</code>.
	 */
	public String getContactnumber() {
		return (String) get(7);
	}

	/**
	 * Setter for <code>tblcontact.photo</code>.
	 */
	public void setPhoto(String value) {
		set(8, value);
	}

	/**
	 * Getter for <code>tblcontact.photo</code>.
	 */
	public String getPhoto() {
		return (String) get(8);
	}

	/**
	 * Setter for <code>tblcontact.slug</code>. Unique value for the contact generated
	 * using trigger.
	 */
	public void setSlug(String value) {
		set(9, value);
	}

	/**
	 * Getter for <code>tblcontact.slug</code>. Unique value for the contact generated
	 * using trigger.
	 */
	public String getSlug() {
		return (String) get(9);
	}

	/**
	 * Setter for <code>tblcontact.ownerid</code>. User id who owns the record. Reference
	 * - tbluser
	 */
	public void setOwnerid(Integer value) {
		set(10, value);
	}

	/**
	 * Getter for <code>tblcontact.ownerid</code>. User id who owns the record. Reference
	 * - tbluser
	 */
	public Integer getOwnerid() {
		return (Integer) get(10);
	}

	/**
	 * Setter for <code>tblcontact.accountid</code>. Account id for which contact is
	 * created.
	 */
	public void setAccountid(Integer value) {
		set(11, value);
	}

	/**
	 * Getter for <code>tblcontact.accountid</code>. Account id for which contact is
	 * created.
	 */
	public Integer getAccountid() {
		return (Integer) get(11);
	}

	/**
	 * Setter for <code>tblcontact.createdby</code>. User id who created the record.
	 */
	public void setCreatedby(Integer value) {
		set(12, value);
	}

	/**
	 * Getter for <code>tblcontact.createdby</code>. User id who created the record.
	 */
	public Integer getCreatedby() {
		return (Integer) get(12);
	}

	/**
	 * Setter for <code>tblcontact.createdon</code>. Unix timestamp when contact is
	 * created.
	 */
	public void setCreatedon(Integer value) {
		set(13, value);
	}

	/**
	 * Getter for <code>tblcontact.createdon</code>. Unix timestamp when contact is
	 * created.
	 */
	public Integer getCreatedon() {
		return (Integer) get(13);
	}

	/**
	 * Setter for <code>tblcontact.updatedby</code>. User id who updated the contact last
	 * time.
	 */
	public void setUpdatedby(Integer value) {
		set(14, value);
	}

	/**
	 * Getter for <code>tblcontact.updatedby</code>. User id who updated the contact last
	 * time.
	 */
	public Integer getUpdatedby() {
		return (Integer) get(14);
	}

	/**
	 * Setter for <code>tblcontact.updatedon</code>. Unix timestamp when contact is
	 * updated.
	 */
	public void setUpdatedon(Integer value) {
		set(15, value);
	}

	/**
	 * Getter for <code>tblcontact.updatedon</code>. Unix timestamp when contact is
	 * updated.
	 */
	public Integer getUpdatedon() {
		return (Integer) get(15);
	}

	/**
	 * Setter for <code>tblcontact.city</code>. City of the contact.
	 */
	public void setCity(String value) {
		set(16, value);
	}

	/**
	 * Getter for <code>tblcontact.city</code>. City of the contact.
	 */
	public String getCity() {
		return (String) get(16);
	}

	/**
	 * Setter for <code>tblcontact.lat</code>. Latitude - Used for radius search.
	 */
	public void setLat(Integer value) {
		set(17, value);
	}

	/**
	 * Getter for <code>tblcontact.lat</code>. Latitude - Used for radius search.
	 */
	public Integer getLat() {
		return (Integer) get(17);
	}

	/**
	 * Setter for <code>tblcontact.lng</code>. Longitude - Used for radius search.
	 */
	public void setLng(Integer value) {
		set(18, value);
	}

	/**
	 * Getter for <code>tblcontact.lng</code>. Longitude - Used for radius search.
	 */
	public Integer getLng() {
		return (Integer) get(18);
	}

	/**
	 * Setter for <code>tblcontact.address</code>. Full address of the contact.
	 */
	public void setAddress(String value) {
		set(19, value);
	}

	/**
	 * Getter for <code>tblcontact.address</code>. Full address of the contact.
	 */
	public String getAddress() {
		return (String) get(19);
	}

	/**
	 * Setter for <code>tblcontact.locality</code>. Locality of the contact.
	 */
	public void setLocality(String value) {
		set(20, value);
	}

	/**
	 * Getter for <code>tblcontact.locality</code>. Locality of the contact.
	 */
	public String getLocality() {
		return (String) get(20);
	}

	/**
	 * Setter for <code>tblcontact.deleted</code>.
	 */
	public void setDeleted(Byte value) {
		set(21, value);
	}

	/**
	 * Getter for <code>tblcontact.deleted</code>.
	 */
	public Byte getDeleted() {
		return (Byte) get(21);
	}

	/**
	 * Setter for <code>tblcontact.designation</code>. Title/Designation of the contact.
	 */
	public void setDesignation(String value) {
		set(22, value);
	}

	/**
	 * Getter for <code>tblcontact.designation</code>. Title/Designation of the contact.
	 */
	public String getDesignation() {
		return (String) get(22);
	}

	/**
	 * Setter for <code>tblcontact.profilefacebook</code>. Facebook Profile URL of the
	 * contact.
	 */
	public void setProfilefacebook(String value) {
		set(23, value);
	}

	/**
	 * Getter for <code>tblcontact.profilefacebook</code>. Facebook Profile URL of the
	 * contact.
	 */
	public String getProfilefacebook() {
		return (String) get(23);
	}

	/**
	 * Setter for <code>tblcontact.profiletwitter</code>. Twitter Profile URL of the
	 * contact.
	 */
	public void setProfiletwitter(String value) {
		set(24, value);
	}

	/**
	 * Getter for <code>tblcontact.profiletwitter</code>. Twitter Profile URL of the
	 * contact.
	 */
	public String getProfiletwitter() {
		return (String) get(24);
	}

	/**
	 * Setter for <code>tblcontact.profilelinkedin</code>. Linkedin Profile URL of the
	 * contact.
	 */
	public void setProfilelinkedin(String value) {
		set(25, value);
	}

	/**
	 * Getter for <code>tblcontact.profilelinkedin</code>. Linkedin Profile URL of the
	 * contact.
	 */
	public String getProfilelinkedin() {
		return (String) get(25);
	}

	/**
	 * Setter for <code>tblcontact.stageid</code>. Contact stage id which reference
	 * tblcontactstage.
	 */
	public void setStageid(Integer value) {
		set(26, value);
	}

	/**
	 * Getter for <code>tblcontact.stageid</code>. Contact stage id which reference
	 * tblcontactstage.
	 */
	public Integer getStageid() {
		return (Integer) get(26);
	}

	/**
	 * Setter for <code>tblcontact.canaccess</code>. User ids who is not owner and not
	 * having full access but need to see the record (comma separated).
	 */
	public void setCanaccess(String value) {
		set(27, value);
	}

	/**
	 * Getter for <code>tblcontact.canaccess</code>. User ids who is not owner and not
	 * having full access but need to see the record (comma separated).
	 */
	public String getCanaccess() {
		return (String) get(27);
	}

	/**
	 * Setter for <code>tblcontact.relatedtocandidate</code>. Candidate slug if the
	 * contact is related to any candidate.
	 */
	public void setRelatedtocandidate(String value) {
		set(28, value);
	}

	/**
	 * Getter for <code>tblcontact.relatedtocandidate</code>. Candidate slug if the
	 * contact is related to any candidate.
	 */
	public String getRelatedtocandidate() {
		return (String) get(28);
	}

	/**
	 * Setter for <code>tblcontact.sourceid</code>.
	 */
	public void setSourceid(Integer value) {
		set(29, value);
	}

	/**
	 * Getter for <code>tblcontact.sourceid</code>.
	 */
	public Integer getSourceid() {
		return (Integer) get(29);
	}

	/**
	 * Setter for <code>tblcontact.migration_reserved1</code>.
	 */
	public void setMigrationReserved1(String value) {
		set(30, value);
	}

	/**
	 * Getter for <code>tblcontact.migration_reserved1</code>.
	 */
	public String getMigrationReserved1() {
		return (String) get(30);
	}

	/**
	 * Setter for <code>tblcontact.migration_reserved2</code>.
	 */
	public void setMigrationReserved2(String value) {
		set(31, value);
	}

	/**
	 * Getter for <code>tblcontact.migration_reserved2</code>.
	 */
	public String getMigrationReserved2() {
		return (String) get(31);
	}

	/**
	 * Setter for <code>tblcontact.email_opt_out</code>. Option to opt out from receiving
	 * the emails
	 */
	public void setEmailOptOut(Byte value) {
		set(32, value);
	}

	/**
	 * Getter for <code>tblcontact.email_opt_out</code>. Option to opt out from receiving
	 * the emails
	 */
	public Byte getEmailOptOut() {
		return (Byte) get(32);
	}

	/**
	 * Setter for <code>tblcontact.vms_mapped</code>. 0 - not mapped, 1 - mapped
	 */
	public void setVmsMapped(Byte value) {
		set(33, value);
	}

	/**
	 * Getter for <code>tblcontact.vms_mapped</code>. 0 - not mapped, 1 - mapped
	 */
	public Byte getVmsMapped() {
		return (Byte) get(33);
	}

	/**
	 * Setter for <code>tblcontact.sms_consent</code>.
	 */
	public void setSmsConsent(Byte value) {
		set(34, value);
	}

	/**
	 * Getter for <code>tblcontact.sms_consent</code>.
	 */
	public Byte getSmsConsent() {
		return (Byte) get(34);
	}

	/**
	 * Setter for <code>tblcontact.profilexing</code>.
	 */
	public void setProfilexing(String value) {
		set(35, value);
	}

	/**
	 * Getter for <code>tblcontact.profilexing</code>.
	 */
	public String getProfilexing() {
		return (String) get(35);
	}

	/**
	 * Setter for <code>tblcontact.email_opt_out_source</code>.
	 */
	public void setEmailOptOutSource(Byte value) {
		set(36, value);
	}

	/**
	 * Getter for <code>tblcontact.email_opt_out_source</code>.
	 */
	public Byte getEmailOptOutSource() {
		return (Byte) get(36);
	}

	/**
	 * Setter for <code>tblcontact.merge_flag</code>.
	 */
	public void setMergeFlag(Byte value) {
		set(37, value);
	}

	/**
	 * Getter for <code>tblcontact.merge_flag</code>.
	 */
	public Byte getMergeFlag() {
		return (Byte) get(37);
	}

	/**
	 * Setter for <code>tblcontact.sms_opt_out</code>.
	 */
	public void setSmsOptOut(Byte value) {
		set(38, value);
	}

	/**
	 * Getter for <code>tblcontact.sms_opt_out</code>.
	 */
	public Byte getSmsOptOut() {
		return (Byte) get(38);
	}

	/**
	 * Setter for <code>tblcontact.formatted_profile_linkedin</code>.
	 */
	public void setFormattedProfileLinkedin(String value) {
		set(39, value);
	}

	/**
	 * Getter for <code>tblcontact.formatted_profile_linkedin</code>.
	 */
	public String getFormattedProfileLinkedin() {
		return (String) get(39);
	}

	/**
	 * Setter for <code>tblcontact.state</code>. Column to store State of the contact
	 * address
	 */
	public void setState(String value) {
		set(40, value);
	}

	/**
	 * Getter for <code>tblcontact.state</code>. Column to store State of the contact
	 * address
	 */
	public String getState() {
		return (String) get(40);
	}

	/**
	 * Setter for <code>tblcontact.country</code>. Column to store country of the contact
	 * address
	 */
	public void setCountry(String value) {
		set(41, value);
	}

	/**
	 * Getter for <code>tblcontact.country</code>. Column to store country of the contact
	 * address
	 */
	public String getCountry() {
		return (String) get(41);
	}

	/**
	 * Setter for <code>tblcontact.postal_code</code>. Column to store Postal code of the
	 * contact address
	 */
	public void setPostalCode(String value) {
		set(42, value);
	}

	/**
	 * Getter for <code>tblcontact.postal_code</code>. Column to store Postal code of the
	 * contact address
	 */
	public String getPostalCode() {
		return (String) get(42);
	}

	/**
	 * Setter for <code>tblcontact.formatted_contact_number</code>. Stores
	 * normalized/formatted contact number for search and filtering support
	 */
	public void setFormattedContactNumber(String value) {
		set(43, value);
	}

	/**
	 * Getter for <code>tblcontact.formatted_contact_number</code>. Stores
	 * normalized/formatted contact number for search and filtering support
	 */
	public String getFormattedContactNumber() {
		return (String) get(43);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TblcontactRecord
	 */
	public TblcontactRecord() {
		super(Tblcontact.TBLCONTACT);
	}

	/**
	 * Create a detached, initialised TblcontactRecord
	 */
	public TblcontactRecord(Integer id, Integer srno, Integer companyid, String companyslug, String firstname,
			String lastname, String email, String contactnumber, String photo, String slug, Integer ownerid,
			Integer accountid, Integer createdby, Integer createdon, Integer updatedby, Integer updatedon, String city,
			Integer lat, Integer lng, String address, String locality, Byte deleted, String designation,
			String profilefacebook, String profiletwitter, String profilelinkedin, Integer stageid, String canaccess,
			String relatedtocandidate, Integer sourceid, String migrationReserved1, String migrationReserved2,
			Byte emailOptOut, Byte vmsMapped, Byte smsConsent, String profilexing, Byte emailOptOutSource,
			Byte mergeFlag, Byte smsOptOut, String formattedProfileLinkedin, String state, String country,
			String postalCode, String formattedContactNumber) {
		super(Tblcontact.TBLCONTACT);

		setId(id);
		setSrno(srno);
		setCompanyid(companyid);
		setCompanyslug(companyslug);
		setFirstname(firstname);
		setLastname(lastname);
		setEmail(email);
		setContactnumber(contactnumber);
		setPhoto(photo);
		setSlug(slug);
		setOwnerid(ownerid);
		setAccountid(accountid);
		setCreatedby(createdby);
		setCreatedon(createdon);
		setUpdatedby(updatedby);
		setUpdatedon(updatedon);
		setCity(city);
		setLat(lat);
		setLng(lng);
		setAddress(address);
		setLocality(locality);
		setDeleted(deleted);
		setDesignation(designation);
		setProfilefacebook(profilefacebook);
		setProfiletwitter(profiletwitter);
		setProfilelinkedin(profilelinkedin);
		setStageid(stageid);
		setCanaccess(canaccess);
		setRelatedtocandidate(relatedtocandidate);
		setSourceid(sourceid);
		setMigrationReserved1(migrationReserved1);
		setMigrationReserved2(migrationReserved2);
		setEmailOptOut(emailOptOut);
		setVmsMapped(vmsMapped);
		setSmsConsent(smsConsent);
		setProfilexing(profilexing);
		setEmailOptOutSource(emailOptOutSource);
		setMergeFlag(mergeFlag);
		setSmsOptOut(smsOptOut);
		setFormattedProfileLinkedin(formattedProfileLinkedin);
		setState(state);
		setCountry(country);
		setPostalCode(postalCode);
		setFormattedContactNumber(formattedContactNumber);
		resetTouchedOnNotNull();
	}

}
