/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.Tblcandidate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TblcandidateRecord extends UpdatableRecordImpl<TblcandidateRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>tblcandidate.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>tblcandidate.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>tblcandidate.srno</code>. This serial number is for user to
	 * identify the record by id. This value is generated account wise. There will be same
	 * srno for different accounts but not in same account.
	 */
	public void setSrno(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>tblcandidate.srno</code>. This serial number is for user to
	 * identify the record by id. This value is generated account wise. There will be same
	 * srno for different accounts but not in same account.
	 */
	public Integer getSrno() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>tblcandidate.firstname</code>.
	 */
	public void setFirstname(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>tblcandidate.firstname</code>.
	 */
	public String getFirstname() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>tblcandidate.lastname</code>.
	 */
	public void setLastname(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>tblcandidate.lastname</code>.
	 */
	public String getLastname() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>tblcandidate.emailid</code>. Email Address of candidate.
	 */
	public void setEmailid(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>tblcandidate.emailid</code>. Email Address of candidate.
	 */
	public String getEmailid() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>tblcandidate.genderid</code>. Gender id of candidate.\nReference -
	 * tblgender
	 */
	public void setGenderid(Byte value) {
		set(5, value);
	}

	/**
	 * Getter for <code>tblcandidate.genderid</code>. Gender id of candidate.\nReference -
	 * tblgender
	 */
	public Byte getGenderid() {
		return (Byte) get(5);
	}

	/**
	 * Setter for <code>tblcandidate.contactnumber</code>. Contact number of candidate(can
	 * be multiple using comma).
	 */
	public void setContactnumber(String value) {
		set(6, value);
	}

	/**
	 * Getter for <code>tblcandidate.contactnumber</code>. Contact number of candidate(can
	 * be multiple using comma).
	 */
	public String getContactnumber() {
		return (String) get(6);
	}

	/**
	 * Setter for <code>tblcandidate.qualificationid</code>. Qualification of candidate.
	 * Reference - tblqualifications
	 */
	public void setQualificationid(Integer value) {
		set(7, value);
	}

	/**
	 * Getter for <code>tblcandidate.qualificationid</code>. Qualification of candidate.
	 * Reference - tblqualifications
	 */
	public Integer getQualificationid() {
		return (Integer) get(7);
	}

	/**
	 * Setter for <code>tblcandidate.specialization</code>. Qualification specialization.
	 */
	public void setSpecialization(String value) {
		set(8, value);
	}

	/**
	 * Getter for <code>tblcandidate.specialization</code>. Qualification specialization.
	 */
	public String getSpecialization() {
		return (String) get(8);
	}

	/**
	 * Setter for <code>tblcandidate.locationid</code>.
	 */
	public void setLocationid(Short value) {
		set(9, value);
	}

	/**
	 * Getter for <code>tblcandidate.locationid</code>.
	 */
	public Short getLocationid() {
		return (Short) get(9);
	}

	/**
	 * Setter for <code>tblcandidate.workexpyr</code>. Work experience in years.
	 */
	public void setWorkexpyr(Byte value) {
		set(10, value);
	}

	/**
	 * Getter for <code>tblcandidate.workexpyr</code>. Work experience in years.
	 */
	public Byte getWorkexpyr() {
		return (Byte) get(10);
	}

	/**
	 * Setter for <code>tblcandidate.workexpmonth</code>. Work experience in months.
	 */
	public void setWorkexpmonth(Byte value) {
		set(11, value);
	}

	/**
	 * Getter for <code>tblcandidate.workexpmonth</code>. Work experience in months.
	 */
	public Byte getWorkexpmonth() {
		return (Byte) get(11);
	}

	/**
	 * Setter for <code>tblcandidate.candidatedob</code>. Date of birth of candidate.
	 */
	public void setCandidatedob(Integer value) {
		set(12, value);
	}

	/**
	 * Getter for <code>tblcandidate.candidatedob</code>. Date of birth of candidate.
	 */
	public Integer getCandidatedob() {
		return (Integer) get(12);
	}

	/**
	 * Setter for <code>tblcandidate.currentsalary</code>. Current salary of candidate.
	 */
	public void setCurrentsalary(Double value) {
		set(13, value);
	}

	/**
	 * Getter for <code>tblcandidate.currentsalary</code>. Current salary of candidate.
	 */
	public Double getCurrentsalary() {
		return (Double) get(13);
	}

	/**
	 * Setter for <code>tblcandidate.salaryexpectation</code>. Expected Salary of
	 * candidate.
	 */
	public void setSalaryexpectation(Double value) {
		set(14, value);
	}

	/**
	 * Getter for <code>tblcandidate.salaryexpectation</code>. Expected Salary of
	 * candidate.
	 */
	public Double getSalaryexpectation() {
		return (Double) get(14);
	}

	/**
	 * Setter for <code>tblcandidate.resume</code>. Link of the resume.
	 */
	public void setResume(String value) {
		set(15, value);
	}

	/**
	 * Getter for <code>tblcandidate.resume</code>. Link of the resume.
	 */
	public String getResume() {
		return (String) get(15);
	}

	/**
	 * Setter for <code>tblcandidate.resumefilename</code>. Resume File name.
	 */
	public void setResumefilename(String value) {
		set(16, value);
	}

	/**
	 * Getter for <code>tblcandidate.resumefilename</code>. Resume File name.
	 */
	public String getResumefilename() {
		return (String) get(16);
	}

	/**
	 * Setter for <code>tblcandidate.willingtorelocate</code>. Does candidate willing to
	 * relocate 0 - no, 1 -yes
	 */
	public void setWillingtorelocate(Byte value) {
		set(17, value);
	}

	/**
	 * Getter for <code>tblcandidate.willingtorelocate</code>. Does candidate willing to
	 * relocate 0 - no, 1 -yes
	 */
	public Byte getWillingtorelocate() {
		return (Byte) get(17);
	}

	/**
	 * Setter for <code>tblcandidate.lastorganisation</code>. Last organisation of
	 * candidate.
	 */
	public void setLastorganisation(String value) {
		set(18, value);
	}

	/**
	 * Getter for <code>tblcandidate.lastorganisation</code>. Last organisation of
	 * candidate.
	 */
	public String getLastorganisation() {
		return (String) get(18);
	}

	/**
	 * Setter for <code>tblcandidate.currentstatus</code>. Current employment status.
	 */
	public void setCurrentstatus(String value) {
		set(19, value);
	}

	/**
	 * Getter for <code>tblcandidate.currentstatus</code>. Current employment status.
	 */
	public String getCurrentstatus() {
		return (String) get(19);
	}

	/**
	 * Setter for <code>tblcandidate.noticeperiod</code>. Notice period in current
	 * company.
	 */
	public void setNoticeperiod(Integer value) {
		set(20, value);
	}

	/**
	 * Getter for <code>tblcandidate.noticeperiod</code>. Notice period in current
	 * company.
	 */
	public Integer getNoticeperiod() {
		return (Integer) get(20);
	}

	/**
	 * Setter for <code>tblcandidate.currencyid</code>. Currency of candidate. Reference -
	 * tblcurrency
	 */
	public void setCurrencyid(Integer value) {
		set(21, value);
	}

	/**
	 * Getter for <code>tblcandidate.currencyid</code>. Currency of candidate. Reference -
	 * tblcurrency
	 */
	public Integer getCurrencyid() {
		return (Integer) get(21);
	}

	/**
	 * Setter for <code>tblcandidate.slug</code>. Unique value generated using trigger.
	 */
	public void setSlug(String value) {
		set(22, value);
	}

	/**
	 * Getter for <code>tblcandidate.slug</code>. Unique value generated using trigger.
	 */
	public String getSlug() {
		return (String) get(22);
	}

	/**
	 * Setter for <code>tblcandidate.authid</code>.
	 */
	public void setAuthid(String value) {
		set(23, value);
	}

	/**
	 * Getter for <code>tblcandidate.authid</code>.
	 */
	public String getAuthid() {
		return (String) get(23);
	}

	/**
	 * Setter for <code>tblcandidate.resumeupdatedon</code>. Timestamp when last time
	 * resume updated.
	 */
	public void setResumeupdatedon(Integer value) {
		set(24, value);
	}

	/**
	 * Getter for <code>tblcandidate.resumeupdatedon</code>. Timestamp when last time
	 * resume updated.
	 */
	public Integer getResumeupdatedon() {
		return (Integer) get(24);
	}

	/**
	 * Setter for <code>tblcandidate.resumeupdaterequestedon</code>. Request profile
	 * updated link generated on time.
	 */
	public void setResumeupdaterequestedon(Integer value) {
		set(25, value);
	}

	/**
	 * Getter for <code>tblcandidate.resumeupdaterequestedon</code>. Request profile
	 * updated link generated on time.
	 */
	public Integer getResumeupdaterequestedon() {
		return (Integer) get(25);
	}

	/**
	 * Setter for <code>tblcandidate.requestresumelinkstatus</code>. Profile Update link
	 * status 0 - Not Active, 1 - Active
	 *
	 */
	public void setRequestresumelinkstatus(Byte value) {
		set(26, value);
	}

	/**
	 * Getter for <code>tblcandidate.requestresumelinkstatus</code>. Profile Update link
	 * status 0 - Not Active, 1 - Active
	 *
	 */
	public Byte getRequestresumelinkstatus() {
		return (Byte) get(26);
	}

	/**
	 * Setter for <code>tblcandidate.resumeaddedon</code>. First time resume added time.
	 */
	public void setResumeaddedon(Integer value) {
		set(27, value);
	}

	/**
	 * Getter for <code>tblcandidate.resumeaddedon</code>. First time resume added time.
	 */
	public Integer getResumeaddedon() {
		return (Integer) get(27);
	}

	/**
	 * Setter for <code>tblcandidate.profilepic</code>. Profile photo URL.
	 */
	public void setProfilepic(String value) {
		set(28, value);
	}

	/**
	 * Getter for <code>tblcandidate.profilepic</code>. Profile photo URL.
	 */
	public String getProfilepic() {
		return (String) get(28);
	}

	/**
	 * Setter for <code>tblcandidate.profilefacebook</code>. Facebook profile url.
	 */
	public void setProfilefacebook(String value) {
		set(29, value);
	}

	/**
	 * Getter for <code>tblcandidate.profilefacebook</code>. Facebook profile url.
	 */
	public String getProfilefacebook() {
		return (String) get(29);
	}

	/**
	 * Setter for <code>tblcandidate.profilegithub</code>. GitHub profile URL.
	 */
	public void setProfilegithub(String value) {
		set(30, value);
	}

	/**
	 * Getter for <code>tblcandidate.profilegithub</code>. GitHub profile URL.
	 */
	public String getProfilegithub() {
		return (String) get(30);
	}

	/**
	 * Setter for <code>tblcandidate.profiletwitter</code>. Twitter profile url.
	 */
	public void setProfiletwitter(String value) {
		set(31, value);
	}

	/**
	 * Getter for <code>tblcandidate.profiletwitter</code>. Twitter profile url.
	 */
	public String getProfiletwitter() {
		return (String) get(31);
	}

	/**
	 * Setter for <code>tblcandidate.profilelinkedin</code>. Linkedin profile url.
	 */
	public void setProfilelinkedin(String value) {
		set(32, value);
	}

	/**
	 * Getter for <code>tblcandidate.profilelinkedin</code>. Linkedin profile url.
	 */
	public String getProfilelinkedin() {
		return (String) get(32);
	}

	/**
	 * Setter for <code>tblcandidate.deleted</code>.
	 */
	public void setDeleted(Byte value) {
		set(33, value);
	}

	/**
	 * Getter for <code>tblcandidate.deleted</code>.
	 */
	public Byte getDeleted() {
		return (Byte) get(33);
	}

	/**
	 * Setter for <code>tblcandidate.ownerid</code>. User id who owns that record.
	 * Reference - tbluser
	 */
	public void setOwnerid(Integer value) {
		set(34, value);
	}

	/**
	 * Getter for <code>tblcandidate.ownerid</code>. User id who owns that record.
	 * Reference - tbluser
	 */
	public Integer getOwnerid() {
		return (Integer) get(34);
	}

	/**
	 * Setter for <code>tblcandidate.accountid</code>. Account id of candidate. Reference
	 * - tblaccount
	 */
	public void setAccountid(Integer value) {
		set(35, value);
	}

	/**
	 * Getter for <code>tblcandidate.accountid</code>. Account id of candidate. Reference
	 * - tblaccount
	 */
	public Integer getAccountid() {
		return (Integer) get(35);
	}

	/**
	 * Setter for <code>tblcandidate.createdby</code>. User id who created the record.
	 */
	public void setCreatedby(Integer value) {
		set(36, value);
	}

	/**
	 * Getter for <code>tblcandidate.createdby</code>. User id who created the record.
	 */
	public Integer getCreatedby() {
		return (Integer) get(36);
	}

	/**
	 * Setter for <code>tblcandidate.createdon</code>. Time when record added.
	 */
	public void setCreatedon(Integer value) {
		set(37, value);
	}

	/**
	 * Getter for <code>tblcandidate.createdon</code>. Time when record added.
	 */
	public Integer getCreatedon() {
		return (Integer) get(37);
	}

	/**
	 * Setter for <code>tblcandidate.updatedby</code>. User id who updated the record.
	 */
	public void setUpdatedby(Integer value) {
		set(38, value);
	}

	/**
	 * Getter for <code>tblcandidate.updatedby</code>. User id who updated the record.
	 */
	public Integer getUpdatedby() {
		return (Integer) get(38);
	}

	/**
	 * Setter for <code>tblcandidate.updatedon</code>. Time when record updated.
	 */
	public void setUpdatedon(Integer value) {
		set(39, value);
	}

	/**
	 * Getter for <code>tblcandidate.updatedon</code>. Time when record updated.
	 */
	public Integer getUpdatedon() {
		return (Integer) get(39);
	}

	/**
	 * Setter for <code>tblcandidate.locality</code>. Locality of candidate.
	 */
	public void setLocality(String value) {
		set(40, value);
	}

	/**
	 * Getter for <code>tblcandidate.locality</code>. Locality of candidate.
	 */
	public String getLocality() {
		return (String) get(40);
	}

	/**
	 * Setter for <code>tblcandidate.city</code>. City of candidate.
	 */
	public void setCity(String value) {
		set(41, value);
	}

	/**
	 * Getter for <code>tblcandidate.city</code>. City of candidate.
	 */
	public String getCity() {
		return (String) get(41);
	}

	/**
	 * Setter for <code>tblcandidate.state</code>.
	 */
	public void setState(String value) {
		set(42, value);
	}

	/**
	 * Getter for <code>tblcandidate.state</code>.
	 */
	public String getState() {
		return (String) get(42);
	}

	/**
	 * Setter for <code>tblcandidate.country</code>.
	 */
	public void setCountry(String value) {
		set(43, value);
	}

	/**
	 * Getter for <code>tblcandidate.country</code>.
	 */
	public String getCountry() {
		return (String) get(43);
	}

	/**
	 * Setter for <code>tblcandidate.lng</code>. Latitude - Used for radius search.
	 */
	public void setLng(Integer value) {
		set(44, value);
	}

	/**
	 * Getter for <code>tblcandidate.lng</code>. Latitude - Used for radius search.
	 */
	public Integer getLng() {
		return (Integer) get(44);
	}

	/**
	 * Setter for <code>tblcandidate.relevantexperience</code>. Relevant Experience of
	 * candidate.
	 */
	public void setRelevantexperience(Integer value) {
		set(45, value);
	}

	/**
	 * Getter for <code>tblcandidate.relevantexperience</code>. Relevant Experience of
	 * candidate.
	 */
	public Integer getRelevantexperience() {
		return (Integer) get(45);
	}

	/**
	 * Setter for <code>tblcandidate.position</code>. Title/position of candidate.
	 */
	public void setPosition(String value) {
		set(46, value);
	}

	/**
	 * Getter for <code>tblcandidate.position</code>. Title/position of candidate.
	 */
	public String getPosition() {
		return (String) get(46);
	}

	/**
	 * Setter for <code>tblcandidate.canaccess</code>. User ids who is not owner and not
	 * having full access but need to see the record (comma separated).
	 */
	public void setCanaccess(String value) {
		set(47, value);
	}

	/**
	 * Getter for <code>tblcandidate.canaccess</code>. User ids who is not owner and not
	 * having full access but need to see the record (comma separated).
	 */
	public String getCanaccess() {
		return (String) get(47);
	}

	/**
	 * Setter for <code>tblcandidate.availablefrom</code>. Unix timestamp frm when
	 * candidate is available to join.
	 */
	public void setAvailablefrom(Integer value) {
		set(48, value);
	}

	/**
	 * Getter for <code>tblcandidate.availablefrom</code>. Unix timestamp frm when
	 * candidate is available to join.
	 */
	public Integer getAvailablefrom() {
		return (Integer) get(48);
	}

	/**
	 * Setter for <code>tblcandidate.salarytype</code>. salary type id.
	 */
	public void setSalarytype(String value) {
		set(49, value);
	}

	/**
	 * Getter for <code>tblcandidate.salarytype</code>. salary type id.
	 */
	public String getSalarytype() {
		return (String) get(49);
	}

	/**
	 * Setter for <code>tblcandidate.source</code>. Source where candidate came from.
	 */
	public void setSource(String value) {
		set(50, value);
	}

	/**
	 * Getter for <code>tblcandidate.source</code>. Source where candidate came from.
	 */
	public String getSource() {
		return (String) get(50);
	}

	/**
	 * Setter for <code>tblcandidate.sourceadded</code>. This is the system field to track
	 * from where candidate is added.
	 */
	public void setSourceadded(String value) {
		set(51, value);
	}

	/**
	 * Getter for <code>tblcandidate.sourceadded</code>. This is the system field to track
	 * from where candidate is added.
	 */
	public String getSourceadded() {
		return (String) get(51);
	}

	/**
	 * Setter for <code>tblcandidate.languageskills</code>. Multiple language skills.
	 */
	public void setLanguageskills(String value) {
		set(52, value);
	}

	/**
	 * Getter for <code>tblcandidate.languageskills</code>. Multiple language skills.
	 */
	public String getLanguageskills() {
		return (String) get(52);
	}

	/**
	 * Setter for <code>tblcandidate.skill</code>. Skills of candidate in comma separated
	 * format.
	 */
	public void setSkill(String value) {
		set(53, value);
	}

	/**
	 * Getter for <code>tblcandidate.skill</code>. Skills of candidate in comma separated
	 * format.
	 */
	public String getSkill() {
		return (String) get(53);
	}

	/**
	 * Setter for <code>tblcandidate.isduplicate</code>. Status if the candidate is
	 * duplicate.
	 */
	public void setIsduplicate(Byte value) {
		set(54, value);
	}

	/**
	 * Getter for <code>tblcandidate.isduplicate</code>. Status if the candidate is
	 * duplicate.
	 */
	public Byte getIsduplicate() {
		return (Byte) get(54);
	}

	/**
	 * Setter for <code>tblcandidate.address</code>. Address of candidate.
	 */
	public void setAddress(String value) {
		set(55, value);
	}

	/**
	 * Getter for <code>tblcandidate.address</code>. Address of candidate.
	 */
	public String getAddress() {
		return (String) get(55);
	}

	/**
	 * Setter for <code>tblcandidate.lat</code>. Latitude - Used for radius search.
	 */
	public void setLat(Integer value) {
		set(56, value);
	}

	/**
	 * Getter for <code>tblcandidate.lat</code>. Latitude - Used for radius search.
	 */
	public Integer getLat() {
		return (Integer) get(56);
	}

	/**
	 * Setter for <code>tblcandidate.sourceid</code>.
	 */
	public void setSourceid(Integer value) {
		set(57, value);
	}

	/**
	 * Getter for <code>tblcandidate.sourceid</code>.
	 */
	public Integer getSourceid() {
		return (Integer) get(57);
	}

	/**
	 * Setter for <code>tblcandidate.migration_reserved1</code>.
	 */
	public void setMigrationReserved1(String value) {
		set(58, value);
	}

	/**
	 * Getter for <code>tblcandidate.migration_reserved1</code>.
	 */
	public String getMigrationReserved1() {
		return (String) get(58);
	}

	/**
	 * Setter for <code>tblcandidate.migration_reserved2</code>.
	 */
	public void setMigrationReserved2(String value) {
		set(59, value);
	}

	/**
	 * Getter for <code>tblcandidate.migration_reserved2</code>.
	 */
	public String getMigrationReserved2() {
		return (String) get(59);
	}

	/**
	 * Setter for <code>tblcandidate.email_opt_out</code>. Option to opt out from
	 * receiving the emails
	 */
	public void setEmailOptOut(Byte value) {
		set(60, value);
	}

	/**
	 * Getter for <code>tblcandidate.email_opt_out</code>. Option to opt out from
	 * receiving the emails
	 */
	public Byte getEmailOptOut() {
		return (Byte) get(60);
	}

	/**
	 * Setter for <code>tblcandidate.profilexing</code>.
	 */
	public void setProfilexing(String value) {
		set(61, value);
	}

	/**
	 * Getter for <code>tblcandidate.profilexing</code>.
	 */
	public String getProfilexing() {
		return (String) get(61);
	}

	/**
	 * Setter for <code>tblcandidate.unavailable</code>.
	 */
	public void setUnavailable(Byte value) {
		set(62, value);
	}

	/**
	 * Getter for <code>tblcandidate.unavailable</code>.
	 */
	public Byte getUnavailable() {
		return (Byte) get(62);
	}

	/**
	 * Setter for <code>tblcandidate.availability_updated_by</code>.
	 */
	public void setAvailabilityUpdatedBy(Integer value) {
		set(63, value);
	}

	/**
	 * Getter for <code>tblcandidate.availability_updated_by</code>.
	 */
	public Integer getAvailabilityUpdatedBy() {
		return (Integer) get(63);
	}

	/**
	 * Setter for <code>tblcandidate.sms_consent</code>.
	 */
	public void setSmsConsent(Byte value) {
		set(64, value);
	}

	/**
	 * Getter for <code>tblcandidate.sms_consent</code>.
	 */
	public Byte getSmsConsent() {
		return (Byte) get(64);
	}

	/**
	 * Setter for <code>tblcandidate.sovren_document_id</code>.
	 */
	public void setSovrenDocumentId(String value) {
		set(65, value);
	}

	/**
	 * Getter for <code>tblcandidate.sovren_document_id</code>.
	 */
	public String getSovrenDocumentId() {
		return (String) get(65);
	}

	/**
	 * Setter for <code>tblcandidate.email_opt_out_source</code>.
	 */
	public void setEmailOptOutSource(Byte value) {
		set(66, value);
	}

	/**
	 * Getter for <code>tblcandidate.email_opt_out_source</code>.
	 */
	public Byte getEmailOptOutSource() {
		return (Byte) get(66);
	}

	/**
	 * Setter for <code>tblcandidate.merge_flag</code>.
	 */
	public void setMergeFlag(Byte value) {
		set(67, value);
	}

	/**
	 * Getter for <code>tblcandidate.merge_flag</code>.
	 */
	public Byte getMergeFlag() {
		return (Byte) get(67);
	}

	/**
	 * Setter for <code>tblcandidate.formatted_contact_number</code>.
	 */
	public void setFormattedContactNumber(String value) {
		set(68, value);
	}

	/**
	 * Getter for <code>tblcandidate.formatted_contact_number</code>.
	 */
	public String getFormattedContactNumber() {
		return (String) get(68);
	}

	/**
	 * Setter for <code>tblcandidate.external_profile_updated_on</code>. Unix timestamp of
	 * candidate updated from external page
	 */
	public void setExternalProfileUpdatedOn(Integer value) {
		set(69, value);
	}

	/**
	 * Getter for <code>tblcandidate.external_profile_updated_on</code>. Unix timestamp of
	 * candidate updated from external page
	 */
	public Integer getExternalProfileUpdatedOn() {
		return (Integer) get(69);
	}

	/**
	 * Setter for <code>tblcandidate.formatted_profilelinkedin</code>.
	 */
	public void setFormattedProfilelinkedin(String value) {
		set(70, value);
	}

	/**
	 * Getter for <code>tblcandidate.formatted_profilelinkedin</code>.
	 */
	public String getFormattedProfilelinkedin() {
		return (String) get(70);
	}

	/**
	 * Setter for <code>tblcandidate.formatted_profile_linkedin</code>.
	 */
	public void setFormattedProfileLinkedin(String value) {
		set(71, value);
	}

	/**
	 * Getter for <code>tblcandidate.formatted_profile_linkedin</code>.
	 */
	public String getFormattedProfileLinkedin() {
		return (String) get(71);
	}

	/**
	 * Setter for <code>tblcandidate.sms_opt_out</code>.
	 */
	public void setSmsOptOut(Byte value) {
		set(72, value);
	}

	/**
	 * Getter for <code>tblcandidate.sms_opt_out</code>.
	 */
	public Byte getSmsOptOut() {
		return (Byte) get(72);
	}

	/**
	 * Setter for <code>tblcandidate.postal_code</code>. Column to store Postal code of
	 * the candidate address
	 */
	public void setPostalCode(String value) {
		set(73, value);
	}

	/**
	 * Getter for <code>tblcandidate.postal_code</code>. Column to store Postal code of
	 * the candidate address
	 */
	public String getPostalCode() {
		return (String) get(73);
	}

	/**
	 * Setter for <code>tblcandidate.portal_access</code>. Portal access for candidate
	 */
	public void setPortalAccess(Byte value) {
		set(74, value);
	}

	/**
	 * Getter for <code>tblcandidate.portal_access</code>. Portal access for candidate
	 */
	public Byte getPortalAccess() {
		return (Byte) get(74);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TblcandidateRecord
	 */
	public TblcandidateRecord() {
		super(Tblcandidate.TBLCANDIDATE);
	}

	/**
	 * Create a detached, initialised TblcandidateRecord
	 */
	public TblcandidateRecord(Integer id, Integer srno, String firstname, String lastname, String emailid,
			Byte genderid, String contactnumber, Integer qualificationid, String specialization, Short locationid,
			Byte workexpyr, Byte workexpmonth, Integer candidatedob, Double currentsalary, Double salaryexpectation,
			String resume, String resumefilename, Byte willingtorelocate, String lastorganisation, String currentstatus,
			Integer noticeperiod, Integer currencyid, String slug, String authid, Integer resumeupdatedon,
			Integer resumeupdaterequestedon, Byte requestresumelinkstatus, Integer resumeaddedon, String profilepic,
			String profilefacebook, String profilegithub, String profiletwitter, String profilelinkedin, Byte deleted,
			Integer ownerid, Integer accountid, Integer createdby, Integer createdon, Integer updatedby,
			Integer updatedon, String locality, String city, String state, String country, Integer lng,
			Integer relevantexperience, String position, String canaccess, Integer availablefrom, String salarytype,
			String source, String sourceadded, String languageskills, String skill, Byte isduplicate, String address,
			Integer lat, Integer sourceid, String migrationReserved1, String migrationReserved2, Byte emailOptOut,
			String profilexing, Byte unavailable, Integer availabilityUpdatedBy, Byte smsConsent,
			String sovrenDocumentId, Byte emailOptOutSource, Byte mergeFlag, String formattedContactNumber,
			Integer externalProfileUpdatedOn, String formattedProfilelinkedin, String formattedProfileLinkedin,
			Byte smsOptOut, String postalCode, Byte portalAccess) {
		super(Tblcandidate.TBLCANDIDATE);

		setId(id);
		setSrno(srno);
		setFirstname(firstname);
		setLastname(lastname);
		setEmailid(emailid);
		setGenderid(genderid);
		setContactnumber(contactnumber);
		setQualificationid(qualificationid);
		setSpecialization(specialization);
		setLocationid(locationid);
		setWorkexpyr(workexpyr);
		setWorkexpmonth(workexpmonth);
		setCandidatedob(candidatedob);
		setCurrentsalary(currentsalary);
		setSalaryexpectation(salaryexpectation);
		setResume(resume);
		setResumefilename(resumefilename);
		setWillingtorelocate(willingtorelocate);
		setLastorganisation(lastorganisation);
		setCurrentstatus(currentstatus);
		setNoticeperiod(noticeperiod);
		setCurrencyid(currencyid);
		setSlug(slug);
		setAuthid(authid);
		setResumeupdatedon(resumeupdatedon);
		setResumeupdaterequestedon(resumeupdaterequestedon);
		setRequestresumelinkstatus(requestresumelinkstatus);
		setResumeaddedon(resumeaddedon);
		setProfilepic(profilepic);
		setProfilefacebook(profilefacebook);
		setProfilegithub(profilegithub);
		setProfiletwitter(profiletwitter);
		setProfilelinkedin(profilelinkedin);
		setDeleted(deleted);
		setOwnerid(ownerid);
		setAccountid(accountid);
		setCreatedby(createdby);
		setCreatedon(createdon);
		setUpdatedby(updatedby);
		setUpdatedon(updatedon);
		setLocality(locality);
		setCity(city);
		setState(state);
		setCountry(country);
		setLng(lng);
		setRelevantexperience(relevantexperience);
		setPosition(position);
		setCanaccess(canaccess);
		setAvailablefrom(availablefrom);
		setSalarytype(salarytype);
		setSource(source);
		setSourceadded(sourceadded);
		setLanguageskills(languageskills);
		setSkill(skill);
		setIsduplicate(isduplicate);
		setAddress(address);
		setLat(lat);
		setSourceid(sourceid);
		setMigrationReserved1(migrationReserved1);
		setMigrationReserved2(migrationReserved2);
		setEmailOptOut(emailOptOut);
		setProfilexing(profilexing);
		setUnavailable(unavailable);
		setAvailabilityUpdatedBy(availabilityUpdatedBy);
		setSmsConsent(smsConsent);
		setSovrenDocumentId(sovrenDocumentId);
		setEmailOptOutSource(emailOptOutSource);
		setMergeFlag(mergeFlag);
		setFormattedContactNumber(formattedContactNumber);
		setExternalProfileUpdatedOn(externalProfileUpdatedOn);
		setFormattedProfilelinkedin(formattedProfilelinkedin);
		setFormattedProfileLinkedin(formattedProfileLinkedin);
		setSmsOptOut(smsOptOut);
		setPostalCode(postalCode);
		setPortalAccess(portalAccess);
		resetTouchedOnNotNull();
	}

}
