/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.Tbldeals;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbldealsRecord extends UpdatableRecordImpl<TbldealsRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>tbldeals.id</code>. Primary key for the table.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>tbldeals.id</code>. Primary key for the table.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>tbldeals.srno</code>. This serial number is for job to identify
	 * the record by id. This value is generated account wise. There will be same srno for
	 * different accounts but not in same account.
	 */
	public void setSrno(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>tbldeals.srno</code>. This serial number is for job to identify
	 * the record by id. This value is generated account wise. There will be same srno for
	 * different accounts but not in same account.
	 */
	public Integer getSrno() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>tbldeals.name</code>.
	 */
	public void setName(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>tbldeals.name</code>.
	 */
	public String getName() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>tbldeals.dealstage</code>. Stage of the deal.
	 */
	public void setDealstage(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>tbldeals.dealstage</code>. Stage of the deal.
	 */
	public Integer getDealstage() {
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>tbldeals.dealvalue</code>.
	 */
	public void setDealvalue(BigDecimal value) {
		set(4, value);
	}

	/**
	 * Getter for <code>tbldeals.dealvalue</code>.
	 */
	public BigDecimal getDealvalue() {
		return (BigDecimal) get(4);
	}

	/**
	 * Setter for <code>tbldeals.dealpercentagevalue</code>.
	 */
	public void setDealpercentagevalue(BigDecimal value) {
		set(5, value);
	}

	/**
	 * Getter for <code>tbldeals.dealpercentagevalue</code>.
	 */
	public BigDecimal getDealpercentagevalue() {
		return (BigDecimal) get(5);
	}

	/**
	 * Setter for <code>tbldeals.closedate</code>. Closing date of the deal.
	 */
	public void setClosedate(Integer value) {
		set(6, value);
	}

	/**
	 * Getter for <code>tbldeals.closedate</code>. Closing date of the deal.
	 */
	public Integer getClosedate() {
		return (Integer) get(6);
	}

	/**
	 * Setter for <code>tbldeals.dealtype</code>. Type of the deal.
	 */
	public void setDealtype(Integer value) {
		set(7, value);
	}

	/**
	 * Getter for <code>tbldeals.dealtype</code>. Type of the deal.
	 */
	public Integer getDealtype() {
		return (Integer) get(7);
	}

	/**
	 * Setter for <code>tbldeals.slug</code>. Unique value generated using trigger.
	 */
	public void setSlug(String value) {
		set(8, value);
	}

	/**
	 * Getter for <code>tbldeals.slug</code>. Unique value generated using trigger.
	 */
	public String getSlug() {
		return (String) get(8);
	}

	/**
	 * Setter for <code>tbldeals.relatedcompany</code>. Company id for which deal created.
	 */
	public void setRelatedcompany(Integer value) {
		set(9, value);
	}

	/**
	 * Getter for <code>tbldeals.relatedcompany</code>. Company id for which deal created.
	 */
	public Integer getRelatedcompany() {
		return (Integer) get(9);
	}

	/**
	 * Setter for <code>tbldeals.relatedcandidate</code>.
	 */
	public void setRelatedcandidate(Integer value) {
		set(10, value);
	}

	/**
	 * Getter for <code>tbldeals.relatedcandidate</code>.
	 */
	public Integer getRelatedcandidate() {
		return (Integer) get(10);
	}

	/**
	 * Setter for <code>tbldeals.archived</code>. If deal is archived, these field set to
	 * 1.
	 */
	public void setArchived(Byte value) {
		set(11, value);
	}

	/**
	 * Getter for <code>tbldeals.archived</code>. If deal is archived, these field set to
	 * 1.
	 */
	public Byte getArchived() {
		return (Byte) get(11);
	}

	/**
	 * Setter for <code>tbldeals.ownerid</code>. User id who owned the deal.
	 */
	public void setOwnerid(Integer value) {
		set(12, value);
	}

	/**
	 * Getter for <code>tbldeals.ownerid</code>. User id who owned the deal.
	 */
	public Integer getOwnerid() {
		return (Integer) get(12);
	}

	/**
	 * Setter for <code>tbldeals.accountid</code>. Account id for which deal is
	 * associated.
	 */
	public void setAccountid(Integer value) {
		set(13, value);
	}

	/**
	 * Getter for <code>tbldeals.accountid</code>. Account id for which deal is
	 * associated.
	 */
	public Integer getAccountid() {
		return (Integer) get(13);
	}

	/**
	 * Setter for <code>tbldeals.createdby</code>. User id who created the deal.
	 */
	public void setCreatedby(Integer value) {
		set(14, value);
	}

	/**
	 * Getter for <code>tbldeals.createdby</code>. User id who created the deal.
	 */
	public Integer getCreatedby() {
		return (Integer) get(14);
	}

	/**
	 * Setter for <code>tbldeals.createdon</code>. Time when record created.
	 */
	public void setCreatedon(Integer value) {
		set(15, value);
	}

	/**
	 * Getter for <code>tbldeals.createdon</code>. Time when record created.
	 */
	public Integer getCreatedon() {
		return (Integer) get(15);
	}

	/**
	 * Setter for <code>tbldeals.updatedby</code>. User id who updated the record.
	 */
	public void setUpdatedby(Integer value) {
		set(16, value);
	}

	/**
	 * Getter for <code>tbldeals.updatedby</code>. User id who updated the record.
	 */
	public Integer getUpdatedby() {
		return (Integer) get(16);
	}

	/**
	 * Setter for <code>tbldeals.updatedon</code>. Time when record updated.
	 */
	public void setUpdatedon(Integer value) {
		set(17, value);
	}

	/**
	 * Getter for <code>tbldeals.updatedon</code>. Time when record updated.
	 */
	public Integer getUpdatedon() {
		return (Integer) get(17);
	}

	/**
	 * Setter for <code>tbldeals.sourceid</code>.
	 */
	public void setSourceid(Integer value) {
		set(18, value);
	}

	/**
	 * Getter for <code>tbldeals.sourceid</code>.
	 */
	public Integer getSourceid() {
		return (Integer) get(18);
	}

	/**
	 * Setter for <code>tbldeals.related_job</code>.
	 */
	public void setRelatedJob(Integer value) {
		set(19, value);
	}

	/**
	 * Getter for <code>tbldeals.related_job</code>.
	 */
	public Integer getRelatedJob() {
		return (Integer) get(19);
	}

	/**
	 * Setter for <code>tbldeals.split_type</code>.
	 */
	public void setSplitType(Integer value) {
		set(20, value);
	}

	/**
	 * Getter for <code>tbldeals.split_type</code>.
	 */
	public Integer getSplitType() {
		return (Integer) get(20);
	}

	/**
	 * Setter for <code>tbldeals.migration_reserved1</code>.
	 */
	public void setMigrationReserved1(String value) {
		set(21, value);
	}

	/**
	 * Getter for <code>tbldeals.migration_reserved1</code>.
	 */
	public String getMigrationReserved1() {
		return (String) get(21);
	}

	/**
	 * Setter for <code>tbldeals.migration_reserved2</code>.
	 */
	public void setMigrationReserved2(String value) {
		set(22, value);
	}

	/**
	 * Getter for <code>tbldeals.migration_reserved2</code>.
	 */
	public String getMigrationReserved2() {
		return (String) get(22);
	}

	/**
	 * Setter for <code>tbldeals.migration_reserved3</code>.
	 */
	public void setMigrationReserved3(String value) {
		set(23, value);
	}

	/**
	 * Getter for <code>tbldeals.migration_reserved3</code>.
	 */
	public String getMigrationReserved3() {
		return (String) get(23);
	}

	/**
	 * Setter for <code>tbldeals.migration_reserved4</code>.
	 */
	public void setMigrationReserved4(String value) {
		set(24, value);
	}

	/**
	 * Getter for <code>tbldeals.migration_reserved4</code>.
	 */
	public String getMigrationReserved4() {
		return (String) get(24);
	}

	/**
	 * Setter for <code>tbldeals.migration_reserved5</code>.
	 */
	public void setMigrationReserved5(String value) {
		set(25, value);
	}

	/**
	 * Getter for <code>tbldeals.migration_reserved5</code>.
	 */
	public String getMigrationReserved5() {
		return (String) get(25);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TbldealsRecord
	 */
	public TbldealsRecord() {
		super(Tbldeals.TBLDEALS);
	}

	/**
	 * Create a detached, initialised TbldealsRecord
	 */
	public TbldealsRecord(Integer id, Integer srno, String name, Integer dealstage, BigDecimal dealvalue,
			BigDecimal dealpercentagevalue, Integer closedate, Integer dealtype, String slug, Integer relatedcompany,
			Integer relatedcandidate, Byte archived, Integer ownerid, Integer accountid, Integer createdby,
			Integer createdon, Integer updatedby, Integer updatedon, Integer sourceid, Integer relatedJob,
			Integer splitType, String migrationReserved1, String migrationReserved2, String migrationReserved3,
			String migrationReserved4, String migrationReserved5) {
		super(Tbldeals.TBLDEALS);

		setId(id);
		setSrno(srno);
		setName(name);
		setDealstage(dealstage);
		setDealvalue(dealvalue);
		setDealpercentagevalue(dealpercentagevalue);
		setClosedate(closedate);
		setDealtype(dealtype);
		setSlug(slug);
		setRelatedcompany(relatedcompany);
		setRelatedcandidate(relatedcandidate);
		setArchived(archived);
		setOwnerid(ownerid);
		setAccountid(accountid);
		setCreatedby(createdby);
		setCreatedon(createdon);
		setUpdatedby(updatedby);
		setUpdatedon(updatedon);
		setSourceid(sourceid);
		setRelatedJob(relatedJob);
		setSplitType(splitType);
		setMigrationReserved1(migrationReserved1);
		setMigrationReserved2(migrationReserved2);
		setMigrationReserved3(migrationReserved3);
		setMigrationReserved4(migrationReserved4);
		setMigrationReserved5(migrationReserved5);
		resetTouchedOnNotNull();
	}

}
