/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.Tbldealjobs;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbldealjobsRecord extends UpdatableRecordImpl<TbldealjobsRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>tbldealjobs.id</code>.
	 */
	public void setId(UInteger value) {
		set(0, value);
	}

	/**
	 * Getter for <code>tbldealjobs.id</code>.
	 */
	public UInteger getId() {
		return (UInteger) get(0);
	}

	/**
	 * Setter for <code>tbldealjobs.dealid</code>.
	 */
	public void setDealid(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>tbldealjobs.dealid</code>.
	 */
	public Integer getDealid() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>tbldealjobs.jobid</code>.
	 */
	public void setJobid(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>tbldealjobs.jobid</code>.
	 */
	public Integer getJobid() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>tbldealjobs.jobslug</code>.
	 */
	public void setJobslug(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>tbldealjobs.jobslug</code>.
	 */
	public String getJobslug() {
		return (String) get(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<UInteger> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TbldealjobsRecord
	 */
	public TbldealjobsRecord() {
		super(Tbldealjobs.TBLDEALJOBS);
	}

	/**
	 * Create a detached, initialised TbldealjobsRecord
	 */
	public TbldealjobsRecord(UInteger id, Integer dealid, Integer jobid, String jobslug) {
		super(Tbldealjobs.TBLDEALJOBS);

		setId(id);
		setDealid(dealid);
		setJobid(jobid);
		setJobslug(jobslug);
		resetTouchedOnNotNull();
	}

}
