/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.Tblextrafields;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TblextrafieldsRecord extends UpdatableRecordImpl<TblextrafieldsRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>tblextrafields.id</code>. This is the default auto-incremented
	 * unique value for the table.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>tblextrafields.id</code>. This is the default auto-incremented
	 * unique value for the table.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>tblextrafields.columnid</code>. Custom column id in the table.
	 */
	public void setColumnid(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>tblextrafields.columnid</code>. Custom column id in the table.
	 */
	public Integer getColumnid() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>tblextrafields.accountid</code>. Account id for which extra field
	 * is created. Reference - tblaccount
	 */
	public void setAccountid(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>tblextrafields.accountid</code>. Account id for which extra field
	 * is created. Reference - tblaccount
	 */
	public Integer getAccountid() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>tblextrafields.entitytypeid</code>. EntityID, For which, extra
	 * field is created. Reference - tblentity
	 */
	public void setEntitytypeid(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>tblextrafields.entitytypeid</code>. EntityID, For which, extra
	 * field is created. Reference - tblentity
	 */
	public Integer getEntitytypeid() {
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>tblextrafields.extrafieldname</code>. Name of the extra field.
	 */
	public void setExtrafieldname(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>tblextrafields.extrafieldname</code>. Name of the extra field.
	 */
	public String getExtrafieldname() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>tblextrafields.extrafieldtype</code>. Type of the extra field.
	 */
	public void setExtrafieldtype(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>tblextrafields.extrafieldtype</code>. Type of the extra field.
	 */
	public String getExtrafieldtype() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>tblextrafields.defaultvalue</code>. Default value for the extra
	 * field. This will be used in dropdown or multi-select dropdown.
	 */
	public void setDefaultvalue(String value) {
		set(6, value);
	}

	/**
	 * Getter for <code>tblextrafields.defaultvalue</code>. Default value for the extra
	 * field. This will be used in dropdown or multi-select dropdown.
	 */
	public String getDefaultvalue() {
		return (String) get(6);
	}

	/**
	 * Setter for <code>tblextrafields.description</code>. Adding Description to help AI
	 * Understand the Custom Field
	 */
	public void setDescription(String value) {
		set(7, value);
	}

	/**
	 * Getter for <code>tblextrafields.description</code>. Adding Description to help AI
	 * Understand the Custom Field
	 */
	public String getDescription() {
		return (String) get(7);
	}

	/**
	 * Setter for <code>tblextrafields.is_parser_enabled</code>. Helps in whether the
	 * fields needs to Parsed by AI or not
	 */
	public void setIsParserEnabled(Byte value) {
		set(8, value);
	}

	/**
	 * Getter for <code>tblextrafields.is_parser_enabled</code>. Helps in whether the
	 * fields needs to Parsed by AI or not
	 */
	public Byte getIsParserEnabled() {
		return (Byte) get(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TblextrafieldsRecord
	 */
	public TblextrafieldsRecord() {
		super(Tblextrafields.TBLEXTRAFIELDS);
	}

	/**
	 * Create a detached, initialised TblextrafieldsRecord
	 */
	public TblextrafieldsRecord(Integer id, Integer columnid, Integer accountid, Integer entitytypeid,
			String extrafieldname, String extrafieldtype, String defaultvalue, String description,
			Byte isParserEnabled) {
		super(Tblextrafields.TBLEXTRAFIELDS);

		setId(id);
		setColumnid(columnid);
		setAccountid(accountid);
		setEntitytypeid(entitytypeid);
		setExtrafieldname(extrafieldname);
		setExtrafieldtype(extrafieldtype);
		setDefaultvalue(defaultvalue);
		setDescription(description);
		setIsParserEnabled(isParserEnabled);
		resetTouchedOnNotNull();
	}

}
