/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.Tbljobstatus;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbljobstatusRecord extends UpdatableRecordImpl<TbljobstatusRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>tbljobstatus.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>tbljobstatus.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>tbljobstatus.label</code>.
	 */
	public void setLabel(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>tbljobstatus.label</code>.
	 */
	public String getLabel() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>tbljobstatus.accountid</code>.
	 */
	public void setAccountid(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>tbljobstatus.accountid</code>.
	 */
	public Integer getAccountid() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>tbljobstatus.sequenceno</code>.
	 */
	public void setSequenceno(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>tbljobstatus.sequenceno</code>.
	 */
	public Integer getSequenceno() {
		return (Integer) get(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TbljobstatusRecord
	 */
	public TbljobstatusRecord() {
		super(Tbljobstatus.TBLJOBSTATUS);
	}

	/**
	 * Create a detached, initialised TbljobstatusRecord
	 */
	public TbljobstatusRecord(Integer id, String label, Integer accountid, Integer sequenceno) {
		super(Tbljobstatus.TBLJOBSTATUS);

		setId(id);
		setLabel(label);
		setAccountid(accountid);
		setSequenceno(sequenceno);
		resetTouchedOnNotNull();
	}

}
