/*
 * This file is generated by jOOQ.
 */
package io.recruitcrm.microservice.search.models.jooq.tables.records;

import io.recruitcrm.microservice.search.models.jooq.tables.Tbluser;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TbluserRecord extends UpdatableRecordImpl<TbluserRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>tbluser.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>tbluser.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>tbluser.roleid</code>. This column holds the value for user role
	 * in the system.\n1 - Super User(System),\n2 - Admin of account, \n3 - Recruiter\n
	 */
	public void setRoleid(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>tbluser.roleid</code>. This column holds the value for user role
	 * in the system.\n1 - Super User(System),\n2 - Admin of account, \n3 - Recruiter\n
	 */
	public Integer getRoleid() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>tbluser.firstname</code>.
	 */
	public void setFirstname(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>tbluser.firstname</code>.
	 */
	public String getFirstname() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>tbluser.lastname</code>.
	 */
	public void setLastname(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>tbluser.lastname</code>.
	 */
	public String getLastname() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>tbluser.email</code>. Email address of the user. Used for login to
	 * the system.
	 */
	public void setEmail(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>tbluser.email</code>. Email address of the user. Used for login to
	 * the system.
	 */
	public String getEmail() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>tbluser.verifiedemail</code>.
	 */
	public void setVerifiedemail(Byte value) {
		set(5, value);
	}

	/**
	 * Getter for <code>tbluser.verifiedemail</code>.
	 */
	public Byte getVerifiedemail() {
		return (Byte) get(5);
	}

	/**
	 * Setter for <code>tbluser.verificationcode</code>.
	 */
	public void setVerificationcode(String value) {
		set(6, value);
	}

	/**
	 * Getter for <code>tbluser.verificationcode</code>.
	 */
	public String getVerificationcode() {
		return (String) get(6);
	}

	/**
	 * Setter for <code>tbluser.contactnumber</code>.
	 */
	public void setContactnumber(String value) {
		set(7, value);
	}

	/**
	 * Getter for <code>tbluser.contactnumber</code>.
	 */
	public String getContactnumber() {
		return (String) get(7);
	}

	/**
	 * Setter for <code>tbluser.photo</code>.
	 */
	public void setPhoto(String value) {
		set(8, value);
	}

	/**
	 * Getter for <code>tbluser.photo</code>.
	 */
	public String getPhoto() {
		return (String) get(8);
	}

	/**
	 * Setter for <code>tbluser.username</code>.
	 */
	public void setUsername(String value) {
		set(9, value);
	}

	/**
	 * Getter for <code>tbluser.username</code>.
	 */
	public String getUsername() {
		return (String) get(9);
	}

	/**
	 * Setter for <code>tbluser.password</code>.
	 */
	public void setPassword(String value) {
		set(10, value);
	}

	/**
	 * Getter for <code>tbluser.password</code>.
	 */
	public String getPassword() {
		return (String) get(10);
	}

	/**
	 * Setter for <code>tbluser.oauthuid</code>.
	 */
	public void setOauthuid(String value) {
		set(11, value);
	}

	/**
	 * Getter for <code>tbluser.oauthuid</code>.
	 */
	public String getOauthuid() {
		return (String) get(11);
	}

	/**
	 * Setter for <code>tbluser.userstatus</code>. To identify active or deactivated user.
	 * 0 - Active, 1 - Deactivated
	 *
	 */
	public void setUserstatus(Byte value) {
		set(12, value);
	}

	/**
	 * Getter for <code>tbluser.userstatus</code>. To identify active or deactivated user.
	 * 0 - Active, 1 - Deactivated
	 *
	 */
	public Byte getUserstatus() {
		return (Byte) get(12);
	}

	/**
	 * Setter for <code>tbluser.session</code>. Sessionid, while user logged in. This
	 * session id matched with the cache session id then we directly logged in user.
	 */
	public void setSession(String value) {
		set(13, value);
	}

	/**
	 * Getter for <code>tbluser.session</code>. Sessionid, while user logged in. This
	 * session id matched with the cache session id then we directly logged in user.
	 */
	public String getSession() {
		return (String) get(13);
	}

	/**
	 * Setter for <code>tbluser.apptoken</code>.
	 */
	public void setApptoken(String value) {
		set(14, value);
	}

	/**
	 * Getter for <code>tbluser.apptoken</code>.
	 */
	public String getApptoken() {
		return (String) get(14);
	}

	/**
	 * Setter for <code>tbluser.msession</code>.
	 */
	public void setMsession(String value) {
		set(15, value);
	}

	/**
	 * Getter for <code>tbluser.msession</code>.
	 */
	public String getMsession() {
		return (String) get(15);
	}

	/**
	 * Setter for <code>tbluser.expiresin</code>.
	 */
	public void setExpiresin(Integer value) {
		set(16, value);
	}

	/**
	 * Getter for <code>tbluser.expiresin</code>.
	 */
	public Integer getExpiresin() {
		return (Integer) get(16);
	}

	/**
	 * Setter for <code>tbluser.slug</code>.
	 */
	public void setSlug(String value) {
		set(17, value);
	}

	/**
	 * Getter for <code>tbluser.slug</code>.
	 */
	public String getSlug() {
		return (String) get(17);
	}

	/**
	 * Setter for <code>tbluser.accountid</code>. Account id for which the user record is
	 * created. Reference - tblaccount
	 */
	public void setAccountid(Integer value) {
		set(18, value);
	}

	/**
	 * Getter for <code>tbluser.accountid</code>. Account id for which the user record is
	 * created. Reference - tblaccount
	 */
	public Integer getAccountid() {
		return (Integer) get(18);
	}

	/**
	 * Setter for <code>tbluser.createdby</code>. User id, who created the record.
	 */
	public void setCreatedby(Integer value) {
		set(19, value);
	}

	/**
	 * Getter for <code>tbluser.createdby</code>. User id, who created the record.
	 */
	public Integer getCreatedby() {
		return (Integer) get(19);
	}

	/**
	 * Setter for <code>tbluser.createdon</code>. Unix timestamp when the user is created.
	 */
	public void setCreatedon(Integer value) {
		set(20, value);
	}

	/**
	 * Getter for <code>tbluser.createdon</code>. Unix timestamp when the user is created.
	 */
	public Integer getCreatedon() {
		return (Integer) get(20);
	}

	/**
	 * Setter for <code>tbluser.updatedby</code>. Userid who updates the user information.
	 */
	public void setUpdatedby(Integer value) {
		set(21, value);
	}

	/**
	 * Getter for <code>tbluser.updatedby</code>. Userid who updates the user information.
	 */
	public Integer getUpdatedby() {
		return (Integer) get(21);
	}

	/**
	 * Setter for <code>tbluser.updatedon</code>. Unix timestamp when the user is updated.
	 */
	public void setUpdatedon(Integer value) {
		set(22, value);
	}

	/**
	 * Getter for <code>tbluser.updatedon</code>. Unix timestamp when the user is updated.
	 */
	public Integer getUpdatedon() {
		return (Integer) get(22);
	}

	/**
	 * Setter for <code>tbluser.country</code>. Country of the user.
	 */
	public void setCountry(String value) {
		set(23, value);
	}

	/**
	 * Getter for <code>tbluser.country</code>. Country of the user.
	 */
	public String getCountry() {
		return (String) get(23);
	}

	/**
	 * Setter for <code>tbluser.city</code>. City of the user.
	 */
	public void setCity(String value) {
		set(24, value);
	}

	/**
	 * Getter for <code>tbluser.city</code>. City of the user.
	 */
	public String getCity() {
		return (String) get(24);
	}

	/**
	 * Setter for <code>tbluser.apitoken</code>. State of the user.
	 */
	public void setApitoken(String value) {
		set(25, value);
	}

	/**
	 * Getter for <code>tbluser.apitoken</code>. State of the user.
	 */
	public String getApitoken() {
		return (String) get(25);
	}

	/**
	 * Setter for <code>tbluser.state</code>. API token for the user.
	 */
	public void setState(String value) {
		set(26, value);
	}

	/**
	 * Getter for <code>tbluser.state</code>. API token for the user.
	 */
	public String getState() {
		return (String) get(26);
	}

	/**
	 * Setter for <code>tbluser.lastactiveon</code>. Last active time.
	 */
	public void setLastactiveon(Integer value) {
		set(27, value);
	}

	/**
	 * Getter for <code>tbluser.lastactiveon</code>. Last active time.
	 */
	public Integer getLastactiveon() {
		return (Integer) get(27);
	}

	/**
	 * Setter for <code>tbluser.locale</code>.
	 */
	public void setLocale(String value) {
		set(28, value);
	}

	/**
	 * Getter for <code>tbluser.locale</code>.
	 */
	public String getLocale() {
		return (String) get(28);
	}

	/**
	 * Setter for <code>tbluser.apitokenactive</code>. To check api token is active or
	 * not.
	 */
	public void setApitokenactive(Byte value) {
		set(29, value);
	}

	/**
	 * Getter for <code>tbluser.apitokenactive</code>. To check api token is active or
	 * not.
	 */
	public Byte getApitokenactive() {
		return (Byte) get(29);
	}

	/**
	 * Setter for <code>tbluser.teamid</code>.
	 */
	public void setTeamid(Integer value) {
		set(30, value);
	}

	/**
	 * Getter for <code>tbluser.teamid</code>.
	 */
	public Integer getTeamid() {
		return (Integer) get(30);
	}

	/**
	 * Setter for <code>tbluser.contactverified</code>.
	 */
	public void setContactverified(Byte value) {
		set(31, value);
	}

	/**
	 * Getter for <code>tbluser.contactverified</code>.
	 */
	public Byte getContactverified() {
		return (Byte) get(31);
	}

	/**
	 * Setter for <code>tbluser.reset_password_token</code>.
	 */
	public void setResetPasswordToken(String value) {
		set(32, value);
	}

	/**
	 * Getter for <code>tbluser.reset_password_token</code>.
	 */
	public String getResetPasswordToken() {
		return (String) get(32);
	}

	/**
	 * Setter for <code>tbluser.reactivate_code</code>.
	 */
	public void setReactivateCode(String value) {
		set(33, value);
	}

	/**
	 * Getter for <code>tbluser.reactivate_code</code>.
	 */
	public String getReactivateCode() {
		return (String) get(33);
	}

	/**
	 * Setter for <code>tbluser.chrome_extension_order</code>. It will store the order of
	 * the sections in Chrome Extension
	 */
	public void setChromeExtensionOrder(String value) {
		set(34, value);
	}

	/**
	 * Getter for <code>tbluser.chrome_extension_order</code>. It will store the order of
	 * the sections in Chrome Extension
	 */
	public String getChromeExtensionOrder() {
		return (String) get(34);
	}

	/**
	 * Setter for <code>tbluser.marketing_communication</code>. This column indicates the
	 * user consent for receiving the marketing emails, updates and offers. Value is set
	 * on marking checkbox during signup
	 */
	public void setMarketingCommunication(Byte value) {
		set(35, value);
	}

	/**
	 * Getter for <code>tbluser.marketing_communication</code>. This column indicates the
	 * user consent for receiving the marketing emails, updates and offers. Value is set
	 * on marking checkbox during signup
	 */
	public Byte getMarketingCommunication() {
		return (Byte) get(35);
	}

	/**
	 * Setter for <code>tbluser.verified_using</code>. This column is used for storing
	 * whether user verified through email (1) or mobile (2) during signup
	 */
	public void setVerifiedUsing(Integer value) {
		set(36, value);
	}

	/**
	 * Getter for <code>tbluser.verified_using</code>. This column is used for storing
	 * whether user verified through email (1) or mobile (2) during signup
	 */
	public Integer getVerifiedUsing() {
		return (Integer) get(36);
	}

	/**
	 * Setter for <code>tbluser.candidate_category_weights</code>.
	 */
	public void setCandidateCategoryWeights(String value) {
		set(37, value);
	}

	/**
	 * Getter for <code>tbluser.candidate_category_weights</code>.
	 */
	public String getCandidateCategoryWeights() {
		return (String) get(37);
	}

	/**
	 * Setter for <code>tbluser.detail_page_field_count</code>. Stores the count of fields
	 * shown on the details page for the user
	 */
	public void setDetailPageFieldCount(JSON value) {
		set(38, value);
	}

	/**
	 * Getter for <code>tbluser.detail_page_field_count</code>. Stores the count of fields
	 * shown on the details page for the user
	 */
	public JSON getDetailPageFieldCount() {
		return (JSON) get(38);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TbluserRecord
	 */
	public TbluserRecord() {
		super(Tbluser.TBLUSER);
	}

	/**
	 * Create a detached, initialised TbluserRecord
	 */
	public TbluserRecord(Integer id, Integer roleid, String firstname, String lastname, String email,
			Byte verifiedemail, String verificationcode, String contactnumber, String photo, String username,
			String password, String oauthuid, Byte userstatus, String session, String apptoken, String msession,
			Integer expiresin, String slug, Integer accountid, Integer createdby, Integer createdon, Integer updatedby,
			Integer updatedon, String country, String city, String apitoken, String state, Integer lastactiveon,
			String locale, Byte apitokenactive, Integer teamid, Byte contactverified, String resetPasswordToken,
			String reactivateCode, String chromeExtensionOrder, Byte marketingCommunication, Integer verifiedUsing,
			String candidateCategoryWeights, JSON detailPageFieldCount) {
		super(Tbluser.TBLUSER);

		setId(id);
		setRoleid(roleid);
		setFirstname(firstname);
		setLastname(lastname);
		setEmail(email);
		setVerifiedemail(verifiedemail);
		setVerificationcode(verificationcode);
		setContactnumber(contactnumber);
		setPhoto(photo);
		setUsername(username);
		setPassword(password);
		setOauthuid(oauthuid);
		setUserstatus(userstatus);
		setSession(session);
		setApptoken(apptoken);
		setMsession(msession);
		setExpiresin(expiresin);
		setSlug(slug);
		setAccountid(accountid);
		setCreatedby(createdby);
		setCreatedon(createdon);
		setUpdatedby(updatedby);
		setUpdatedon(updatedon);
		setCountry(country);
		setCity(city);
		setApitoken(apitoken);
		setState(state);
		setLastactiveon(lastactiveon);
		setLocale(locale);
		setApitokenactive(apitokenactive);
		setTeamid(teamid);
		setContactverified(contactverified);
		setResetPasswordToken(resetPasswordToken);
		setReactivateCode(reactivateCode);
		setChromeExtensionOrder(chromeExtensionOrder);
		setMarketingCommunication(marketingCommunication);
		setVerifiedUsing(verifiedUsing);
		setCandidateCategoryWeights(candidateCategoryWeights);
		setDetailPageFieldCount(detailPageFieldCount);
		resetTouchedOnNotNull();
	}

}
